"""
Classes from the 'AppleAccount' framework.
"""

try:
    from rubicon.objc import ObjCClass
except ValueError:

    def ObjCClass(name):
        return None


def _Class(name):
    try:
        return ObjCClass(name)
    except NameError:
        return None


AASignInOperationHelper = _Class("AASignInOperationHelper")
AALoginContextManager = _Class("AALoginContextManager")
AAStorableLoginContext = _Class("AAStorableLoginContext")
AALoginContextTransientStorage = _Class("AALoginContextTransientStorage")
AARemoteServer = _Class("AARemoteServer")
AAAccountManager = _Class("AAAccountManager")
_AAURLSessionConfigurationTask = _Class("_AAURLSessionConfigurationTask")
AAAbsintheContext = _Class("AAAbsintheContext")
AAAccount = _Class("AAAccount")
AAQuotaDepletionAlert = _Class("AAQuotaDepletionAlert")
AAPersonaUtility = _Class("AAPersonaUtility")
AASignInFlowController = _Class("AASignInFlowController")
AARegionInfo = _Class("AARegionInfo")
AAPreferences = _Class("AAPreferences")
AAFollowUpUtilities = _Class("AAFollowUpUtilities")
AARemoteServerConfigurationCache = _Class("AARemoteServerConfigurationCache")
AAURLSession = _Class("AAURLSession")
_AAURLSessionDelegate = _Class("_AAURLSessionDelegate")
AALoginResponseAppleAccountInfo = _Class("AALoginResponseAppleAccountInfo")
AALoginPluginManager = _Class("AALoginPluginManager")
AASuspensionInfo = _Class("AASuspensionInfo")
AALoginResponseDataclasses = _Class("AALoginResponseDataclasses")
AAURLConfiguration = _Class("AAURLConfiguration")
AASigningSession = _Class("AASigningSession")
AAAcceptedTermsController = _Class("AAAcceptedTermsController")
AAAutoAccountVerifier = _Class("AAAutoAccountVerifier")
AAUserNotification = _Class("AAUserNotification")
AASignOutFlowController = _Class("AASignOutFlowController")
AAGrandSlamSigner = _Class("AAGrandSlamSigner")
AADeviceList = _Class("AADeviceList")
AADeviceProvisioningSession = _Class("AADeviceProvisioningSession")
AALocalization = _Class("AALocalization")
AAKeychainManager = _Class("AAKeychainManager")
AAFollowUpController = _Class("AAFollowUpController")
AADeviceInfo = _Class("AADeviceInfo")
AADataclassManager = _Class("AADataclassManager")
AAFamilyMember = _Class("AAFamilyMember")
AAAbsintheSigner = _Class("AAAbsintheSigner")
AAURLSessionContext = _Class("AAURLSessionContext")
AADevice = _Class("AADevice")
AAAbsintheSignerContextCache = _Class("AAAbsintheSignerContextCache")
AASetupAssistantService = _Class("AASetupAssistantService")
AACertificatePinner = _Class("AACertificatePinner")
AAFamilyInvite = _Class("AAFamilyInvite")
AAResponse = _Class("AAResponse")
AASigningSessionResponse = _Class("AASigningSessionResponse")
AADeviceProvisioningResponse = _Class("AADeviceProvisioningResponse")
AAQuotaInfoResponse = _Class("AAQuotaInfoResponse")
AAPhotoResponse = _Class("AAPhotoResponse")
AACloudKitDevicesListResponse = _Class("AACloudKitDevicesListResponse")
AACloudKitStartMigrationResponse = _Class("AACloudKitStartMigrationResponse")
AACloudKitMigrationStateResponse = _Class("AACloudKitMigrationStateResponse")
AAAvailabilityResponse = _Class("AAAvailabilityResponse")
AATrustedDeviceListResponse = _Class("AATrustedDeviceListResponse")
AADeviceListResponse = _Class("AADeviceListResponse")
AAPaymentSummaryResponse = _Class("AAPaymentSummaryResponse")
AAFamilyEligibilityResponse = _Class("AAFamilyEligibilityResponse")
AASecondaryAuthenticationResponse = _Class("AASecondaryAuthenticationResponse")
AAFamilyDetailsResponse = _Class("AAFamilyDetailsResponse")
AAAccountManagementUIResponse = _Class("AAAccountManagementUIResponse")
AALoginDelegatesResponse = _Class("AALoginDelegatesResponse")
AAFMIPAuthenticateResponse = _Class("AAFMIPAuthenticateResponse")
AACompleteEmailVettingResponse = _Class("AACompleteEmailVettingResponse")
AAMobileMeOfferResponse = _Class("AAMobileMeOfferResponse")
AAAuthenticationResponse = _Class("AAAuthenticationResponse")
AAProvisioningResponse = _Class("AAProvisioningResponse")
ATVHighSecurityAccountVerifyCodeResponse = _Class(
    "ATVHighSecurityAccountVerifyCodeResponse"
)
ATVHighSecurityAccountSendCodeResponse = _Class(
    "ATVHighSecurityAccountSendCodeResponse"
)
ATVHighSecurityAccountDeviceListResponse = _Class(
    "ATVHighSecurityAccountDeviceListResponse"
)
AASetupAssistantUpgradeStatusResponse = _Class("AASetupAssistantUpgradeStatusResponse")
AAUpgradeiOSTermsResponse = _Class("AAUpgradeiOSTermsResponse")
AASetupAssistantSetupDelegatesResponse = _Class(
    "AASetupAssistantSetupDelegatesResponse"
)
AASetupAssistantCreateResponse = _Class("AASetupAssistantCreateResponse")
AASetupAssistantConfigResponse = _Class("AASetupAssistantConfigResponse")
AALoginAccountResponse = _Class("AALoginAccountResponse")
AAiCloudTermsAgreeResponse = _Class("AAiCloudTermsAgreeResponse")
AAGenericTermsUIResponse = _Class("AAGenericTermsUIResponse")
AAiCloudTermsStringResponse = _Class("AAiCloudTermsStringResponse")
_AAURLSessionOperation = _Class("_AAURLSessionOperation")
AALoginResponseiCloudTokens = _Class("AALoginResponseiCloudTokens")
AAAttestationSigner = _Class("AAAttestationSigner")
AARequest = _Class("AARequest")
AALoginAccountRequest = _Class("AALoginAccountRequest")
AAAppleTVRequest = _Class("AAAppleTVRequest")
ATVHighSecurityAccountSendCode = _Class("ATVHighSecurityAccountSendCode")
ATVHighSecurityAccountVerifyCode = _Class("ATVHighSecurityAccountVerifyCode")
ATVHighSecurityAccountDeviceList = _Class("ATVHighSecurityAccountDeviceList")
AASigningSessionRequest = _Class("AASigningSessionRequest")
AAQuotaInfoRequest = _Class("AAQuotaInfoRequest")
AAiCloudTermsAgreeRequest = _Class("AAiCloudTermsAgreeRequest")
AAGenericTermsUIRequest = _Class("AAGenericTermsUIRequest")
AAiCloudTermsStringRequest = _Class("AAiCloudTermsStringRequest")
AAUpdateAccountUIRequest = _Class("AAUpdateAccountUIRequest")
AAMyPhotoRequest = _Class("AAMyPhotoRequest")
_AABasicGetRequest = _Class("_AABasicGetRequest")
AACloudKitDevicesListRequest = _Class("AACloudKitDevicesListRequest")
AACloudKitStartMigrationRequest = _Class("AACloudKitStartMigrationRequest")
AACloudKitMigrationStateRequest = _Class("AACloudKitMigrationStateRequest")
AAAvailabilityRequest = _Class("AAAvailabilityRequest")
AATrustedDeviceListRequest = _Class("AATrustedDeviceListRequest")
AADeviceListRequest = _Class("AADeviceListRequest")
AAFamilyRequest = _Class("AAFamilyRequest")
AAFamilyDetailsRequest = _Class("AAFamilyDetailsRequest")
AAFamilyEligibilityRequest = _Class("AAFamilyEligibilityRequest")
AASecondaryAuthenticationRequest = _Class("AASecondaryAuthenticationRequest")
AAAppleIDSettingsRequest = _Class("AAAppleIDSettingsRequest")
AAUpdateNameRequest = _Class("AAUpdateNameRequest")
AAPaymentUIRequest = _Class("AAPaymentUIRequest")
AAPasswordSecurityUIRequest = _Class("AAPasswordSecurityUIRequest")
AAPersonalInfoUIRequest = _Class("AAPersonalInfoUIRequest")
AAPaymentSummaryRequest = _Class("AAPaymentSummaryRequest")
AALoginOrCreateDelegatesRequest = _Class("AALoginOrCreateDelegatesRequest")
AALoginDelegatesRequest = _Class("AALoginDelegatesRequest")
AAFMIPAuthenticateRequest = _Class("AAFMIPAuthenticateRequest")
AAEmailVettingRequest = _Class("AAEmailVettingRequest")
AACompleteEmailVettingRequest = _Class("AACompleteEmailVettingRequest")
AAInitiateEmailVettingRequest = _Class("AAInitiateEmailVettingRequest")
AAUpdateProvisioningRequest = _Class("AAUpdateProvisioningRequest")
AAAddEmailUIRequest = _Class("AAAddEmailUIRequest")
AASetupAssistantUpgradeStatusRequest = _Class("AASetupAssistantUpgradeStatusRequest")
AASetupAssistantTermsFetchRequest = _Class("AASetupAssistantTermsFetchRequest")
AASetupAssistantSetupDelegatesRequest = _Class("AASetupAssistantSetupDelegatesRequest")
AASetupAssistantCreateRequest = _Class("AASetupAssistantCreateRequest")
AASetupAssistantUpdateRequest = _Class("AASetupAssistantUpdateRequest")
AAAuthenticateRequest = _Class("AAAuthenticateRequest")
AARegisterRequest = _Class("AARegisterRequest")
AASetupAssistantAuthenticateRequest = _Class("AASetupAssistantAuthenticateRequest")
AAURLConfigurationRequest = _Class("AAURLConfigurationRequest")
AASetupAssistantConfigRequest = _Class("AASetupAssistantConfigRequest")
AADeviceProvisioningRequest = _Class("AADeviceProvisioningRequest")
AATrustedDevice = _Class("AATrustedDevice")
AAiCloudLoginAccountRequester = _Class("AAiCloudLoginAccountRequester")
AAURLProtocol = _Class("AAURLProtocol")
AARequester = _Class("AARequester")
