"""
Classes from the 'AssetsLibraryServices' framework.
"""

try:
    from rubicon.objc import ObjCClass
except ValueError:

    def ObjCClass(name):
        return None


def _Class(name):
    try:
        return ObjCClass(name)
    except NameError:
        return None


PLAutoBindingBlackholeProxy = _Class("PLAutoBindingBlackholeProxy")
PLAppPrivateData = _Class("PLAppPrivateData")
PLVolumeInfo = _Class("PLVolumeInfo")
PLDiskController = _Class("PLDiskController")
PLAssetsdClientXPCConnection = _Class("PLAssetsdClientXPCConnection")
PLAutoBindingProxyFactory = _Class("PLAutoBindingProxyFactory")
PLXPCMessageLogger = _Class("PLXPCMessageLogger")
PLLazyObject = _Class("PLLazyObject")
PLAtomicObject = _Class("PLAtomicObject")
PLFileSystemPersistenceAttributes = _Class("PLFileSystemPersistenceAttributes")
PLFileSystemPersistenceBatchItem = _Class("PLFileSystemPersistenceBatchItem")
PLFileSystemPersistence = _Class("PLFileSystemPersistence")
PLFileSystemCapabilities = _Class("PLFileSystemCapabilities")
PLCoreAnalyticsEvent = _Class("PLCoreAnalyticsEvent")
PLAssetsdInterface = _Class("PLAssetsdInterface")
PLPhotoLibraryPathManager = _Class("PLPhotoLibraryPathManager")
PLPrivacy = _Class("PLPrivacy")
PLImageFormat = _Class("PLImageFormat")
PLExclusiveFileLock = _Class("PLExclusiveFileLock")
PLNonBindingAssetsdClient = _Class("PLNonBindingAssetsdClient")
PLAssetFormatsCore = _Class("PLAssetFormatsCore")
PLAssetsdClient = _Class("PLAssetsdClient")
PLSecurity = _Class("PLSecurity")
PLAssetsdServiceProxyFactory = _Class("PLAssetsdServiceProxyFactory")
PLResult = _Class("PLResult")
PLAssetsdClientSandboxExtensions = _Class("PLAssetsdClientSandboxExtensions")
PLImportFileManager = _Class("PLImportFileManager")
PLFileUtilities = _Class("PLFileUtilities")
PLGatekeeperClient = _Class("PLGatekeeperClient")
PLImageDataInfo = _Class("PLImageDataInfo")
PLCPLDownloadContext = _Class("PLCPLDownloadContext")
PLLibraryServicesStateNode = _Class("PLLibraryServicesStateNode")
PLSandboxHelper = _Class("PLSandboxHelper")
PLBuildVersion = _Class("PLBuildVersion")
PLCoreAnalyticsEventManager = _Class("PLCoreAnalyticsEventManager")
PLFormatChooser = _Class("PLFormatChooser")
PLLibraryBookmarkManager = _Class("PLLibraryBookmarkManager")
PLQueryBuilder = _Class("PLQueryBuilder")
PLDeviceConfiguration = _Class("PLDeviceConfiguration")
PLAssetsdClientService = _Class("PLAssetsdClientService")
PLPhotoDCIMDirectory = _Class("PLPhotoDCIMDirectory")
PLCPLPlistHandler = _Class("PLCPLPlistHandler")
PLXPCObject = _Class("PLXPCObject")
PLXPCShMemObject = _Class("PLXPCShMemObject")
PLXPCDictionary = _Class("PLXPCDictionary")
PLXPCFileDescriptor = _Class("PLXPCFileDescriptor")
PLXPCGenericObject = _Class("PLXPCGenericObject")
PLXPCTransaction = _Class("PLXPCTransaction")
PLCIFilterUtilities = _Class("PLCIFilterUtilities")
PLPhotoLibraryFileIdentifier = _Class("PLPhotoLibraryFileIdentifier")
PLPhotoLibraryPathManagerCore = _Class("PLPhotoLibraryPathManagerCore")
PLPhotoLibraryPathManagerDCIM = _Class("PLPhotoLibraryPathManagerDCIM")
PLPhotoLibraryPathManagerUBF = _Class("PLPhotoLibraryPathManagerUBF")
PLPositionalImageTable = _Class("PLPositionalImageTable")
PLThumbnailManagerCore = _Class("PLThumbnailManagerCore")
PLThumbFileManagerCore = _Class("PLThumbFileManagerCore")
PLMigrationServiceOptions = _Class("PLMigrationServiceOptions")
PLAssetsdBaseClient = _Class("PLAssetsdBaseClient")
PLAssetsdResourceClient = _Class("PLAssetsdResourceClient")
PLAssetsdDiagnosticsClient = _Class("PLAssetsdDiagnosticsClient")
PLAssetsdSystemLibraryURLReadOnlyClient = _Class(
    "PLAssetsdSystemLibraryURLReadOnlyClient"
)
PLAssetsdCloudClient = _Class("PLAssetsdCloudClient")
PLAssetsdPrivacySupportClient = _Class("PLAssetsdPrivacySupportClient")
PLAssetsdResourceInternalClient = _Class("PLAssetsdResourceInternalClient")
PLAssetsdPhotoKitAddClient = _Class("PLAssetsdPhotoKitAddClient")
PLAssetsdMigrationClient = _Class("PLAssetsdMigrationClient")
PLAssetsdCloudInternalClient = _Class("PLAssetsdCloudInternalClient")
PLAssetsdLibraryManagementClient = _Class("PLAssetsdLibraryManagementClient")
PLAssetsdLibraryInternalClient = _Class("PLAssetsdLibraryInternalClient")
PLAssetsdDebugClient = _Class("PLAssetsdDebugClient")
PLAssetsdResourceAvailabilityClient = _Class("PLAssetsdResourceAvailabilityClient")
PLAssetsdDemoClient = _Class("PLAssetsdDemoClient")
PLAssetsdSyncClient = _Class("PLAssetsdSyncClient")
PLAssetsdPhotoKitClient = _Class("PLAssetsdPhotoKitClient")
PLAssetsdResourceWriteOnlyClient = _Class("PLAssetsdResourceWriteOnlyClient")
PLAssetsdLibraryClient = _Class("PLAssetsdLibraryClient")
PLAssetsdNotificationClient = _Class("PLAssetsdNotificationClient")
PLPhotoDCFObject = _Class("PLPhotoDCFObject")
PLPhotoDCFFileGroup = _Class("PLPhotoDCFFileGroup")
PLPhotoDCFDirectory = _Class("PLPhotoDCFDirectory")
PLSingleQuery = _Class("PLSingleQuery")
PLQuery = _Class("PLQuery")
PLLibraryServicesOperation = _Class("PLLibraryServicesOperation")
PLUUIDString = _Class("PLUUIDString")
PLSandboxedURL = _Class("PLSandboxedURL")
PLXPCShMemData = _Class("PLXPCShMemData")
