"""
Classes from the 'AssistantServices' framework.
"""

try:
    from rubicon.objc import ObjCClass
except ValueError:

    def ObjCClass(name):
        return None


def _Class(name):
    try:
        return ObjCClass(name)
    except NameError:
        return None


AFAccessibilityObserver = _Class("AFAccessibilityObserver")
AFSiriTask = _Class("AFSiriTask")
_AFClientInfoMutation = _Class("_AFClientInfoMutation")
AFClientInfo = _Class("AFClientInfo")
_AFPeerInfoMutation = _Class("_AFPeerInfoMutation")
AFPeerInfo = _Class("AFPeerInfo")
AFSyncSnapshot = _Class("AFSyncSnapshot")
AFContextDonationService = _Class("AFContextDonationService")
AFPowerAssertionManager = _Class("AFPowerAssertionManager")
_AFClockAlarmMutation = _Class("_AFClockAlarmMutation")
AFClockAlarm = _Class("AFClockAlarm")
AFApplicationInfo = _Class("AFApplicationInfo")
AFRequestCompletionOptions = _Class("AFRequestCompletionOptions")
AFChildConversationItemList = _Class("AFChildConversationItemList")
AFInterstitialCommandWrapper = _Class("AFInterstitialCommandWrapper")
_AFMediaPlaybackStateSnapshotMutation = _Class("_AFMediaPlaybackStateSnapshotMutation")
AFMediaPlaybackStateSnapshot = _Class("AFMediaPlaybackStateSnapshot")
AFConversationInsertion = _Class("AFConversationInsertion")
AFPairedBluetoothDevicesObserver = _Class("AFPairedBluetoothDevicesObserver")
AFConnectionEntitlementCache = _Class("AFConnectionEntitlementCache")
_AFSiriActivationResultMutation = _Class("_AFSiriActivationResultMutation")
AFSiriActivationResult = _Class("AFSiriActivationResult")
AFAnalyticsEvent = _Class("AFAnalyticsEvent")
STSiriContext = _Class("STSiriContext")
AFMultiUserConnection = _Class("AFMultiUserConnection")
_AFInterstitialConfigurationMutation = _Class("_AFInterstitialConfigurationMutation")
AFInterstitialConfiguration = _Class("AFInterstitialConfiguration")
AFMyriadEmergencyCallPunchout = _Class("AFMyriadEmergencyCallPunchout")
_AFSpeechSynthesisRecordMutation = _Class("_AFSpeechSynthesisRecordMutation")
AFSpeechSynthesisRecord = _Class("AFSpeechSynthesisRecord")
AFSiriActivationRequest = _Class("AFSiriActivationRequest")
AFSiriAceRequest = _Class("AFSiriAceRequest")
AFSiriMusicSmartPlayRequest = _Class("AFSiriMusicSmartPlayRequest")
AFSiriMusicSubscriptionLeaseTakenRequest = _Class(
    "AFSiriMusicSubscriptionLeaseTakenRequest"
)
AFSiriAcousticIDRequest = _Class("AFSiriAcousticIDRequest")
_AFSiriClientState = _Class("_AFSiriClientState")
AFSiriClientStateManager = _Class("AFSiriClientStateManager")
AFAnalyticsObserverConnection = _Class("AFAnalyticsObserverConnection")
AFAppContextAggregator = _Class("AFAppContextAggregator")
AFBluetoothWirelessSplitterSessionStateObserver = _Class(
    "AFBluetoothWirelessSplitterSessionStateObserver"
)
STPersonContactHandle = _Class("STPersonContactHandle")
AFNotifyStatePublisher = _Class("AFNotifyStatePublisher")
AFAudioPowerUpdater = _Class("AFAudioPowerUpdater")
_AFSharedConfidenceScoreMutation = _Class("_AFSharedConfidenceScoreMutation")
AFSharedConfidenceScore = _Class("AFSharedConfidenceScore")
AFMyriadCoordinator = _Class("AFMyriadCoordinator")
_AFApplicationContextMutation = _Class("_AFApplicationContextMutation")
AFApplicationContext = _Class("AFApplicationContext")
AFConversationItem = _Class("AFConversationItem")
_AFBundleResourceMutation = _Class("_AFBundleResourceMutation")
AFBundleResource = _Class("AFBundleResource")
_AFAudioPlaybackRequestMutation = _Class("_AFAudioPlaybackRequestMutation")
AFAudioPlaybackRequest = _Class("AFAudioPlaybackRequest")
AFSiriTether = _Class("AFSiriTether")
AFAggregator = _Class("AFAggregator")
AFSpeechAudioAnalytics = _Class("AFSpeechAudioAnalytics")
AFSpeechAcousticFeature = _Class("AFSpeechAcousticFeature")
AFClockAlarmObserver = _Class("AFClockAlarmObserver")
AFInstrumentationObserverConnection = _Class("AFInstrumentationObserverConnection")
AFMachServiceSiriTaskDeliverer = _Class("AFMachServiceSiriTaskDeliverer")
AFAnalyticsTurnBasedInstrumentationContext = _Class(
    "AFAnalyticsTurnBasedInstrumentationContext"
)
AFDialogPhase = _Class("AFDialogPhase")
AFBulletin = _Class("AFBulletin")
AFMyriadEmergencyManager = _Class("AFMyriadEmergencyManager")
AFUIApplicationSiriTaskDeliverer = _Class("AFUIApplicationSiriTaskDeliverer")
AFClockTimerObserver = _Class("AFClockTimerObserver")
AFUtteranceSuggestions = _Class("AFUtteranceSuggestions")
AFDeviceRingerSwitchObserver = _Class("AFDeviceRingerSwitchObserver")
AFSiriActivationListener = _Class("AFSiriActivationListener")
_AFSiriActivationContextMutation = _Class("_AFSiriActivationContextMutation")
AFSiriActivationContext = _Class("AFSiriActivationContext")
_AFMemoryInfoMutation = _Class("_AFMemoryInfoMutation")
AFMemoryInfo = _Class("AFMemoryInfo")
STSiriLocation = _Class("STSiriLocation")
AFDisambiguationStore = _Class("AFDisambiguationStore")
AFAssertionCoordinator = _Class("AFAssertionCoordinator")
_AFAssertionProxy = _Class("_AFAssertionProxy")
_AFAssertionRecord = _Class("_AFAssertionRecord")
AFTreeNodePropertyListSerialization = _Class("AFTreeNodePropertyListSerialization")
AFSiriTaskmaster = _Class("AFSiriTaskmaster")
AFSiriTaskDeliveryHandler = _Class("AFSiriTaskDeliveryHandler")
AFSiriTaskService = _Class("AFSiriTaskService")
AFDeviceCapabilities = _Class("AFDeviceCapabilities")
_AFExperimentContextMutation = _Class("_AFExperimentContextMutation")
AFExperimentContext = _Class("AFExperimentContext")
_AFClockTimerSnapshotMutation = _Class("_AFClockTimerSnapshotMutation")
AFClockTimerSnapshot = _Class("AFClockTimerSnapshot")
AFPluginManager = _Class("AFPluginManager")
AFClientPluginManager = _Class("AFClientPluginManager")
AFPluginBundle = _Class("AFPluginBundle")
_AFClockAlarmSnapshotMutation = _Class("_AFClockAlarmSnapshotMutation")
AFClockAlarmSnapshot = _Class("AFClockAlarmSnapshot")
_AFAudioDeviceInfoMutation = _Class("_AFAudioDeviceInfoMutation")
AFAudioDeviceInfo = _Class("AFAudioDeviceInfo")
_AFLocationSnapshotMutation = _Class("_AFLocationSnapshotMutation")
AFLocationSnapshot = _Class("AFLocationSnapshot")
AFSiriActivationHandlerCoreSpeechDaemon = _Class(
    "AFSiriActivationHandlerCoreSpeechDaemon"
)
AFServiceContextSnapshot = _Class("AFServiceContextSnapshot")
AFServiceMediaPlaybackStateSnapshot = _Class("AFServiceMediaPlaybackStateSnapshot")
AFLinkedListItem = _Class("AFLinkedListItem")
STCity = _Class("STCity")
AFSiriActivationHandlerFrontendProcess = _Class(
    "AFSiriActivationHandlerFrontendProcess"
)
AFSettingsConnectionServiceDelegate = _Class("AFSettingsConnectionServiceDelegate")
AFSettingsConnection = _Class("AFSettingsConnection")
AFSiriUserNotificationRequestCapabilityManager = _Class(
    "AFSiriUserNotificationRequestCapabilityManager"
)
AFSiriUserNotificationRequest = _Class("AFSiriUserNotificationRequest")
AFSiriNotificationRequest = _Class("AFSiriNotificationRequest")
AFMetrics = _Class("AFMetrics")
_AFMyriadSessionMutation = _Class("_AFMyriadSessionMutation")
AFMyriadSession = _Class("AFMyriadSession")
AFOpportuneSpeakingModelFeedbackManager = _Class(
    "AFOpportuneSpeakingModelFeedbackManager"
)
AFOpportuneSpeakingModelFeedback = _Class("AFOpportuneSpeakingModelFeedback")
AFThreeArgumentSafetyBlock = _Class("AFThreeArgumentSafetyBlock")
AFTwoArgumentSafetyBlock = _Class("AFTwoArgumentSafetyBlock")
AFOneArgumentSafetyBlock = _Class("AFOneArgumentSafetyBlock")
AFSafetyBlock = _Class("AFSafetyBlock")
AFFuture = _Class("AFFuture")
AFRemoteRequestWatcher = _Class("AFRemoteRequestWatcher")
AFManagedStorageConnection = _Class("AFManagedStorageConnection")
AFAccount = _Class("AFAccount")
AFTriggerlessListeningOptions = _Class("AFTriggerlessListeningOptions")
AFMemoryPressureObserver = _Class("AFMemoryPressureObserver")
AFAnalyticsEventRecord = _Class("AFAnalyticsEventRecord")
_AFAssertionContextMutation = _Class("_AFAssertionContextMutation")
AFAssertionContext = _Class("AFAssertionContext")
AFConversationStore = _Class("AFConversationStore")
AFAudioAnalyzer = _Class("AFAudioAnalyzer")
_AFBluetoothHeadphoneInEarDetectionStateMutation = _Class(
    "_AFBluetoothHeadphoneInEarDetectionStateMutation"
)
AFBluetoothHeadphoneInEarDetectionState = _Class(
    "AFBluetoothHeadphoneInEarDetectionState"
)
_AFDataStoreEntry = _Class("_AFDataStoreEntry")
AFDataStore = _Class("AFDataStore")
AFImagePNGData = _Class("AFImagePNGData")
AFLocalization = _Class("AFLocalization")
AFMediaRemoteDeviceInfo = _Class("AFMediaRemoteDeviceInfo")
AFClientLite = _Class("AFClientLite")
AFSynchronousClientLite = _Class("AFSynchronousClientLite")
AFClientLiteInternal = _Class("AFClientLiteInternal")
AFClockItemStorage = _Class("AFClockItemStorage")
AFRequestInfo = _Class("AFRequestInfo")
_AFExperimentMutation = _Class("_AFExperimentMutation")
AFExperiment = _Class("AFExperiment")
_AFSpeechRecordingAlertPolicyMutation = _Class("_AFSpeechRecordingAlertPolicyMutation")
AFSpeechRecordingAlertPolicy = _Class("AFSpeechRecordingAlertPolicy")
AFFeatureFlags = _Class("AFFeatureFlags")
AFSiriTaskUsageResult = _Class("AFSiriTaskUsageResult")
_AFBluetoothDeviceInfoMutation = _Class("_AFBluetoothDeviceInfoMutation")
AFBluetoothDeviceInfo = _Class("AFBluetoothDeviceInfo")
AFSiriActivationHandlerAssistantDaemon = _Class(
    "AFSiriActivationHandlerAssistantDaemon"
)
AFDictationConnectionServiceDelegate = _Class("AFDictationConnectionServiceDelegate")
AFNotifyObserver = _Class("AFNotifyObserver")
_AFSpeakableUtterancePassThroughProvider = _Class(
    "_AFSpeakableUtterancePassThroughProvider"
)
AFSpeakableUtteranceParser = _Class("AFSpeakableUtteranceParser")
AFSUPFunctionProvider = _Class("AFSUPFunctionProvider")
_AFClientConfigurationMutation = _Class("_AFClientConfigurationMutation")
AFClientConfiguration = _Class("AFClientConfiguration")
AFMyriadMonitor = _Class("AFMyriadMonitor")
_AFMyriadAdvertisementContextMutation = _Class("_AFMyriadAdvertisementContextMutation")
AFMyriadAdvertisementContext = _Class("AFMyriadAdvertisementContext")
AFConversation = _Class("AFConversation")
AFCoercion = _Class("AFCoercion")
AFSiriTaskContextProvider = _Class("AFSiriTaskContextProvider")
AFAssistedDisambiguationRules = _Class("AFAssistedDisambiguationRules")
AFTreeNode = _Class("AFTreeNode")
AFAudioState = _Class("AFAudioState")
AFSpeechRecognition = _Class("AFSpeechRecognition")
AFOpportuneSpeakingModuleDataCollection = _Class(
    "AFOpportuneSpeakingModuleDataCollection"
)
AFOpportuneSpeakingModuleDataCollectionSanitizedSpeakable = _Class(
    "AFOpportuneSpeakingModuleDataCollectionSanitizedSpeakable"
)
AFConnectionUserInteractionAssertion = _Class("AFConnectionUserInteractionAssertion")
AFMyriadRecord = _Class("AFMyriadRecord")
_AFDeleteSiriHistoryContextMutation = _Class("_AFDeleteSiriHistoryContextMutation")
AFDeleteSiriHistoryContext = _Class("AFDeleteSiriHistoryContext")
AFSpeechToken = _Class("AFSpeechToken")
AFSpeechInterpretation = _Class("AFSpeechInterpretation")
AFSpeechUtterance = _Class("AFSpeechUtterance")
AFSpeechPhrase = _Class("AFSpeechPhrase")
AFDictionarySchema = _Class("AFDictionarySchema")
_AFMyriadPerceptualAudioHashMutation = _Class("_AFMyriadPerceptualAudioHashMutation")
AFMyriadPerceptualAudioHash = _Class("AFMyriadPerceptualAudioHash")
_AFSpeechRecordingAlertBehaviorMutation = _Class(
    "_AFSpeechRecordingAlertBehaviorMutation"
)
AFSpeechRecordingAlertBehavior = _Class("AFSpeechRecordingAlertBehavior")
AFSpeechPackage = _Class("AFSpeechPackage")
AFSyncInfo = _Class("AFSyncInfo")
AFAnalyticsConnection = _Class("AFAnalyticsConnection")
_AFClockTimerMutation = _Class("_AFClockTimerMutation")
AFClockTimer = _Class("AFClockTimer")
AFUserUtteranceSelectionResults = _Class("AFUserUtteranceSelectionResults")
AFUserUtterance = _Class("AFUserUtterance")
AFPersonalUserSettings = _Class("AFPersonalUserSettings")
_AFAccessibilityStateMutation = _Class("_AFAccessibilityStateMutation")
AFAccessibilityState = _Class("AFAccessibilityState")
AFUserNotificationProvider = _Class("AFUserNotificationProvider")
AFNowPlayingObserver = _Class("AFNowPlayingObserver")
AFContextManager = _Class("AFContextManager")
_AFAudioPowerXPCSharedMemory = _Class("_AFAudioPowerXPCSharedMemory")
AFAudioPowerXPCProvider = _Class("AFAudioPowerXPCProvider")
AFError = _Class("AFError")
AFConversationTransaction = _Class("AFConversationTransaction")
AFLanguageDetectionUserContext = _Class("AFLanguageDetectionUserContext")
AFXPCWrapper = _Class("AFXPCWrapper")
AFPhonemeMapper = _Class("AFPhonemeMapper")
AFSiriActivationConnection = _Class("AFSiriActivationConnection")
_AFMyriadContextMutation = _Class("_AFMyriadContextMutation")
AFMyriadContext = _Class("AFMyriadContext")
_AFMultiUserStateSnapshotMutation = _Class("_AFMultiUserStateSnapshotMutation")
AFMultiUserStateSnapshot = _Class("AFMultiUserStateSnapshot")
AFDisambiguationEvent = _Class("AFDisambiguationEvent")
AFDisambiguationInfo = _Class("AFDisambiguationInfo")
AFWatchdogTimer = _Class("AFWatchdogTimer")
AFSiriResponse = _Class("AFSiriResponse")
AFSetSettingsResponse = _Class("AFSetSettingsResponse")
AFObjectUpdatedSiriResponse = _Class("AFObjectUpdatedSiriResponse")
AFGetSettingsResponse = _Class("AFGetSettingsResponse")
AFContextResponse = _Class("AFContextResponse")
AFCreateAlarmResponse = _Class("AFCreateAlarmResponse")
AFUpdateAlarmResponse = _Class("AFUpdateAlarmResponse")
AFSearchAlarmsResponse = _Class("AFSearchAlarmsResponse")
AFObjectCreatedSiriResponse = _Class("AFObjectCreatedSiriResponse")
AFGetTimerResponse = _Class("AFGetTimerResponse")
AFSiriRequestSucceededResponse = _Class("AFSiriRequestSucceededResponse")
_AFExperimentGroupMutation = _Class("_AFExperimentGroupMutation")
AFExperimentGroup = _Class("AFExperimentGroup")
AFSiriTaskExecution = _Class("AFSiriTaskExecution")
AFRemoteRequest = _Class("AFRemoteRequest")
AFMyriadAdvertisementContextRecord = _Class("AFMyriadAdvertisementContextRecord")
AFPhonemeTranscription = _Class("AFPhonemeTranscription")
AFFlowServiceConnection = _Class("AFFlowServiceConnection")
AFBundleResourceManager = _Class("AFBundleResourceManager")
AFMutableConversationItem = _Class("AFMutableConversationItem")
AFVoiceInfo = _Class("AFVoiceInfo")
STSiriModelObject = _Class("STSiriModelObject")
STPerson = _Class("STPerson")
STSetting = _Class("STSetting")
STCall = _Class("STCall")
STAlarm = _Class("STAlarm")
STSiriMessage = _Class("STSiriMessage")
STSettingChange = _Class("STSettingChange")
STTimer = _Class("STTimer")
STContactAddress = _Class("STContactAddress")
_AFBluetoothWirelessSplitterSessionInfoMutation = _Class(
    "_AFBluetoothWirelessSplitterSessionInfoMutation"
)
AFBluetoothWirelessSplitterSessionInfo = _Class(
    "AFBluetoothWirelessSplitterSessionInfo"
)
AFMyriadAdvertisementContextManager = _Class("AFMyriadAdvertisementContextManager")
AFQueue = _Class("AFQueue")
AFSecurityConnection = _Class("AFSecurityConnection")
_AFExperimentConfigurationMutation = _Class("_AFExperimentConfigurationMutation")
AFExperimentConfiguration = _Class("AFExperimentConfiguration")
AFDeviceStateConnection = _Class("AFDeviceStateConnection")
AFSiriPhoneticContactNames = _Class("AFSiriPhoneticContactNames")
AFSiriRingtone = _Class("AFSiriRingtone")
AFSiriRequest = _Class("AFSiriRequest")
AFShowAlarmRequest = _Class("AFShowAlarmRequest")
AFContextRequest = _Class("AFContextRequest")
AFInitiateCallRequest = _Class("AFInitiateCallRequest")
AFSearchAlarmsRequest = _Class("AFSearchAlarmsRequest")
AFCreateAlarmRequest = _Class("AFCreateAlarmRequest")
AFShowTimerRequest = _Class("AFShowTimerRequest")
AFShowNextEventRequest = _Class("AFShowNextEventRequest")
AFShowSettingRequest = _Class("AFShowSettingRequest")
AFCreateMessageRequest = _Class("AFCreateMessageRequest")
AFUpdateMessageRequest = _Class("AFUpdateMessageRequest")
AFDeleteAlarmRequest = _Class("AFDeleteAlarmRequest")
AFDismissTimerRequest = _Class("AFDismissTimerRequest")
AFSiriDebugUIRequest = _Class("AFSiriDebugUIRequest")
AFSetTimerRequest = _Class("AFSetTimerRequest")
AFGetTimerRequest = _Class("AFGetTimerRequest")
AFDismissAlarmRequest = _Class("AFDismissAlarmRequest")
AFSetSettingsRequest = _Class("AFSetSettingsRequest")
AFGetSettingsRequest = _Class("AFGetSettingsRequest")
AFUpdateAlarmRequest = _Class("AFUpdateAlarmRequest")
_AFInterstitialAction = _Class("_AFInterstitialAction")
AFInterstitialProvider = _Class("AFInterstitialProvider")
AFConnectionClientServiceDelegate = _Class("AFConnectionClientServiceDelegate")
AFConnection = _Class("AFConnection")
AFConnectionAvailabilityObserver = _Class("AFConnectionAvailabilityObserver")
AFSpeechCorrectionInfo = _Class("AFSpeechCorrectionInfo")
AFSpeechRequestOptions = _Class("AFSpeechRequestOptions")
AFDictationOptions = _Class("AFDictationOptions")
AFNetworkAvailability = _Class("AFNetworkAvailability")
AFAnalytics = _Class("AFAnalytics")
_AFCallSiteInfoMutation = _Class("_AFCallSiteInfoMutation")
AFCallSiteInfo = _Class("AFCallSiteInfo")
SISchemaClientAnyEvent = _Class("SISchemaClientAnyEvent")
SISchemaClientTurnContext = _Class("SISchemaClientTurnContext")
SISchemaClientTurnBasedEvent = _Class("SISchemaClientTurnBasedEvent")
AFPreferences = _Class("AFPreferences")
AFDictationConnection = _Class("AFDictationConnection")
AFConversationError = _Class("AFConversationError")
