"""
Classes from the 'CalendarFoundation' framework.
"""

try:
    from rubicon.objc import ObjCClass
except ValueError:

    def ObjCClass(name):
        return None


def _Class(name):
    try:
        return ObjCClass(name)
    except NameError:
        return None


CalDescriptionBuilder = _Class("CalDescriptionBuilder")
CalSystemInformation = _Class("CalSystemInformation")
CalLocationBundle = _Class("CalLocationBundle")
CalLimitingQueue = _Class("CalLimitingQueue")
CalRoute = _Class("CalRoute")
CalLocation = _Class("CalLocation")
CalNWideQueue = _Class("CalNWideQueue")
CalDisjointDateRange = _Class("CalDisjointDateRange")
CalDateRange = _Class("CalDateRange")
CalFoundationPreferences = _Class("CalFoundationPreferences")
CalLogEnvelope = _Class("CalLogEnvelope")
CalAccountUtils = _Class("CalAccountUtils")
CalRecurrenceGenerator = _Class("CalRecurrenceGenerator")
EKFoundInAppsEventTracker = _Class("EKFoundInAppsEventTracker")
CalLogConfiguration = _Class("CalLogConfiguration")
CalUMCalendarDataContainerProvider = _Class("CalUMCalendarDataContainerProvider")
CalStopwatch = _Class("CalStopwatch")
CalPreferences = _Class("CalPreferences")
CalSpotlightQueryController = _Class("CalSpotlightQueryController")
CalSpotlightPendingSearch = _Class("CalSpotlightPendingSearch")
CalSpotlightQueryResult = _Class("CalSpotlightQueryResult")
CalRecurrenceDayOfWeek = _Class("CalRecurrenceDayOfWeek")
CalDispatchQueueAsyncBlockPerformer = _Class("CalDispatchQueueAsyncBlockPerformer")
CalCrashReporter = _Class("CalCrashReporter")
CalDarwinNotificationListener = _Class("CalDarwinNotificationListener")
CalFileSensor = _Class("CalFileSensor")
CalDefaultDictionary = _Class("CalDefaultDictionary")
EKStats = _Class("EKStats")
CalRecurrenceRuleDescriptionGenerator = _Class("CalRecurrenceRuleDescriptionGenerator")
CalMockCalendarDataContainerProvider = _Class("CalMockCalendarDataContainerProvider")
EKSuggestionsServiceLogger = _Class("EKSuggestionsServiceLogger")
CalGrantedDelegate = _Class("CalGrantedDelegate")
CalendarColors = _Class("CalendarColors")
CalGeocoder = _Class("CalGeocoder")
CalDateLocalization = _Class("CalDateLocalization")
CalCalendarConstraints = _Class("CalCalendarConstraints")
CalFloatingDateHelper = _Class("CalFloatingDateHelper")
CalDefaults = _Class("CalDefaults")
CalEntitlementsVerifier = _Class("CalEntitlementsVerifier")
CalDeviceLockObserver = _Class("CalDeviceLockObserver")
CalFoundationBundle = _Class("CalFoundationBundle")
EKCalendarDate = _Class("EKCalendarDate")
EKMutableCalendarDate = _Class("EKMutableCalendarDate")
CalLocationPrediction = _Class("CalLocationPrediction")
CaliCalendarPRODID = _Class("CaliCalendarPRODID")
CalWellKnownPaths = _Class("CalWellKnownPaths")
CalStructuredDataArchiver = _Class("CalStructuredDataArchiver")
CalLogBasicTextFormatter = _Class("CalLogBasicTextFormatter")
CalChronometry = _Class("CalChronometry")
CalAttachmentUtils = _Class("CalAttachmentUtils")
CalCancelablePerformSelector = _Class("CalCancelablePerformSelector")
CalPerformSelectorAsyncBlockPerformer = _Class("CalPerformSelectorAsyncBlockPerformer")
CalChangeHistoryCollector = _Class("CalChangeHistoryCollector")
CalContactsProvider = _Class("CalContactsProvider")
CalSuggestionsProvider = _Class("CalSuggestionsProvider")
CalLogFilter = _Class("CalLogFilter")
CalAsyncBlockQueue = _Class("CalAsyncBlockQueue")
CalCancelableDispatchBlock = _Class("CalCancelableDispatchBlock")
CalNSDateProvider = _Class("CalNSDateProvider")
CalAccumulatingQueue = _Class("CalAccumulatingQueue")
CalLazyCreateUtils = _Class("CalLazyCreateUtils")
CalLogXMLFormatter = _Class("CalLogXMLFormatter")
CalSignalSensor = _Class("CalSignalSensor")
EKTimeZone = _Class("EKTimeZone")
CalCancelableRunLoopPerformBlock = _Class("CalCancelableRunLoopPerformBlock")
CalLogNode = _Class("CalLogNode")
CalLogWriter = _Class("CalLogWriter")
CalLogFileWriter = _Class("CalLogFileWriter")
CalOSLogWriter = _Class("CalOSLogWriter")
CalLogNSLogWriter = _Class("CalLogNSLogWriter")
CalEmailProvider = _Class("CalEmailProvider")
CalLocationManagerDelegate = _Class("CalLocationManagerDelegate")
CalLocationManager = _Class("CalLocationManager")
CalCancellableSearch = _Class("CalCancellableSearch")
EKProtocolObject_Shared = _Class("EKProtocolObject_Shared")
CalTimeIntervalLocalization = _Class("CalTimeIntervalLocalization")
CaliCalendarAnonymizer = _Class("CaliCalendarAnonymizer")
CalLogMaster = _Class("CalLogMaster")
CalWidgetUtils = _Class("CalWidgetUtils")
CalLocationAuthorization = _Class("CalLocationAuthorization")
CalLocationAuthorizationStatus = _Class("CalLocationAuthorizationStatus")
EKTTLEventTracker = _Class("EKTTLEventTracker")
