"""
Classes from the 'CloudPhotoLibrary' framework.
"""

try:
    from rubicon.objc import ObjCClass
except ValueError:

    def ObjCClass(name):
        return None


def _Class(name):
    try:
        return ObjCClass(name)
    except NameError:
        return None


CPLDateFormatter = _Class("CPLDateFormatter")
CPLPlatform = _Class("CPLPlatform")
CPLChangeBatch = _Class("CPLChangeBatch")
CPLNetworkIndicator = _Class("CPLNetworkIndicator")
CPLChangeSessionContext = _Class("CPLChangeSessionContext")
CPLExtractedBatch = _Class("CPLExtractedBatch")
CPLMomentShareParticipant = _Class("CPLMomentShareParticipant")
CPLRejectedRecords = _Class("CPLRejectedRecords")
_CPLScheduledOverride = _Class("_CPLScheduledOverride")
CPLEngineSystemMonitor = _Class("CPLEngineSystemMonitor")
_CPLForcedSyncHistory = _Class("_CPLForcedSyncHistory")
CPLEngineSyncManager = _Class("CPLEngineSyncManager")
_CPLEngineSyncLastError = _Class("_CPLEngineSyncLastError")
_CPLTransientStatus = _Class("_CPLTransientStatus")
CPLFeatureVersionHistory = _Class("CPLFeatureVersionHistory")
_CPLOptimisticIDMapping = _Class("_CPLOptimisticIDMapping")
CPLMomentShare = _Class("CPLMomentShare")
CPLBatteryMonitor = _Class("CPLBatteryMonitor")
CPLFeature = _Class("CPLFeature")
CPLMomentShareFeature = _Class("CPLMomentShareFeature")
CPLPushChangeTasks = _Class("CPLPushChangeTasks")
CPLEngineFeedbackManager = _Class("CPLEngineFeedbackManager")
CPLSyncStep = _Class("CPLSyncStep")
CPLPullFromTransportSyncStep = _Class("CPLPullFromTransportSyncStep")
CPLSimpleTaskSyncStep = _Class("CPLSimpleTaskSyncStep")
CPLPushToTransportSyncStep = _Class("CPLPushToTransportSyncStep")
CPLEngineComponentEnumerator = _Class("CPLEngineComponentEnumerator")
CPLEngineLibrary = _Class("CPLEngineLibrary")
CPLPushSessionTracker = _Class("CPLPushSessionTracker")
CPLFileWatcher = _Class("CPLFileWatcher")
CPLSyncIndicator = _Class("CPLSyncIndicator")
CPLRecordChangeDiffTracker = _Class("CPLRecordChangeDiffTracker")
CPLContainerRelation = _Class("CPLContainerRelation")
CPLLibraryState = _Class("CPLLibraryState")
CPLLibraryInfo = _Class("CPLLibraryInfo")
CPLBatchExtractionStep = _Class("CPLBatchExtractionStep")
CPLTrashedAssetExtractionStep = _Class("CPLTrashedAssetExtractionStep")
CPLNewAssetExtractionStep = _Class("CPLNewAssetExtractionStep")
CPLDeleteAlbumExtractionStep = _Class("CPLDeleteAlbumExtractionStep")
CPLNewAlbumExtractionStep = _Class("CPLNewAlbumExtractionStep")
CPLByClassExtractionStep = _Class("CPLByClassExtractionStep")
CPLRecordStorageView = _Class("CPLRecordStorageView")
CPLClientCacheBaseView = _Class("CPLClientCacheBaseView")
CPLChangedRecordStorageView = _Class("CPLChangedRecordStorageView")
CPLChangeStorage = _Class("CPLChangeStorage")
CPLChangeBatchChangeStorage = _Class("CPLChangeBatchChangeStorage")
CPLUnacknowledgedChangeStorage = _Class("CPLUnacknowledgedChangeStorage")
CPLPushRepositoryStorage = _Class("CPLPushRepositoryStorage")
CPLDiffTracker = _Class("CPLDiffTracker")
CPLCodingPropertyEntry = _Class("CPLCodingPropertyEntry")
CPLResource = _Class("CPLResource")
CPLLibraryManager = _Class("CPLLibraryManager")
_CPLWeakLibraryManager = _Class("_CPLWeakLibraryManager")
CPLActiveDownloadQueue = _Class("CPLActiveDownloadQueue")
CPLSimpleMergeHelper = _Class("CPLSimpleMergeHelper")
CPLSimpleMerger = _Class("CPLSimpleMerger")
CPLRecordStatus = _Class("CPLRecordStatus")
CPLScopedIdentifier = _Class("CPLScopedIdentifier")
CPLShare = _Class("CPLShare")
CPLErrors = _Class("CPLErrors")
CPLConfiguration = _Class("CPLConfiguration")
CPLDerivativesFilter = _Class("CPLDerivativesFilter")
CPLEngineDerivativesCache = _Class("CPLEngineDerivativesCache")
_CPLResourcesMutableArray = _Class("_CPLResourcesMutableArray")
CPLChangeSession = _Class("CPLChangeSession")
CPLPushChangeSession = _Class("CPLPushChangeSession")
CPLPullChangeSession = _Class("CPLPullChangeSession")
CPLScopeFilter = _Class("CPLScopeFilter")
_CPLEngineScopeCache = _Class("_CPLEngineScopeCache")
CPLEngineScheduler = _Class("CPLEngineScheduler")
CPLTransaction = _Class("CPLTransaction")
CPLStatus = _Class("CPLStatus")
CPLResetReason = _Class("CPLResetReason")
CPLResetTracker = _Class("CPLResetTracker")
CPLPlaceAnnotation = _Class("CPLPlaceAnnotation")
CPLEngineScopeFlagsUpdate = _Class("CPLEngineScopeFlagsUpdate")
CPLEngineScope = _Class("CPLEngineScope")
CPLEngineTransport = _Class("CPLEngineTransport")
CPLResourceIdentity = _Class("CPLResourceIdentity")
CPLResourceIdentityImplementation = _Class("CPLResourceIdentityImplementation")
CPLShareParticipant = _Class("CPLShareParticipant")
CPLBatchExtractionStrategy = _Class("CPLBatchExtractionStrategy")
CPLChangeSessionUpdate = _Class("CPLChangeSessionUpdate")
CPLPullSessionScopesAcknowledgement = _Class("CPLPullSessionScopesAcknowledgement")
CPLPullSessionUpdate = _Class("CPLPullSessionUpdate")
CPLPushSessionUpdate = _Class("CPLPushSessionUpdate")
CPLPersonReference = _Class("CPLPersonReference")
CPLRecordChange = _Class("CPLRecordChange")
CPLFaceCropChange = _Class("CPLFaceCropChange")
CPLPersonChange = _Class("CPLPersonChange")
CPLContainerRelationChange = _Class("CPLContainerRelationChange")
CPLContainerChange = _Class("CPLContainerChange")
CPLAlbumChange = _Class("CPLAlbumChange")
CPLMemoryChange = _Class("CPLMemoryChange")
CPLScopeChange = _Class("CPLScopeChange")
CPLMomentShareScopeChange = _Class("CPLMomentShareScopeChange")
CPLItemChange = _Class("CPLItemChange")
CPLAssetChange = _Class("CPLAssetChange")
CPLMasterChange = _Class("CPLMasterChange")
CPLSuggestionChange = _Class("CPLSuggestionChange")
CPLFileStorageItem = _Class("CPLFileStorageItem")
CPLEngineFileStorage = _Class("CPLEngineFileStorage")
CPLNetworkState = _Class("CPLNetworkState")
CPLNetworkWatcher = _Class("CPLNetworkWatcher")
CPLSyncSession = _Class("CPLSyncSession")
CPLPowerAssertion = _Class("CPLPowerAssertion")
_CPLTimingStatistic = _Class("_CPLTimingStatistic")
CPLEngineWriteTransactionBlocker = _Class("CPLEngineWriteTransactionBlocker")
_CPLEngineStoreBatchedTransaction = _Class("_CPLEngineStoreBatchedTransaction")
CPLEngineStoreTransaction = _Class("CPLEngineStoreTransaction")
CPLEngineStore = _Class("CPLEngineStore")
CPLEngineSyncTask = _Class("CPLEngineSyncTask")
CPLBackgroundDownloadsTask = _Class("CPLBackgroundDownloadsTask")
CPLCleanupTask = _Class("CPLCleanupTask")
CPLMinglePulledChangesTask = _Class("CPLMinglePulledChangesTask")
CPLPullScopesTask = _Class("CPLPullScopesTask")
CPLEngineScopedTask = _Class("CPLEngineScopedTask")
CPLPullFromTransportScopeTask = _Class("CPLPullFromTransportScopeTask")
CPLScopeUpdateScopeTask = _Class("CPLScopeUpdateScopeTask")
CPLPushToTransportScopeTask = _Class("CPLPushToTransportScopeTask")
CPLTransportUpdateScopeTask = _Class("CPLTransportUpdateScopeTask")
CPLEngineMultiscopeSyncTask = _Class("CPLEngineMultiscopeSyncTask")
CPLPullFromTransportTask = _Class("CPLPullFromTransportTask")
CPLScopeUpdateTask = _Class("CPLScopeUpdateTask")
CPLPushToTransportTask = _Class("CPLPushToTransportTask")
CPLTransportUpdateTask = _Class("CPLTransportUpdateTask")
_CPLPruneRequestCounter = _Class("_CPLPruneRequestCounter")
CPLEngineStorage = _Class("CPLEngineStorage")
CPLEngineInitialQueryTracker = _Class("CPLEngineInitialQueryTracker")
CPLEngineOutgoingResources = _Class("CPLEngineOutgoingResources")
CPLEngineQuarantinedRecords = _Class("CPLEngineQuarantinedRecords")
CPLEngineStatusCenter = _Class("CPLEngineStatusCenter")
CPLEngineCloudCache = _Class("CPLEngineCloudCache")
CPLEngineRemappedDeletes = _Class("CPLEngineRemappedDeletes")
CPLEngineTransientRepository = _Class("CPLEngineTransientRepository")
CPLEngineChangePipe = _Class("CPLEngineChangePipe")
CPLEngineScopeCleanupTasks = _Class("CPLEngineScopeCleanupTasks")
CPLEngineScopeStorage = _Class("CPLEngineScopeStorage")
CPLEngineResourceDownloadQueue = _Class("CPLEngineResourceDownloadQueue")
CPLEngineIDMapping = _Class("CPLEngineIDMapping")
CPLEnginePushRepository = _Class("CPLEnginePushRepository")
CPLEngineResourceStorage = _Class("CPLEngineResourceStorage")
CPLRecordView = _Class("CPLRecordView")
CPLClientCacheRecordView = _Class("CPLClientCacheRecordView")
CPLChangedRecordView = _Class("CPLChangedRecordView")
CPLSimpleRecordView = _Class("CPLSimpleRecordView")
CPLSerializedFeedbackMessage = _Class("CPLSerializedFeedbackMessage")
CPLFeedbackMessage = _Class("CPLFeedbackMessage")
CPLInfoFeedbackMessage = _Class("CPLInfoFeedbackMessage")
CPLResetFeedbackMessage = _Class("CPLResetFeedbackMessage")
CPLQuarantineFeedbackMessage = _Class("CPLQuarantineFeedbackMessage")
CPLSettingFeedbackMessage = _Class("CPLSettingFeedbackMessage")
CPLExpungeableResourceState = _Class("CPLExpungeableResourceState")
CPLAdjustments = _Class("CPLAdjustments")
CPLResourceTransferTask = _Class("CPLResourceTransferTask")
CPLEngineResourceUploadTask = _Class("CPLEngineResourceUploadTask")
CPLInMemoryResourceDownloadTask = _Class("CPLInMemoryResourceDownloadTask")
CPLEngineResourceDownloadTask = _Class("CPLEngineResourceDownloadTask")
CPLProxyResourceTransferTask = _Class("CPLProxyResourceTransferTask")
CPLForceSyncTask = _Class("CPLForceSyncTask")
CPLEngineForceSyncTask = _Class("CPLEngineForceSyncTask")
CPLEngineBackupSyncTask = _Class("CPLEngineBackupSyncTask")
CPLProxyForceSyncTask = _Class("CPLProxyForceSyncTask")
CPLProxyLibraryManagerSyncOutstandingInvocation = _Class(
    "CPLProxyLibraryManagerSyncOutstandingInvocation"
)
CPLProxyLibraryManagerOutstandingInvocation = _Class(
    "CPLProxyLibraryManagerOutstandingInvocation"
)
CPLPlatformObject = _Class("CPLPlatformObject")
CPLProxySession = _Class("CPLProxySession")
CPLProxyPushSession = _Class("CPLProxyPushSession")
CPLProxyPullSession = _Class("CPLProxyPullSession")
CPLProxyLibraryManager = _Class("CPLProxyLibraryManager")
CPLSuggestionAssetList = _Class("CPLSuggestionAssetList")
CPLServerFeedbackMessage = _Class("CPLServerFeedbackMessage")
CPLMemoryAssetList = _Class("CPLMemoryAssetList")
CPLRampingResponse = _Class("CPLRampingResponse")
CPLServerFeedbackResponse = _Class("CPLServerFeedbackResponse")
CPLMemoryAssetFlag = _Class("CPLMemoryAssetFlag")
CPLSuggestionAsset = _Class("CPLSuggestionAsset")
CPLSuggestionAssetFlag = _Class("CPLSuggestionAssetFlag")
CPLFaceInstance = _Class("CPLFaceInstance")
CPLRampingRequestResource = _Class("CPLRampingRequestResource")
CPLAccountFlags = _Class("CPLAccountFlags")
CPLServerFeedbackKeyAndValue = _Class("CPLServerFeedbackKeyAndValue")
CPLMemoryAsset = _Class("CPLMemoryAsset")
CPLMomentSharePreviewData = _Class("CPLMomentSharePreviewData")
CPLFaceAnalysis = _Class("CPLFaceAnalysis")
CPLFaceAnalysisReference = _Class("CPLFaceAnalysisReference")
CPLRampingResponseResource = _Class("CPLRampingResponseResource")
CPLServerFeedbackRequest = _Class("CPLServerFeedbackRequest")
CPLRampingRequest = _Class("CPLRampingRequest")
CPLArchiver = _Class("CPLArchiver")
CPLAssetKeywordSortDescriptor = _Class("CPLAssetKeywordSortDescriptor")
