"""
Classes from the 'CoreSuggestions' framework.
"""

try:
    from rubicon.objc import ObjCClass
except ValueError:

    def ObjCClass(name):
        return None


def _Class(name):
    try:
        return ObjCClass(name)
    except NameError:
        return None


SGDaemonConnection = _Class("SGDaemonConnection")
SGSuggestionsICSMetrics = _Class("SGSuggestionsICSMetrics")
SGErrorMetrics = _Class("SGErrorMetrics")
SGPatternMetrics = _Class("SGPatternMetrics")
SGSuggestedActionMetrics = _Class("SGSuggestedActionMetrics")
SGNLEventSuggestionsMetrics = _Class("SGNLEventSuggestionsMetrics")
SGContact = _Class("SGContact")
SGMailMessageKey = _Class("SGMailMessageKey")
SGMessagesDaemonConnection = _Class("SGMessagesDaemonConnection")
SGXPCResponse = _Class("SGXPCResponse")
SGXPCResponse1 = _Class("SGXPCResponse1")
SGXPCResponse2 = _Class("SGXPCResponse2")
SGXPCResponse3 = _Class("SGXPCResponse3")
SGRecordId = _Class("SGRecordId")
SGPreferenceStorage = _Class("SGPreferenceStorage")
SGPreferenceManager = _Class("SGPreferenceManager")
SGContactMatch = _Class("SGContactMatch")
SGExtractionInfo = _Class("SGExtractionInfo")
SGRealtimeContact = _Class("SGRealtimeContact")
SGMatchinfoData = _Class("SGMatchinfoData")
SGCircularBufferArray = _Class("SGCircularBufferArray")
SGFn = _Class("SGFn")
SGSimpleTimeRange = _Class("SGSimpleTimeRange")
SGTimeZoneDetector = _Class("SGTimeZoneDetector")
SGTimeZone = _Class("SGTimeZone")
SGRealtimeSuggestionMock = _Class("SGRealtimeSuggestionMock")
SGDSuggestManagerInterface = _Class("SGDSuggestManagerInterface")
SGSearchableItemHelper = _Class("SGSearchableItemHelper")
SGIPMessage = _Class("SGIPMessage")
SGIPPerson = _Class("SGIPPerson")
SGOrigin = _Class("SGOrigin")
SGNotificationListener = _Class("SGNotificationListener")
SGEventMetadata = _Class("SGEventMetadata")
SGMatchedDetails = _Class("SGMatchedDetails")
SGRealtimeReminder = _Class("SGRealtimeReminder")
SGSimpleNamedEmailAddress = _Class("SGSimpleNamedEmailAddress")
SGMFoundInAppsICS = _Class("SGMFoundInAppsICS")
SGMMailClientInMailApp = _Class("SGMMailClientInMailApp")
SGMCNtoSGContactsCacheHit = _Class("SGMCNtoSGContactsCacheHit")
SGMSerializedContactsCacheHit = _Class("SGMSerializedContactsCacheHit")
SGMContactsInterfaceCacheCount = _Class("SGMContactsInterfaceCacheCount")
SGMContactsInterfaceCacheHit = _Class("SGMContactsInterfaceCacheHit")
SGMBundleIdsTrackedAsOther = _Class("SGMBundleIdsTrackedAsOther")
SGMBundleIdsUsingOldEntitlement = _Class("SGMBundleIdsUsingOldEntitlement")
SGMBundleIdsMissingEntitlement = _Class("SGMBundleIdsMissingEntitlement")
SGMSelfIdModelScore = _Class("SGMSelfIdModelScore")
SGMFoundInMailModelScore = _Class("SGMFoundInMailModelScore")
SGMSearchResultsIncludedPureSuggestion = _Class(
    "SGMSearchResultsIncludedPureSuggestion"
)
SGMContactCreated = _Class("SGMContactCreated")
SGMSuggestedContactDetailShown = _Class("SGMSuggestedContactDetailShown")
SGMSuggestedContactDetailUsed = _Class("SGMSuggestedContactDetailUsed")
SGMSearchResultsUserSelectedContact = _Class("SGMSearchResultsUserSelectedContact")
SGMAutocompleteUserSelectedContact = _Class("SGMAutocompleteUserSelectedContact")
SGMContactDetailSent = _Class("SGMContactDetailSent")
SGMContactDetailExtraction = _Class("SGMContactDetailExtraction")
SGMBadInteractionIgnored = _Class("SGMBadInteractionIgnored")
SGMSelfIdPatternMatched = _Class("SGMSelfIdPatternMatched")
SGMDDLinkShown = _Class("SGMDDLinkShown")
SGMNLEventInBanner = _Class("SGMNLEventInBanner")
SGMOtherResultSelectedInSpotlight = _Class("SGMOtherResultSelectedInSpotlight")
SGMNoResultSelectedInSpotlight = _Class("SGMNoResultSelectedInSpotlight")
SGMEventResultSelectedInSpotlight = _Class("SGMEventResultSelectedInSpotlight")
SGMEventResultInSpotlight = _Class("SGMEventResultInSpotlight")
SGMContactResultSelectedInSpotlight = _Class("SGMContactResultSelectedInSpotlight")
SGMContactResultInSpotlight = _Class("SGMContactResultInSpotlight")
SGMEventICSOpportunity = _Class("SGMEventICSOpportunity")
SGMEventBannerRejected = _Class("SGMEventBannerRejected")
SGMEventBannerConfirmed = _Class("SGMEventBannerConfirmed")
SGMEventInBanner = _Class("SGMEventInBanner")
SGMEventOpportunityInSpotlight = _Class("SGMEventOpportunityInSpotlight")
SGMContactOpportunityInSpotlight = _Class("SGMContactOpportunityInSpotlight")
SGMUnknownContactInformationShown = _Class("SGMUnknownContactInformationShown")
SGMMaybeInformationShown = _Class("SGMMaybeInformationShown")
SGMContactDetailConversationTurn = _Class("SGMContactDetailConversationTurn")
SGMContactDetailRejected = _Class("SGMContactDetailRejected")
SGMContactDetailUsed = _Class("SGMContactDetailUsed")
SGMContactDetailConfirmed = _Class("SGMContactDetailConfirmed")
SGMContactRejected = _Class("SGMContactRejected")
SGMContactConfirmed = _Class("SGMContactConfirmed")
SGMContactInBanner = _Class("SGMContactInBanner")
SGMSuggestdExitReason = _Class("SGMSuggestdExitReason")
SGMSqliteErrors = _Class("SGMSqliteErrors")
SGRealtimeEvent = _Class("SGRealtimeEvent")
SGSuggestionsService = _Class("SGSuggestionsService")
SGMessagesSuggestionsService = _Class("SGMessagesSuggestionsService")
SGDetailCacheSnapshot = _Class("SGDetailCacheSnapshot")
SGRemoteObjectProxy = _Class("SGRemoteObjectProxy")
SGKeyValueCacheFile = _Class("SGKeyValueCacheFile")
SGPostalAddressComponents = _Class("SGPostalAddressComponents")
SGEventGeocode = _Class("SGEventGeocode")
SGDirectory = _Class("SGDirectory")
SGReminderMetadata = _Class("SGReminderMetadata")
SGFuture = _Class("SGFuture")
SGObject = _Class("SGObject")
SGEvent = _Class("SGEvent")
SGDelivery = _Class("SGDelivery")
SGName = _Class("SGName")
SGLocation = _Class("SGLocation")
SGLabeledObject = _Class("SGLabeledObject")
SGEmailAddress = _Class("SGEmailAddress")
SGDateComponents = _Class("SGDateComponents")
SGPhoneNumber = _Class("SGPhoneNumber")
SGPostalAddress = _Class("SGPostalAddress")
SGReminder = _Class("SGReminder")
SGEKEventConversions = _Class("SGEKEventConversions")
SGEventActivity = _Class("SGEventActivity")
SGObjCRuntime = _Class("SGObjCRuntime")
SGEntityTag = _Class("SGEntityTag")
SGEntityTagLabelOptions = _Class("SGEntityTagLabelOptions")
SGSuggestedEventLaunchInfo = _Class("SGSuggestedEventLaunchInfo")
SGSuggestions = _Class("SGSuggestions")
SGURL = _Class("SGURL")
SGDomainWhitelistChecker = _Class("SGDomainWhitelistChecker")
SGDomainWhitelistCheckerGuardedData = _Class("SGDomainWhitelistCheckerGuardedData")
SGSearchableItemSerializedAttributes = _Class("SGSearchableItemSerializedAttributes")
SGHarvestEligibility = _Class("SGHarvestEligibility")
SGEligibilityCheckResult = _Class("SGEligibilityCheckResult")
SGM2BundleIdsUsingOldEntitlement = _Class("SGM2BundleIdsUsingOldEntitlement")
SGM2SelfIdPatternMatched = _Class("SGM2SelfIdPatternMatched")
SGM2NLEventInBanner = _Class("SGM2NLEventInBanner")
SGM2MaybeInformationShown = _Class("SGM2MaybeInformationShown")
SGM2FoundInAppsICS = _Class("SGM2FoundInAppsICS")
SGM2EventInBanner = _Class("SGM2EventInBanner")
SGM2EventICSOpportunity = _Class("SGM2EventICSOpportunity")
SGM2EventBannerRejected = _Class("SGM2EventBannerRejected")
SGM2EventBannerConfirmed = _Class("SGM2EventBannerConfirmed")
SGM2DDLinkShown = _Class("SGM2DDLinkShown")
SGM2ContactRejected = _Class("SGM2ContactRejected")
SGM2ContactInBanner = _Class("SGM2ContactInBanner")
SGM2ContactDetailUsed = _Class("SGM2ContactDetailUsed")
SGM2ContactDetailRejected = _Class("SGM2ContactDetailRejected")
SGM2ContactDetailConfirmed = _Class("SGM2ContactDetailConfirmed")
SGM2ContactConfirmed = _Class("SGM2ContactConfirmed")
SGM2CNtoSGContactsCacheHit = _Class("SGM2CNtoSGContactsCacheHit")
SGM2BundleIdsMissingEntitlement = _Class("SGM2BundleIdsMissingEntitlement")
SGM2BadInteractionIgnored = _Class("SGM2BadInteractionIgnored")
_SGNSStringEncodingEnumerator = _Class("_SGNSStringEncodingEnumerator")
