"""
Classes from the 'CoreDuet' framework.
"""

try:
    from rubicon.objc import ObjCClass
except ValueError:

    def ObjCClass(name):
        return None


def _Class(name):
    try:
        return ObjCClass(name)
    except NameError:
        return None


_DKSyncCoordinatorLogging = _Class("_DKSyncCoordinatorLogging")
_DKSyncContextObjectFactory = _Class("_DKSyncContextObjectFactory")
_DKSyncContext = _Class("_DKSyncContext")
_DKSyncPeerObserver = _Class("_DKSyncPeerObserver")
_DKSyncPeerInfo = _Class("_DKSyncPeerInfo")
_CDDeviceInfo = _Class("_CDDeviceInfo")
_DKPlatform = _Class("_DKPlatform")
_CDSizeMetricFamily = _Class("_CDSizeMetricFamily")
_CDSizeMetric = _Class("_CDSizeMetric")
_CDMutableSizeMetric = _Class("_CDMutableSizeMetric")
_CDHomeControlsDataCollectionTask = _Class("_CDHomeControlsDataCollectionTask")
_CDHomeControlsDataCollectionSession = _Class("_CDHomeControlsDataCollectionSession")
_CDDataCollection = _Class("_CDDataCollection")
_CDDataCollectionSession = _Class("_CDDataCollectionSession")
_CDEventStreamsRegister = _Class("_CDEventStreamsRegister")
_DKProtobufMetadata = _Class("_DKProtobufMetadata")
_CDDatePrinter = _Class("_CDDatePrinter")
_CDStatsPrinter = _Class("_CDStatsPrinter")
_DKObjectType = _Class("_DKObjectType")
_DKIdentifierType = _Class("_DKIdentifierType")
_DKQuantityType = _Class("_DKQuantityType")
_DKCategoryType = _Class("_DKCategoryType")
_DKSyncRapportCommonStorage = _Class("_DKSyncRapportCommonStorage")
_DKSyncRapportStorage = _Class("_DKSyncRapportStorage")
_DKSyncRapportContextStorage = _Class("_DKSyncRapportContextStorage")
_DKSyncRapportKnowledgeStorage = _Class("_DKSyncRapportKnowledgeStorage")
_CDSpotlightItemRecorder = _Class("_CDSpotlightItemRecorder")
_CDSpotlightItemRecorderOperation = _Class("_CDSpotlightItemRecorderOperation")
_DKDataProtectionStateMonitor = _Class("_DKDataProtectionStateMonitor")
_DKDataProtectionMonitor = _Class("_DKDataProtectionMonitor")
_DKXPCKnowledgeStore = _Class("_DKXPCKnowledgeStore")
_CDDateRange = _Class("_CDDateRange")
_DKKnowledgeStorageLogging = _Class("_DKKnowledgeStorageLogging")
_CDPInteractionStoreDataHarvester = _Class("_CDPInteractionStoreDataHarvester")
_CDSpotlightQuerier = _Class("_CDSpotlightQuerier")
_CDMDSearchQueryDelegate = _Class("_CDMDSearchQueryDelegate")
_CDSleepPredictorMath = _Class("_CDSleepPredictorMath")
_CDErrorUtilities = _Class("_CDErrorUtilities")
CDBudget = _Class("CDBudget")
_CDNetworkBudgetCalculator = _Class("_CDNetworkBudgetCalculator")
CDAttribute = _Class("CDAttribute")
CDAttributeOccurrence = _Class("CDAttributeOccurrence")
_DKSyncUrgencyTracker = _Class("_DKSyncUrgencyTracker")
_CDSocialInteractionAdvisor = _Class("_CDSocialInteractionAdvisor")
_CDInteractionRecorder = _Class("_CDInteractionRecorder")
_DKStandingQueryExecutor = _Class("_DKStandingQueryExecutor")
_DKDeviceActivityStandingQuery = _Class("_DKDeviceActivityStandingQuery")
_CDSpotlightEventIndexer = _Class("_CDSpotlightEventIndexer")
_CDEventIndexerContext = _Class("_CDEventIndexerContext")
_CDEventIndexerBookmark = _Class("_CDEventIndexerBookmark")
_CDPSerializedDataHarvester = _Class("_CDPSerializedDataHarvester")
_DKSyncSerializer = _Class("_DKSyncSerializer")
_DKPredictor = _Class("_DKPredictor")
_CDInteractionFeedbackLogger = _Class("_CDInteractionFeedbackLogger")
CDSession = _Class("CDSession")
CDGlanceLingerEvent = _Class("CDGlanceLingerEvent")
_DKKnowledgeStorageSimpleKeyValueStore = _Class(
    "_DKKnowledgeStorageSimpleKeyValueStore"
)
_CDCommunicatorHelper = _Class("_CDCommunicatorHelper")
_DKObjectMOConverter = _Class("_DKObjectMOConverter")
_DKObjectFromMOCache = _Class("_DKObjectFromMOCache")
_DKSyncPeer = _Class("_DKSyncPeer")
CDMonitorManager = _Class("CDMonitorManager")
_CDInteractionStoreNotificationReceiver = _Class(
    "_CDInteractionStoreNotificationReceiver"
)
_CDInteractionStoreNotifier = _Class("_CDInteractionStoreNotifier")
_DKEventData = _Class("_DKEventData")
_CDInteractionPolicies = _Class("_CDInteractionPolicies")
_DKDiskSubsystemIdentifier = _Class("_DKDiskSubsystemIdentifier")
_DKNotificationEventIdentifier = _Class("_DKNotificationEventIdentifier")
_DKUUIDIdentifier = _Class("_DKUUIDIdentifier")
_DKTopicIdentifier = _Class("_DKTopicIdentifier")
_DKHomeKitHomeAppViewIdentifier = _Class("_DKHomeKitHomeAppViewIdentifier")
_DKHomeKitAccessoryControlIdentifier = _Class("_DKHomeKitAccessoryControlIdentifier")
_DKHomeKitSceneIdentifier = _Class("_DKHomeKitSceneIdentifier")
_DKResourceIdentifier = _Class("_DKResourceIdentifier")
_DKLocationIdentifier = _Class("_DKLocationIdentifier")
_DKBundleIdentifier = _Class("_DKBundleIdentifier")
_DKTitleIdentifier = _Class("_DKTitleIdentifier")
_DKAnyStringIdentifier = _Class("_DKAnyStringIdentifier")
_DKCustomIdentifier = _Class("_DKCustomIdentifier")
_CDLogging = _Class("_CDLogging")
_DKCoreDataStorage = _Class("_DKCoreDataStorage")
_DKIntentMetadataKey = _Class("_DKIntentMetadataKey")
_DKRoutineLocationOfInterestTypeCategory = _Class(
    "_DKRoutineLocationOfInterestTypeCategory"
)
_DKSourceMOConverter = _Class("_DKSourceMOConverter")
_CDDataCollectionUtilities = _Class("_CDDataCollectionUtilities")
_DKRoutineEventStreams = _Class("_DKRoutineEventStreams")
_DKEventStatsUtilities = _Class("_DKEventStatsUtilities")
_DKEventTypeStatsTimerCounter = _Class("_DKEventTypeStatsTimerCounter")
_DKEventStatsTimerCounter = _Class("_DKEventStatsTimerCounter")
_DKEventTypeResultStatsCounter = _Class("_DKEventTypeResultStatsCounter")
_DKEventTypeStatsCounter = _Class("_DKEventTypeStatsCounter")
_DKEventResultStatsCounter = _Class("_DKEventResultStatsCounter")
_DKEventStatsCounter = _Class("_DKEventStatsCounter")
_DKEventStatsCollection = _Class("_DKEventStatsCollection")
_DKEventStatsCounterInternal = _Class("_DKEventStatsCounterInternal")
_DKSyncedFeatures = _Class("_DKSyncedFeatures")
_DKActivityThrottler = _Class("_DKActivityThrottler")
_DKThrottledActivity = _Class("_DKThrottledActivity")
_CDInteractionAdvisorSettings = _Class("_CDInteractionAdvisorSettings")
_CDPSimpleDataPoint = _Class("_CDPSimpleDataPoint")
_CDEntitlementsUtilities = _Class("_CDEntitlementsUtilities")
_DKSyncMetadataStorage = _Class("_DKSyncMetadataStorage")
_CDBatterySaver = _Class("_CDBatterySaver")
_DKSyncErrors = _Class("_DKSyncErrors")
_CDCloudFamilyDataCollectionTask = _Class("_CDCloudFamilyDataCollectionTask")
_CDCloudFamilyDataCollectionSession = _Class("_CDCloudFamilyDataCollectionSession")
_DKQueryDispatcher = _Class("_DKQueryDispatcher")
_DKAggregateEventQueryResult = _Class("_DKAggregateEventQueryResult")
_DKContentProviderQueries = _Class("_DKContentProviderQueries")
_DKEventCKConverter = _Class("_DKEventCKConverter")
_DKSyncPowerlog = _Class("_DKSyncPowerlog")
_CDEventStream = _Class("_CDEventStream")
_DKKnowledgeSyncStorageAssertion = _Class("_DKKnowledgeSyncStorageAssertion")
_DKSyncChanges = _Class("_DKSyncChanges")
_DKLocalChanges = _Class("_DKLocalChanges")
_DKKnowledgeStorage = _Class("_DKKnowledgeStorage")
_CDCloudFamilyPETDataCollectionUtilities = _Class(
    "_CDCloudFamilyPETDataCollectionUtilities"
)
_DKAppMediaUsageMetadataKey = _Class("_DKAppMediaUsageMetadataKey")
_DKDigitalHealthMetadataKey = _Class("_DKDigitalHealthMetadataKey")
_CDPortraitStreams = _Class("_CDPortraitStreams")
_CDIntentSpotlightIndex = _Class("_CDIntentSpotlightIndex")
_DKHistogram = _Class("_DKHistogram")
_CDPeopleSuggesterSettings = _Class("_CDPeopleSuggesterSettings")
_CDPeopleSuggesterContext = _Class("_CDPeopleSuggesterContext")
_CDSuggestedPerson = _Class("_CDSuggestedPerson")
_CDCachedPeopleSuggestion = _Class("_CDCachedPeopleSuggestion")
_CDPeopleSuggester = _Class("_CDPeopleSuggester")
_CDPortraitMetadataKey = _Class("_CDPortraitMetadataKey")
_CDEntityMetadataKey = _Class("_CDEntityMetadataKey")
_CDTopicMetadataKey = _Class("_CDTopicMetadataKey")
_CDEventHandlerForDefaultPairedNearby = _Class("_CDEventHandlerForDefaultPairedNearby")
_CDEventHandlerForWatchNearby = _Class("_CDEventHandlerForWatchNearby")
_CDEventHandlerForAppInFocus = _Class("_CDEventHandlerForAppInFocus")
_CDEventHandlerForActivityLevel = _Class("_CDEventHandlerForActivityLevel")
_CDFileUtility = _Class("_CDFileUtility")
_CDDataCollectionAnonymizer = _Class("_CDDataCollectionAnonymizer")
_CDAppActionRecorder = _Class("_CDAppActionRecorder")
_CDUserActivity = _Class("_CDUserActivity")
_DKSyncLocalKnowledgeStorage = _Class("_DKSyncLocalKnowledgeStorage")
_CDTemporalInteractionAdvisor = _Class("_CDTemporalInteractionAdvisor")
_CDInteractionAdvisorUtils = _Class("_CDInteractionAdvisorUtils")
_CDGenericInteractionRanker = _Class("_CDGenericInteractionRanker")
_CDInteractionRank = _Class("_CDInteractionRank")
_CDInteractionAdviceEngine = _Class("_CDInteractionAdviceEngine")
_DKRoutineMetadataKeys = _Class("_DKRoutineMetadataKeys")
_CDMultiLevelRateLimiter = _Class("_CDMultiLevelRateLimiter")
_DKKnowledgeContentProvider = _Class("_DKKnowledgeContentProvider")
_DKKeyValueStore = _Class("_DKKeyValueStore")
_CDInteractionAdvisorSimple = _Class("_CDInteractionAdvisorSimple")
_DKRateLimitPolicyEnforcer = _Class("_DKRateLimitPolicyEnforcer")
_CDSiriLearningSettings = _Class("_CDSiriLearningSettings")
_DKEntityCategory = _Class("_DKEntityCategory")
_DKAlarmStateCategory = _Class("_DKAlarmStateCategory")
_DKAirPlayPredictionCategory = _Class("_DKAirPlayPredictionCategory")
_DKAudioRouteCategory = _Class("_DKAudioRouteCategory")
_DKRoutineLocationCategory = _Class("_DKRoutineLocationCategory")
_DKMotionCategory = _Class("_DKMotionCategory")
_DKUIOrientationCategory = _Class("_DKUIOrientationCategory")
_DKTristateCategory = _Class("_DKTristateCategory")
_DKBoolCategory = _Class("_DKBoolCategory")
_DKAnyIntegerCategory = _Class("_DKAnyIntegerCategory")
_DKCustomCategory = _Class("_DKCustomCategory")
_DKPredictionQueryFeedback = _Class("_DKPredictionQueryFeedback")
_CDInteractionDataCollectionTask = _Class("_CDInteractionDataCollectionTask")
_CDInteractionDataCollectionSession = _Class("_CDInteractionDataCollectionSession")
_DKSync3Policy = _Class("_DKSync3Policy")
_DKSync3FeaturePolicy = _Class("_DKSync3FeaturePolicy")
_DKSync3TransportPolicy = _Class("_DKSync3TransportPolicy")
_CDInteractionStore = _Class("_CDInteractionStore")
_DKSyncWindow = _Class("_DKSyncWindow")
_CDAttachment = _Class("_CDAttachment")
_CDComplications = _Class("_CDComplications")
_CDPaths = _Class("_CDPaths")
_DKBatteryPercentageQuantity = _Class("_DKBatteryPercentageQuantity")
_DKAnyDoubleQuantity = _Class("_DKAnyDoubleQuantity")
_DKCustomQuantity = _Class("_DKCustomQuantity")
_CDContactStatistics = _Class("_CDContactStatistics")
_CDContact = _Class("_CDContact")
CDTrendLogic = _Class("CDTrendLogic")
_DKPrivacyPolicyEnforcer = _Class("_DKPrivacyPolicyEnforcer")
_CDSpotlightItemUtils = _Class("_CDSpotlightItemUtils")
_CDInBedDetector = _Class("_CDInBedDetector")
_CDInBedDetection = _Class("_CDInBedDetection")
_CDPModelTuning = _Class("_CDPModelTuning")
_CDPModelTuningState = _Class("_CDPModelTuningState")
_DKPreferences = _Class("_DKPreferences")
_CDDiagnosticDataReporter = _Class("_CDDiagnosticDataReporter")
_DKCKError = _Class("_DKCKError")
_CDPSimpleModel = _Class("_CDPSimpleModel")
_DKEventIntersection = _Class("_DKEventIntersection")
_CDInteractionPolicy = _Class("_CDInteractionPolicy")
_CDServerRequest = _Class("_CDServerRequest")
_CDPeriodicScheduler = _Class("_CDPeriodicScheduler")
_CDPeriodicSchedulerJob = _Class("_CDPeriodicSchedulerJob")
_DKContentProviderCache = _Class("_DKContentProviderCache")
_DKMetadataHomeAppView = _Class("_DKMetadataHomeAppView")
_DKMetadataHomeKitAccessoryControl = _Class("_DKMetadataHomeKitAccessoryControl")
_DKMetadataHomeKitScene = _Class("_DKMetadataHomeKitScene")
_CDSpotlightEventIndexerDataSource = _Class("_CDSpotlightEventIndexerDataSource")
_CDSpotlightIntentIndexerDataSource = _Class("_CDSpotlightIntentIndexerDataSource")
_DKFamilyPredictionMetadataKey = _Class("_DKFamilyPredictionMetadataKey")
_DKBehavioralRuleFeaturesMetadataKey = _Class("_DKBehavioralRuleFeaturesMetadataKey")
_DKDeviceStandbyTimerMetadataKey = _Class("_DKDeviceStandbyTimerMetadataKey")
_DKDeviceActivityLevelFeedbackMetadataKey = _Class(
    "_DKDeviceActivityLevelFeedbackMetadataKey"
)
_DKDeviceIsPluggedInMetadataKey = _Class("_DKDeviceIsPluggedInMetadataKey")
_DKDeviceBatteryPercentageMetadataKey = _Class("_DKDeviceBatteryPercentageMetadataKey")
_DKTombstoneMetadataKey = _Class("_DKTombstoneMetadataKey")
_DKNotificationUsageMetadataKey = _Class("_DKNotificationUsageMetadataKey")
_DKRelevantShortcutMetadataKey = _Class("_DKRelevantShortcutMetadataKey")
_DKSafariHistoryMetadataKey = _Class("_DKSafariHistoryMetadataKey")
_DKPeopleSuggesterOutputForSiriNLMetadataKey = _Class(
    "_DKPeopleSuggesterOutputForSiriNLMetadataKey"
)
_DKMapsShareEtaFeedbackMetadataKey = _Class("_DKMapsShareEtaFeedbackMetadataKey")
_DKShareSheetSuggestLessFeedbackMetadataKey = _Class(
    "_DKShareSheetSuggestLessFeedbackMetadataKey"
)
_DKShareSheetFeedbackMetadataKey = _Class("_DKShareSheetFeedbackMetadataKey")
_DKSearchFeedbackMetadataKey = _Class("_DKSearchFeedbackMetadataKey")
_DKDiscoverabilityUsageMetadataKey = _Class("_DKDiscoverabilityUsageMetadataKey")
_DKDiscoverabilitySignalsMetadataKey = _Class("_DKDiscoverabilitySignalsMetadataKey")
_DKSiriIntentEventMetadataKey = _Class("_DKSiriIntentEventMetadataKey")
_DKSiriServiceMetadataKey = _Class("_DKSiriServiceMetadataKey")
_DKDeviceIdMetadataKey = _Class("_DKDeviceIdMetadataKey")
_DKDebugMetadataKey = _Class("_DKDebugMetadataKey")
_DKPeriodMetadataKey = _Class("_DKPeriodMetadataKey")
_DKCallMetadataKey = _Class("_DKCallMetadataKey")
_DKBluetoothMetadataKey = _Class("_DKBluetoothMetadataKey")
_DKOrientationMetadataKey = _Class("_DKOrientationMetadataKey")
_DKBatterySaverMetadataKey = _Class("_DKBatterySaverMetadataKey")
_DKBacklightMetadataKey = _Class("_DKBacklightMetadataKey")
_DKBulletinBoardMetadataKey = _Class("_DKBulletinBoardMetadataKey")
_DKStarkMetadataKey = _Class("_DKStarkMetadataKey")
_DKMicroLocationMetadataKey = _Class("_DKMicroLocationMetadataKey")
_DKLocationMetadataKey = _Class("_DKLocationMetadataKey")
_DKMotionMetadataKey = _Class("_DKMotionMetadataKey")
_DKCalendarMetadataKey = _Class("_DKCalendarMetadataKey")
_DKTimerMetadataKey = _Class("_DKTimerMetadataKey")
_DKAlarmMetadataKey = _Class("_DKAlarmMetadataKey")
_DKAirPlayPredictionMetadataKey = _Class("_DKAirPlayPredictionMetadataKey")
_DKNowPlayingMetadataKey = _Class("_DKNowPlayingMetadataKey")
_DKAudioMetadataKey = _Class("_DKAudioMetadataKey")
_DKAppInstallMetadataKey = _Class("_DKAppInstallMetadataKey")
_DKLocationApplicationActivityMetadataKey = _Class(
    "_DKLocationApplicationActivityMetadataKey"
)
_DKApplicationActivityMetadataKey = _Class("_DKApplicationActivityMetadataKey")
_DKAppClipUsageMetadataKey = _Class("_DKAppClipUsageMetadataKey")
_DKApplicationMetadataKey = _Class("_DKApplicationMetadataKey")
_DKSource = _Class("_DKSource")
_DKObserverEntry = _Class("_DKObserverEntry")
_CDObservationCenter = _Class("_CDObservationCenter")
CDDevice = _Class("CDDevice")
_CDQueryInteractionAdvisor = _Class("_CDQueryInteractionAdvisor")
_CDCloudFamilyPETDataCollectionTask = _Class("_CDCloudFamilyPETDataCollectionTask")
_CDCloudFamilyPETDataCollectionSession = _Class(
    "_CDCloudFamilyPETDataCollectionSession"
)
_DKSyncType = _Class("_DKSyncType")
_DKEventStream = _Class("_DKEventStream")
_CDInteractionHarvester = _Class("_CDInteractionHarvester")
_DKPhotosMetadataKeys = _Class("_DKPhotosMetadataKeys")
_DKPhotosEventStreams = _Class("_DKPhotosEventStreams")
_CDRateLimiter = _Class("_CDRateLimiter")
_CDRateAndTotalLimiter = _Class("_CDRateAndTotalLimiter")
_CDStringTokenizer = _Class("_CDStringTokenizer")
_DKSyncHistory = _Class("_DKSyncHistory")
_CDPPredictionResult = _Class("_CDPPredictionResult")
_CDEventStreamProperties = _Class("_CDEventStreamProperties")
_CDInteraction = _Class("_CDInteraction")
_CDStats = _Class("_CDStats")
_CDHashUtilities = _Class("_CDHashUtilities")
_CDPSimpleModelParameterManager = _Class("_CDPSimpleModelParameterManager")
_CDPSimpleModelParameterManagerAccountState = _Class(
    "_CDPSimpleModelParameterManagerAccountState"
)
_CDPSimpleModelParameterManagerTuningValue = _Class(
    "_CDPSimpleModelParameterManagerTuningValue"
)
_DKTombstonePolicy = _Class("_DKTombstonePolicy")
_DKTombstoneRequirement = _Class("_DKTombstoneRequirement")
_DKAppUsageTombstoneRequirement = _Class("_DKAppUsageTombstoneRequirement")
_DKEligibleForPredictionTombstoneRequirement = _Class(
    "_DKEligibleForPredictionTombstoneRequirement"
)
_DKAppActivityStreamTombstoneRequirement = _Class(
    "_DKAppActivityStreamTombstoneRequirement"
)
_DKAppIntentsStreamTombstoneRequirement = _Class(
    "_DKAppIntentsStreamTombstoneRequirement"
)
_DKSyncStreamsTombstoneRequirement = _Class("_DKSyncStreamsTombstoneRequirement")
_CDSleepPredictor = _Class("_CDSleepPredictor")
_DKSystemEventStreams = _Class("_DKSystemEventStreams")
_DKTombstoneNotifier = _Class("_DKTombstoneNotifier")
_CDSerializableKeyedData = _Class("_CDSerializableKeyedData")
_CDSharedMemoryKeyValueStore = _Class("_CDSharedMemoryKeyValueStore")
_DKSyncUpCloudKitKnowledgeStorage = _Class("_DKSyncUpCloudKitKnowledgeStorage")
_DKSyncDownCloudKitKnowledgeStorage = _Class("_DKSyncDownCloudKitKnowledgeStorage")
_DKSyncCloudKitKnowledgeStorage = _Class("_DKSyncCloudKitKnowledgeStorage")
_DKCloudUtilities = _Class("_DKCloudUtilities")
_CDContactResolver = _Class("_CDContactResolver")
_CDPrivacyPolicy = _Class("_CDPrivacyPolicy")
_DKKnowledgeStore = _Class("_DKKnowledgeStore")
_DKCompatibility = _Class("_DKCompatibility")
_DKSyncDeletedEventIDs = _Class("_DKSyncDeletedEventIDs")
_DKChangeSet = _Class("_DKChangeSet")
_DKLocationHistoryCache = _Class("_DKLocationHistoryCache")
_DKCachedLocationVisit = _Class("_DKCachedLocationVisit")
_DKObject = _Class("_DKObject")
_DKEvent = _Class("_DKEvent")
_DKRelation = _Class("_DKRelation")
_DKQuantity = _Class("_DKQuantity")
_DKCategory = _Class("_DKCategory")
_DKIdentifier = _Class("_DKIdentifier")
_DKSyncPolicy = _Class("_DKSyncPolicy")
_DKSyncToggle = _Class("_DKSyncToggle")
_DKEventUtils = _Class("_DKEventUtils")
_DKEventDateRef = _Class("_DKEventDateRef")
_CDAdvisedInteraction = _Class("_CDAdvisedInteraction")
_CDInteractionAdvisor = _Class("_CDInteractionAdvisor")
_CDEventStreams = _Class("_CDEventStreams")
_DKSync2State = _Class("_DKSync2State")
_DKSyncContextObject = _Class("_DKSyncContextObject")
_DKSyncPeerStatusTracker = _Class("_DKSyncPeerStatusTracker")
_DKSync2Coordinator = _Class("_DKSync2Coordinator")
_CDPerfMetricFamily = _Class("_CDPerfMetricFamily")
_CDPerfMetric = _Class("_CDPerfMetric")
_CDMutablePerfMetric = _Class("_CDMutablePerfMetric")
_DKSync2Policy = _Class("_DKSync2Policy")
_DKMetadata = _Class("_DKMetadata")
_CDSleepForAutoSu = _Class("_CDSleepForAutoSu")
_CDAutoSuCache = _Class("_CDAutoSuCache")
_CDAutoSuConfig = _Class("_CDAutoSuConfig")
_CDAirPlayDataCollectionTask = _Class("_CDAirPlayDataCollectionTask")
_CDAirPlayDataCollectionSession = _Class("_CDAirPlayDataCollectionSession")
_CDDateQuantizer = _Class("_CDDateQuantizer")
_DKMetadataPersistenceLookupTable = _Class("_DKMetadataPersistenceLookupTable")
_CDInteractionCache = _Class("_CDInteractionCache")
_DKPrivacyMaintainer = _Class("_DKPrivacyMaintainer")
HomeControlAnalysisPETCoreBehaviorAnalysisEvent = _Class(
    "HomeControlAnalysisPETCoreBehaviorAnalysisEvent"
)
InteractionAnalysisPETInteractionEvents = _Class(
    "InteractionAnalysisPETInteractionEvents"
)
_DKPRMetadataEntry = _Class("_DKPRMetadataEntry")
_DKPRChangeSet = _Class("_DKPRChangeSet")
_DKPRMetadata = _Class("_DKPRMetadata")
_DKPRSource = _Class("_DKPRSource")
_DKPREvent = _Class("_DKPREvent")
CloudFamilyAnalysisPETContactEvent = _Class("CloudFamilyAnalysisPETContactEvent")
_DKPRValueType = _Class("_DKPRValueType")
_DKPREventData = _Class("_DKPREventData")
CloudFamilyAnalysisPETContactEvents = _Class("CloudFamilyAnalysisPETContactEvents")
_DKPRCompressedChangeSet = _Class("_DKPRCompressedChangeSet")
InteractionAnalysisPETInteractionEvent = _Class(
    "InteractionAnalysisPETInteractionEvent"
)
_DKPRValue = _Class("_DKPRValue")
_DKPRStream = _Class("_DKPRStream")
CloudFamilyAnalysisPETCloudFamilyAnalysisEvent = _Class(
    "CloudFamilyAnalysisPETCloudFamilyAnalysisEvent"
)
_DKSyncPeerMO = _Class("_DKSyncPeerMO")
_DKStructuredMetadataMO = _Class("_DKStructuredMetadataMO")
_DKKeyValueMO = _Class("_DKKeyValueMO")
_CDInteractionRecord = _Class("_CDInteractionRecord")
_DKChangeSetMO = _Class("_DKChangeSetMO")
_CDContactRecord = _Class("_CDContactRecord")
_CDKeywordRecord = _Class("_CDKeywordRecord")
_DKRelationMO = _Class("_DKRelationMO")
_CDAttachmentRecord = _Class("_CDAttachmentRecord")
_CDVersionRecord = _Class("_CDVersionRecord")
_DKCustomMetadataMO = _Class("_DKCustomMetadataMO")
_DKObjectMO = _Class("_DKObjectMO")
_DKIdentifierMO = _Class("_DKIdentifierMO")
_DKCategoryMO = _Class("_DKCategoryMO")
_DKEventMO = _Class("_DKEventMO")
_DKQuantityMO = _Class("_DKQuantityMO")
_DKSourceMO = _Class("_DKSourceMO")
_DKHistogramValueMO = _Class("_DKHistogramValueMO")
_DKHistogramMO = _Class("_DKHistogramMO")
_DKPredictionTimeline = _Class("_DKPredictionTimeline")
_DKCategoryCache = _Class("_DKCategoryCache")
_DKEventStreamCache = _Class("_DKEventStreamCache")
_DKSyncOperation = _Class("_DKSyncOperation")
_DKSyncBlockOperation = _Class("_DKSyncBlockOperation")
_DKSyncCompositeOperation = _Class("_DKSyncCompositeOperation")
_DKPerformSyncUpHistoryOperation = _Class("_DKPerformSyncUpHistoryOperation")
_DKPerformSyncDownPeerAdditionsOperation = _Class(
    "_DKPerformSyncDownPeerAdditionsOperation"
)
_DKPerformSyncUpHistoryDeletionsOperation = _Class(
    "_DKPerformSyncUpHistoryDeletionsOperation"
)
_DKPerformSyncUpHistoryAdditionsOperation = _Class(
    "_DKPerformSyncUpHistoryAdditionsOperation"
)
_DKPerformSyncDownPeerDeletionsOperation = _Class(
    "_DKPerformSyncDownPeerDeletionsOperation"
)
_DKSyncBlockCompositeOperation = _Class("_DKSyncBlockCompositeOperation")
_DKPerformSyncUpChangeOperation = _Class("_DKPerformSyncUpChangeOperation")
_DKPerformSyncDownOperation = _Class("_DKPerformSyncDownOperation")
_DKPerformSyncDownPeerOperation = _Class("_DKPerformSyncDownPeerOperation")
_DKModifyRecordsOperation = _Class("_DKModifyRecordsOperation")
_DKFetchRecordZoneChangesOperation = _Class("_DKFetchRecordZoneChangesOperation")
_DKQueryOperation = _Class("_DKQueryOperation")
_DKFetchDatabaseChangesOperation = _Class("_DKFetchDatabaseChangesOperation")
_DKFetchRecordZonesOperation = _Class("_DKFetchRecordZonesOperation")
_DKModifyRecordZonesOperation = _Class("_DKModifyRecordZonesOperation")
_DKQuery = _Class("_DKQuery")
_DKHistogramQuery = _Class("_DKHistogramQuery")
_DKEventQuery = _Class("_DKEventQuery")
_DKPredictionQuery = _Class("_DKPredictionQuery")
