'''
Classes from the 'CoreDAV' framework.
'''

try:
    from rubicon.objc import ObjCClass
except ValueError:
    def ObjCClass(name):
        return None


def _Class(name):
    try:
        return ObjCClass(name)
    except NameError:
        return None

    
CoreDAVXMLElementGenerator = _Class('CoreDAVXMLElementGenerator')
CoreDAVXMLElementAttribute = _Class('CoreDAVXMLElementAttribute')
CoreDAVParseRule = _Class('CoreDAVParseRule')
CoreDAVItemParserMapping = _Class('CoreDAVItemParserMapping')
CoreDAVXMLData_Impl = _Class('CoreDAVXMLData_Impl')
CoreDAVExpandProperty = _Class('CoreDAVExpandProperty')
CoreDAVOctetStreamParser = _Class('CoreDAVOctetStreamParser')
CoreDAVOctetStreamToFileParser = _Class('CoreDAVOctetStreamToFileParser')
CoreDAVNullParser = _Class('CoreDAVNullParser')
CoreDAVXMLData = _Class('CoreDAVXMLData')
CoreDAVRequestLogger = _Class('CoreDAVRequestLogger')
CoreDAVSRVResourceRecord = _Class('CoreDAVSRVResourceRecord')
CoreDAVLogging = _Class('CoreDAVLogging')
CoreDAVLeafDataPayload = _Class('CoreDAVLeafDataPayload')
CoreDAVItem = _Class('CoreDAVItem')
CoreDAVMatchResultsItem = _Class('CoreDAVMatchResultsItem')
CoreDAVItemWithHrefChildItem = _Class('CoreDAVItemWithHrefChildItem')
CoreDAVItemWithHrefChildItemTolerateBarePayload = _Class('CoreDAVItemWithHrefChildItemTolerateBarePayload')
CoreDAVBulkRequestsSupportedItem = _Class('CoreDAVBulkRequestsSupportedItem')
CoreDAVBulkRequestsSetItem = _Class('CoreDAVBulkRequestsSetItem')
CoreDAVBulkRequestsItem = _Class('CoreDAVBulkRequestsItem')
CoreDAVPropertySearchItem = _Class('CoreDAVPropertySearchItem')
CoreDAVItemWithHrefChildren = _Class('CoreDAVItemWithHrefChildren')
CoreDAVResourceTypeItem = _Class('CoreDAVResourceTypeItem')
CoreDAVCalendarServerEmailAddressSetItem = _Class('CoreDAVCalendarServerEmailAddressSetItem')
CoreDAVCalendarServerTransportItem = _Class('CoreDAVCalendarServerTransportItem')
CoreDAVCalendarServerPushTransportsItem = _Class('CoreDAVCalendarServerPushTransportsItem')
CoreDAVSupportedReportSetItem = _Class('CoreDAVSupportedReportSetItem')
CoreDAVSupportedReportItem = _Class('CoreDAVSupportedReportItem')
CoreDAVSetItem = _Class('CoreDAVSetItem')
CoreDAVRemoveItem = _Class('CoreDAVRemoveItem')
CoreDAVPropStatItem = _Class('CoreDAVPropStatItem')
CoreDAVPropFindItem = _Class('CoreDAVPropFindItem')
CoreDAVPropertyUpdateItem = _Class('CoreDAVPropertyUpdateItem')
CoreDAVMultiStatusItem = _Class('CoreDAVMultiStatusItem')
CoreDAVSyncReportItem = _Class('CoreDAVSyncReportItem')
CoreDAVMkcolResponseItem = _Class('CoreDAVMkcolResponseItem')
CoreDAVLeafItem = _Class('CoreDAVLeafItem')
CoreDAVHrefItem = _Class('CoreDAVHrefItem')
CoreDAVCurrentUserPrincipalItem = _Class('CoreDAVCurrentUserPrincipalItem')
CoreDAVPrincipalSearchPropertySetItem = _Class('CoreDAVPrincipalSearchPropertySetItem')
CoreDAVPrincipalSearchPropertyItem = _Class('CoreDAVPrincipalSearchPropertyItem')
CoreDAVCurrentUserPrivilegeSetItem = _Class('CoreDAVCurrentUserPrivilegeSetItem')
CoreDAVItemWithNoChildren = _Class('CoreDAVItemWithNoChildren')
CoreDAVDenyItem = _Class('CoreDAVDenyItem')
CoreDAVGrantItem = _Class('CoreDAVGrantItem')
CoreDAVPrincipalItem = _Class('CoreDAVPrincipalItem')
CoreDAVInvertItem = _Class('CoreDAVInvertItem')
CoreDAVACEItem = _Class('CoreDAVACEItem')
CoreDAVACLItem = _Class('CoreDAVACLItem')
CoreDAVResponseItem = _Class('CoreDAVResponseItem')
CoreDAVErrorItem = _Class('CoreDAVErrorItem')
CoreDAVDiscoveryAccountInfo = _Class('CoreDAVDiscoveryAccountInfo')
CoreDAVTask = _Class('CoreDAVTask')
CoreDAVBulkChangeTask = _Class('CoreDAVBulkChangeTask')
CardDAVBulkChangeTask = _Class('CardDAVBulkChangeTask')
CoreDAVMultiPutTask = _Class('CoreDAVMultiPutTask')
CardDAVMultiPutTask = _Class('CardDAVMultiPutTask')
CoreDAVHeadTask = _Class('CoreDAVHeadTask')
CoreDAVGetTask = _Class('CoreDAVGetTask')
CardDAVFolderGetTask = _Class('CardDAVFolderGetTask')
CoreDAVGetToFileTask = _Class('CoreDAVGetToFileTask')
CoreDAVACLTask = _Class('CoreDAVACLTask')
CoreDAVPrincipalSearchPropertySetTask = _Class('CoreDAVPrincipalSearchPropertySetTask')
CoreDAVCopyOrMoveTask = _Class('CoreDAVCopyOrMoveTask')
CoreDAVMoveTask = _Class('CoreDAVMoveTask')
CoreDAVCopyTask = _Class('CoreDAVCopyTask')
CoreDAVSRVLookupTask = _Class('CoreDAVSRVLookupTask')
CoreDAVPropertyFindBaseTask = _Class('CoreDAVPropertyFindBaseTask')
CoreDAVExpandPropertiesTask = _Class('CoreDAVExpandPropertiesTask')
CoreDAVPrincipalPropertySearchTask = _Class('CoreDAVPrincipalPropertySearchTask')
CoreDAVSyncReportTask = _Class('CoreDAVSyncReportTask')
CoreDAVPropFindTask = _Class('CoreDAVPropFindTask')
CoreDAVOptionsTask = _Class('CoreDAVOptionsTask')
CoreDAVActionBackedTask = _Class('CoreDAVActionBackedTask')
CoreDAVPropPatchTask = _Class('CoreDAVPropPatchTask')
CoreDAVMkcolTask = _Class('CoreDAVMkcolTask')
CoreDAVPostOrPutTask = _Class('CoreDAVPostOrPutTask')
CoreDAVPostTask = _Class('CoreDAVPostTask')
CoreDAVPutTask = _Class('CoreDAVPutTask')
CoreDAVPutStreamTask = _Class('CoreDAVPutStreamTask')
CoreDAVDeleteTask = _Class('CoreDAVDeleteTask')
CoreDAVContainerQueryTask = _Class('CoreDAVContainerQueryTask')
CardDAVFolderQueryTask = _Class('CardDAVFolderQueryTask')
CoreDAVContainerMultiGetTask = _Class('CoreDAVContainerMultiGetTask')
CoreDAVFolderContentsMultiGetTask = _Class('CoreDAVFolderContentsMultiGetTask')
CardDAVFolderMultiGetTask = _Class('CardDAVFolderMultiGetTask')
CoreDAVContainer = _Class('CoreDAVContainer')
CardDAVAddressBookContainer = _Class('CardDAVAddressBookContainer')
CoreDAVAction = _Class('CoreDAVAction')
CoreDAVOrderedAction = _Class('CoreDAVOrderedAction')
CoreDAVTaskGroup = _Class('CoreDAVTaskGroup')
CoreDAVMultiMoveWithFallbackTaskGroup = _Class('CoreDAVMultiMoveWithFallbackTaskGroup')
CoreDAVMultiGetWithFallbackTaskGroup = _Class('CoreDAVMultiGetWithFallbackTaskGroup')
CoreDAVMoveWithFallbackTaskGroup = _Class('CoreDAVMoveWithFallbackTaskGroup')
CardDAVUpdateMeCardTaskGroup = _Class('CardDAVUpdateMeCardTaskGroup')
CoreDAVBulkUploadTaskGroup = _Class('CoreDAVBulkUploadTaskGroup')
CardDAVBulkUploadTaskGroup = _Class('CardDAVBulkUploadTaskGroup')
CoreDAVValidatePrincipalsTaskGroup = _Class('CoreDAVValidatePrincipalsTaskGroup')
CoreDAVRecursiveContainerSyncTaskGroup = _Class('CoreDAVRecursiveContainerSyncTaskGroup')
CoreDAVContainerInfoSyncTaskGroup = _Class('CoreDAVContainerInfoSyncTaskGroup')
CoreDAVUpdateACLTaskGroup = _Class('CoreDAVUpdateACLTaskGroup')
CoreDAVDiscoveryTaskGroup = _Class('CoreDAVDiscoveryTaskGroup')
CoreDAVContainerSyncTaskGroup = _Class('CoreDAVContainerSyncTaskGroup')
CardDAVFolderSyncTaskGroup = _Class('CardDAVFolderSyncTaskGroup')
CoreDAVContainerInfoTaskGroup = _Class('CoreDAVContainerInfoTaskGroup')
CardDAVFolderInfoTaskGroup = _Class('CardDAVFolderInfoTaskGroup')
CoreDAVGetAccountPropertiesTaskGroup = _Class('CoreDAVGetAccountPropertiesTaskGroup')
CardDAVGetAccountPropertiesTaskGroup = _Class('CardDAVGetAccountPropertiesTaskGroup')
CoreDAVXMLParser = _Class('CoreDAVXMLParser')
