'''
Classes from the 'CorePDF' framework.
'''

try:
    from rubicon.objc import ObjCClass
except ValueError:
    def ObjCClass(name):
        return None


def _Class(name):
    try:
        return ObjCClass(name)
    except NameError:
        return None

    
CPImageObjectData = _Class('CPImageObjectData')
CPDocumentAndData = _Class('CPDocumentAndData')
CPPDFAnnotationParserDelegate = _Class('CPPDFAnnotationParserDelegate')
UIPDFMagnifierController = _Class('UIPDFMagnifierController')
CPRMTableCell = _Class('CPRMTableCell')
UIPDFSearchHighlightsController = _Class('UIPDFSearchHighlightsController')
CPRMList = _Class('CPRMList')
UIPDFPlacementController = _Class('UIPDFPlacementController')
CPRMTable = _Class('CPRMTable')
UIPDFAnnotationController = _Class('UIPDFAnnotationController')
UIPDFAnnotationParserDelegate = _Class('UIPDFAnnotationParserDelegate')
UIPDFPageImageCache = _Class('UIPDFPageImageCache')
UIPDFPageRenderJob = _Class('UIPDFPageRenderJob')
UIPDFPageContentDelegate = _Class('UIPDFPageContentDelegate')
UIPDFViewManager = _Class('UIPDFViewManager')
UIPDFTextRangeWidget = _Class('UIPDFTextRangeWidget')
UIPDFSelectionController = _Class('UIPDFSelectionController')
UIPDFParagraphWidget = _Class('UIPDFParagraphWidget')
UIPDFSelection = _Class('UIPDFSelection')
UIPDFParserDelegate = _Class('UIPDFParserDelegate')
UIPDFPage = _Class('UIPDFPage')
UIPDFDocument = _Class('UIPDFDocument')
CPZoneMaker = _Class('CPZoneMaker')
CPZoneFilter = _Class('CPZoneFilter')
CPZoneBorderNeighbor = _Class('CPZoneBorderNeighbor')
CPZoneBorderIntersection = _Class('CPZoneBorderIntersection')
CPZoneBorder = _Class('CPZoneBorder')
CPTableMaker = _Class('CPTableMaker')
CPSpacerFinder = _Class('CPSpacerFinder')
CPRotatedText = _Class('CPRotatedText')
CPPreformatter = _Class('CPPreformatter')
CPListMaker = _Class('CPListMaker')
CPLineBreaker = _Class('CPLineBreaker')
CPInterval = _Class('CPInterval')
CPHighlighter = _Class('CPHighlighter')
CPGuideFinder = _Class('CPGuideFinder')
CPGraphicMaker = _Class('CPGraphicMaker')
CPReadingModel = _Class('CPReadingModel')
CPFontKerning = _Class('CPFontKerning')
CPFontInfo = _Class('CPFontInfo')
CPCompoundGraphicMaker = _Class('CPCompoundGraphicMaker')
CPCluster = _Class('CPCluster')
CPCharSequence = _Class('CPCharSequence')
CPMemoryOwner = _Class('CPMemoryOwner')
CPTextLineSplitter = _Class('CPTextLineSplitter')
CPTextLineMerge = _Class('CPTextLineMerge')
CPTextLineMaker = _Class('CPTextLineMaker')
CPTextBoxMaker = _Class('CPTextBoxMaker')
CPParagraphMaker = _Class('CPParagraphMaker')
CPParagraphFlow = _Class('CPParagraphFlow')
CPLayoutMaker = _Class('CPLayoutMaker')
CPRMHeading = _Class('CPRMHeading')
CPColumnMaker = _Class('CPColumnMaker')
CPBuilder = _Class('CPBuilder')
CPHeadingFinder = _Class('CPHeadingFinder')
CPFont = _Class('CPFont')
CPHitTest = _Class('CPHitTest')
CPArchive = _Class('CPArchive')
CPRMListItem = _Class('CPRMListItem')
CPParagraphListItem = _Class('CPParagraphListItem')
CPList = _Class('CPList')
CPGenericVisitor = _Class('CPGenericVisitor')
CPObjectUtility = _Class('CPObjectUtility')
CPDocument = _Class('CPDocument')
CPObject = _Class('CPObject')
CPChunk = _Class('CPChunk')
CPTextObject = _Class('CPTextObject')
CPTextLine = _Class('CPTextLine')
CPTableCell = _Class('CPTableCell')
CPTable = _Class('CPTable')
CPRegion = _Class('CPRegion')
CPZone = _Class('CPZone')
CPRotation = _Class('CPRotation')
CPIsland = _Class('CPIsland')
CPBody = _Class('CPBody')
CPTextBox = _Class('CPTextBox')
CPParagraph = _Class('CPParagraph')
CPLayoutArea = _Class('CPLayoutArea')
CPGraphicRegion = _Class('CPGraphicRegion')
CPShapeRegion = _Class('CPShapeRegion')
CPImageRegion = _Class('CPImageRegion')
CPColumn = _Class('CPColumn')
CPGraphicObject = _Class('CPGraphicObject')
CPShape = _Class('CPShape')
CPImage = _Class('CPImage')
CPCompoundGraphic = _Class('CPCompoundGraphic')
CPPage = _Class('CPPage')
UIPDFHighlighter = _Class('UIPDFHighlighter')
UIPDFAnnotation = _Class('UIPDFAnnotation')
UIPDFTextAnnotation = _Class('UIPDFTextAnnotation')
UIPDFStampAnnotation = _Class('UIPDFStampAnnotation')
UIPDFPopupAnnotation = _Class('UIPDFPopupAnnotation')
UIPDFLineAnnotation = _Class('UIPDFLineAnnotation')
UIPDFMarkupAnnotation = _Class('UIPDFMarkupAnnotation')
UIPDFUnderlineAnnotation = _Class('UIPDFUnderlineAnnotation')
UIPDFStrikeOutAnnotation = _Class('UIPDFStrikeOutAnnotation')
UIPDFLinkAnnotation = _Class('UIPDFLinkAnnotation')
UIPDFHighlightAnnotation = _Class('UIPDFHighlightAnnotation')
UIPDFFreeTextAnnotation = _Class('UIPDFFreeTextAnnotation')
UIPDFSquareOrCircleAnnotation = _Class('UIPDFSquareOrCircleAnnotation')
UIPDFCircleAnnotation = _Class('UIPDFCircleAnnotation')
UIPDFSquareAnnotation = _Class('UIPDFSquareAnnotation')
SurfaceLayer = _Class('SurfaceLayer')
UIPDFPageContentLayer = _Class('UIPDFPageContentLayer')
UIPDFHighlightLayer = _Class('UIPDFHighlightLayer')
UIPDFPageContentTiledLayer = _Class('UIPDFPageContentTiledLayer')
UIPDFPageRenderOperation = _Class('UIPDFPageRenderOperation')
UIPDFViewTouchHandler = _Class('UIPDFViewTouchHandler')
UIPDFPageView = _Class('UIPDFPageView')
UIPDFAnnotationView = _Class('UIPDFAnnotationView')
UIPDFHighlightAnnotationView = _Class('UIPDFHighlightAnnotationView')
UIPDFPopupAnnotationView = _Class('UIPDFPopupAnnotationView')
UIPDFUnderlineAnnotationView = _Class('UIPDFUnderlineAnnotationView')
UIPDFWidget = _Class('UIPDFWidget')
