"""
Classes from the 'DifferentialPrivacy' framework.
"""

try:
    from rubicon.objc import ObjCClass
except ValueError:

    def ObjCClass(name):
        return None


def _Class(name):
    try:
        return ObjCClass(name)
    except NameError:
        return None


_DPLog = _Class("_DPLog")
_DPKeyProperties = _Class("_DPKeyProperties")
_DPToolArguments = _Class("_DPToolArguments")
_DPPTRecordMOConverter = _Class("_DPPTRecordMOConverter")
_DPPTRecord = _Class("_DPPTRecord")
_DPCMSSample = _Class("_DPCMSSample")
_DPPrivacyBudgetManager = _Class("_DPPrivacyBudgetManager")
_DPPuzzleBox = _Class("_DPPuzzleBox")
_DPBlacklist = _Class("_DPBlacklist")
_DPPrioSeedablePRNG = _Class("_DPPrioSeedablePRNG")
_DPInputHelper = _Class("_DPInputHelper")
_DPBiasedCoin = _Class("_DPBiasedCoin")
_DPStringRandomizer = _Class("_DPStringRandomizer")
_DPDiagnosticDataReporter = _Class("_DPDiagnosticDataReporter")
_DPBitValueDataRecordMOConverter = _Class("_DPBitValueDataRecordMOConverter")
_DPBitValueRecord = _Class("_DPBitValueRecord")
_DPBitValueMap = _Class("_DPBitValueMap")
_DPPeriodicTaskManager = _Class("_DPPeriodicTaskManager")
_DPPeriodicTask = _Class("_DPPeriodicTask")
_DPNumberRandomizer = _Class("_DPNumberRandomizer")
_DPStringRecorder = _Class("_DPStringRecorder")
_DPRecordQueryPredicates = _Class("_DPRecordQueryPredicates")
_DPPrioValueRandomizer = _Class("_DPPrioValueRandomizer")
_DPHCMSRandomizer = _Class("_DPHCMSRandomizer")
_DPDataProtectionStateMonitor = _Class("_DPDataProtectionStateMonitor")
_DPDataProtectionMaster = _Class("_DPDataProtectionMaster")
_DPPrivacyBudgetRecordMOConverter = _Class("_DPPrivacyBudgetRecordMOConverter")
_DPPrivacyBudgetRecord = _Class("_DPPrivacyBudgetRecord")
_DPDeviceInfo = _Class("_DPDeviceInfo")
_DPPCCRecordMOConverter = _Class("_DPPCCRecordMOConverter")
_DPPCCRecord = _Class("_DPPCCRecord")
_DPServer = _Class("_DPServer")
_DPPCCValueRandomizer = _Class("_DPPCCValueRandomizer")
_DPToolCommand = _Class("_DPToolCommand")
_DPUploadHelper = _Class("_DPUploadHelper")
_DPPrioRecordMOConverter = _Class("_DPPrioRecordMOConverter")
_DPPrioRecord = _Class("_DPPrioRecord")
_DPHCMSSample = _Class("_DPHCMSSample")
_DPPrioCountMinSketchValueRandomizer = _Class("_DPPrioCountMinSketchValueRandomizer")
_DPAlgorithmParameters = _Class("_DPAlgorithmParameters")
_DPPTValueRandomizer = _Class("_DPPTValueRandomizer")
_DPNumericDataRecorder = _Class("_DPNumericDataRecorder")
_DPCMSRandomizer = _Class("_DPCMSRandomizer")
_DPReportGenerator = _Class("_DPReportGenerator")
_DPPrioReporter = _Class("_DPPrioReporter")
_DPUniformNoiseGenerator = _Class("_DPUniformNoiseGenerator")
_DPPrivacyBudgetProperties = _Class("_DPPrivacyBudgetProperties")
_DPModelInfoRecordMOConverter = _Class("_DPModelInfoRecordMOConverter")
_DPModelInfoRecord = _Class("_DPModelInfoRecord")
_DPLaplaceNoiseGenerator = _Class("_DPLaplaceNoiseGenerator")
_DPStrings = _Class("_DPStrings")
_DPPrivacyBudget = _Class("_DPPrivacyBudget")
_DPWordRecord = _Class("_DPWordRecord")
_DPErrorUtilities = _Class("_DPErrorUtilities")
_DPRandomBitPositionGenerator = _Class("_DPRandomBitPositionGenerator")
_DPStorage = _Class("_DPStorage")
_DPRandomizedBit = _Class("_DPRandomizedBit")
_DPBitValueRandomizer = _Class("_DPBitValueRandomizer")
_DPValueRange = _Class("_DPValueRange")
_DPReportFilesMaintainer = _Class("_DPReportFilesMaintainer")
_DPOBHRandomizer = _Class("_DPOBHRandomizer")
_DPSubmissionRateLimiter = _Class("_DPSubmissionRateLimiter")
_DPCoreDataStorage = _Class("_DPCoreDataStorage")
_DPBitValueRecorder = _Class("_DPBitValueRecorder")
_DPWordRecorder = _Class("_DPWordRecorder")
_DPNumericDataRecordMOConverter = _Class("_DPNumericDataRecordMOConverter")
_DPNumericDataRecord = _Class("_DPNumericDataRecord")
_DPPrioAlgorithm = _Class("_DPPrioAlgorithm")
_DPJSONSegment = _Class("_DPJSONSegment")
_DPCoreAnalyticsCollector = _Class("_DPCoreAnalyticsCollector")
_DPReportFileManager = _Class("_DPReportFileManager")
_DPKeyNames = _Class("_DPKeyNames")
_DPBlacklistServerStorage = _Class("_DPBlacklistServerStorage")
_DPDataRecorder = _Class("_DPDataRecorder")
_DPXPCRecorder = _Class("_DPXPCRecorder")
_DPDatabaseRecorder = _Class("_DPDatabaseRecorder")
_DPDaemonConnection = _Class("_DPDaemonConnection")
_DPBlacklistManager = _Class("_DPBlacklistManager")
_DPJSONOutputHelper = _Class("_DPJSONOutputHelper")
_DPCMSRecordMOConverter = _Class("_DPCMSRecordMOConverter")
_DPCMSRecord = _Class("_DPCMSRecord")
_DPCMSSequenceRecord = _Class("_DPCMSSequenceRecord")
_DPHCMSSequenceRecord = _Class("_DPHCMSSequenceRecord")
_DPCMSWordRecord = _Class("_DPCMSWordRecord")
_DPHCMSWordRecord = _Class("_DPHCMSWordRecord")
_DPOBHRecordMOConverter = _Class("_DPOBHRecordMOConverter")
_DPOBHRecord = _Class("_DPOBHRecord")
_DPOBHSequenceRecord = _Class("_DPOBHSequenceRecord")
_DPPCCRecordMO = _Class("_DPPCCRecordMO")
_DPPrioRecordMO = _Class("_DPPrioRecordMO")
_DPCMSRecordMO = _Class("_DPCMSRecordMO")
_DPCMSSequenceMO = _Class("_DPCMSSequenceMO")
_DPHCMSSequenceMO = _Class("_DPHCMSSequenceMO")
_DPCMSWordMO = _Class("_DPCMSWordMO")
_DPHCMSWordMO = _Class("_DPHCMSWordMO")
_DPPTRecordMO = _Class("_DPPTRecordMO")
_DPModelInfoRecordMO = _Class("_DPModelInfoRecordMO")
_DPBitValueRecordMO = _Class("_DPBitValueRecordMO")
_DPNumericDataRecordMO = _Class("_DPNumericDataRecordMO")
_DPOBHRecordMO = _Class("_DPOBHRecordMO")
_DPOBHSequenceMO = _Class("_DPOBHSequenceMO")
_DPPrivacyBudgetRecordMO = _Class("_DPPrivacyBudgetRecordMO")
_DPPrioError = _Class("_DPPrioError")
