'''
Classes from the 'IDS' framework.
'''

try:
    from rubicon.objc import ObjCClass
except ValueError:
    def ObjCClass(name):
        return None


def _Class(name):
    try:
        return ObjCClass(name)
    except NameError:
        return None

    
IDSDaemonControllerForwarder = _Class('IDSDaemonControllerForwarder')
IDSTransactionLogTaskHandler = _Class('IDSTransactionLogTaskHandler')
IDSTransactionLogSyncTaskHandler = _Class('IDSTransactionLogSyncTaskHandler')
IDSTransactionLogBaseTaskHandler = _Class('IDSTransactionLogBaseTaskHandler')
IDSTransactionLogTaskHandlerAccountInfo = _Class('IDSTransactionLogTaskHandlerAccountInfo')
IDSServiceMonitor = _Class('IDSServiceMonitor')
IDSRealTimeEncryptionProxy = _Class('IDSRealTimeEncryptionProxy')
_IDSBatchIDQueryController = _Class('_IDSBatchIDQueryController')
_IDSActivityMonitorXPCConnector = _Class('_IDSActivityMonitorXPCConnector')
IDSInternalQueueController = _Class('IDSInternalQueueController')
IDSGroupContextDataSource = _Class('IDSGroupContextDataSource')
_IDSSession = _Class('_IDSSession')
_IDSContinuity = _Class('_IDSContinuity')
IDSIDQueryController = _Class('IDSIDQueryController')
IDSXPCActivityMonitorInterface = _Class('IDSXPCActivityMonitorInterface')
IDSDeviceConnection = _Class('IDSDeviceConnection')
_IDSXPCCheckinManager = _Class('_IDSXPCCheckinManager')
_IDSXPCCheckInInfo = _Class('_IDSXPCCheckInInfo')
IDSDatagramChannel = _Class('IDSDatagramChannel')
_IDSDatagramChannel = _Class('_IDSDatagramChannel')
IDSDataChannelLinkContext = _Class('IDSDataChannelLinkContext')
_IDSDataChannelLinkContext = _Class('_IDSDataChannelLinkContext')
IDSDevice = _Class('IDSDevice')
IDSXPCOpportunisticInterface = _Class('IDSXPCOpportunisticInterface')
_IDSIDQueryController = _Class('_IDSIDQueryController')
_IDSDevice = _Class('_IDSDevice')
IDSXPCConnectionTimeoutProxy = _Class('IDSXPCConnectionTimeoutProxy')
IDSXPCConnection = _Class('IDSXPCConnection')
IDSLogging = _Class('IDSLogging')
IDSTransportLog = _Class('IDSTransportLog')
IDSPhoneSubscriptionSelector = _Class('IDSPhoneSubscriptionSelector')
IDSPhoneTemporaryAliasDescription = _Class('IDSPhoneTemporaryAliasDescription')
IDSPhoneSubscription = _Class('IDSPhoneSubscription')
IDSTransactionLogMessage = _Class('IDSTransactionLogMessage')
IDSTransactionLogDictionaryMessage = _Class('IDSTransactionLogDictionaryMessage')
IDSTransactionLogDataMessage = _Class('IDSTransactionLogDataMessage')
_IDSService = _Class('_IDSService')
IDSAutoCleanup = _Class('IDSAutoCleanup')
IDSDaemonRequestTimer = _Class('IDSDaemonRequestTimer')
IDSDaemonRequestContext = _Class('IDSDaemonRequestContext')
IDSService = _Class('IDSService')
IDSXPCPairedDeviceManagerInterface = _Class('IDSXPCPairedDeviceManagerInterface')
_IDSAccount = _Class('_IDSAccount')
IDSReportiMessageSpamDaemonResponseListener = _Class('IDSReportiMessageSpamDaemonResponseListener')
IDSHomeKitManager = _Class('IDSHomeKitManager')
IDSAccount = _Class('IDSAccount')
IDSLocalPairingRecord = _Class('IDSLocalPairingRecord')
IDSLocalPairingLocalDeviceRecord = _Class('IDSLocalPairingLocalDeviceRecord')
IDSLocalPairingPairedDeviceRecord = _Class('IDSLocalPairingPairedDeviceRecord')
IDSLocalPairingIdentityDataErrorPair = _Class('IDSLocalPairingIdentityDataErrorPair')
IDSXPCDaemonController = _Class('IDSXPCDaemonController')
_IDSAccountController = _Class('_IDSAccountController')
_IDSDeviceConnection = _Class('_IDSDeviceConnection')
_IDSDeviceConnectionActiveMap = _Class('_IDSDeviceConnectionActiveMap')
IDSLocalPairingAddPairedDeviceInfo = _Class('IDSLocalPairingAddPairedDeviceInfo')
IDSQuickSwitchAcknowledgementTracker = _Class('IDSQuickSwitchAcknowledgementTracker')
IDSDaemonProtocolController = _Class('IDSDaemonProtocolController')
_IDSConnection = _Class('_IDSConnection')
IDSQuickRelayFixedTokenAllocator = _Class('IDSQuickRelayFixedTokenAllocator')
IDSGroupContextControllerContent = _Class('IDSGroupContextControllerContent')
IDSGroupContextController = _Class('IDSGroupContextController')
_IDSGroupSession = _Class('_IDSGroupSession')
IDSAccountController = _Class('IDSAccountController')
IDSXPCConnectionRemoteObjectPromise = _Class('IDSXPCConnectionRemoteObjectPromise')
IDSRegistrationControlDaemonResponseListener = _Class('IDSRegistrationControlDaemonResponseListener')
IDSPhoneCertificateVendor = _Class('IDSPhoneCertificateVendor')
IDSAuthenticationSigningResult = _Class('IDSAuthenticationSigningResult')
IDSAuthenticationCertificateSignature = _Class('IDSAuthenticationCertificateSignature')
IDSCarrierToken = _Class('IDSCarrierToken')
IDSCarrierTokenRequestParameters = _Class('IDSCarrierTokenRequestParameters')
IDSPairedDeviceManager = _Class('IDSPairedDeviceManager')
IDSXPCDaemonClientInterface = _Class('IDSXPCDaemonClientInterface')
IDSXPCDaemonInterface = _Class('IDSXPCDaemonInterface')
IDSGroupSessionUnicastParameter = _Class('IDSGroupSessionUnicastParameter')
_IDSPasswordManager = _Class('_IDSPasswordManager')
IDSTransactionLogTask = _Class('IDSTransactionLogTask')
IDSTransactionLogSyncTask = _Class('IDSTransactionLogSyncTask')
IDSDaemonResponseHandler = _Class('IDSDaemonResponseHandler')
IDSXPCPairingInterface = _Class('IDSXPCPairingInterface')
IDSConnection = _Class('IDSConnection')
IDSBatchIDQueryController = _Class('IDSBatchIDQueryController')
IDSAppleCareDaemonResponseListener = _Class('IDSAppleCareDaemonResponseListener')
IDSSession = _Class('IDSSession')
IDSSignInController = _Class('IDSSignInController')
IDSSignInControllerAccountDescription = _Class('IDSSignInControllerAccountDescription')
IDSSignInServiceUserStatus = _Class('IDSSignInServiceUserStatus')
IDSSignInServiceUserInfo = _Class('IDSSignInServiceUserInfo')
IDSGroupContextNotifyingObserver = _Class('IDSGroupContextNotifyingObserver')
IDSActivityMonitor = _Class('IDSActivityMonitor')
IDSActivityUpdate = _Class('IDSActivityUpdate')
IDSActivityInfo = _Class('IDSActivityInfo')
_IDSRealTimeEncryptionProxy = _Class('_IDSRealTimeEncryptionProxy')
IDSDaemonListener = _Class('IDSDaemonListener')
IDSServiceContainer = _Class('IDSServiceContainer')
IDSServiceAvailabilityController = _Class('IDSServiceAvailabilityController')
IDSXPCRegistrationInterface = _Class('IDSXPCRegistrationInterface')
IDSGroupSession = _Class('IDSGroupSession')
IDSXPCReunionSyncInterface = _Class('IDSXPCReunionSyncInterface')
IDSXPCInternalTestingInterface = _Class('IDSXPCInternalTestingInterface')
IDSDaemonController = _Class('IDSDaemonController')
IDSContinuity = _Class('IDSContinuity')
_IDSGenericCompletionHandler = _Class('_IDSGenericCompletionHandler')
_IDSCompletionHandler = _Class('_IDSCompletionHandler')
