"""
Classes from the 'ManagedConfiguration' framework.
"""

try:
    from rubicon.objc import ObjCClass
except ValueError:

    def ObjCClass(name):
        return None


def _Class(name):
    try:
        return ObjCClass(name)
    except NameError:
        return None


MCMDMDeviceQueryUtilities = _Class("MCMDMDeviceQueryUtilities")
MCDomainsCacheEntry = _Class("MCDomainsCacheEntry")
MCSingleAppModeConfiguration = _Class("MCSingleAppModeConfiguration")
MCSingleSignOnPayloadKerberosInfo = _Class("MCSingleSignOnPayloadKerberosInfo")
MCHTTPRequestor = _Class("MCHTTPRequestor")
MCBatterySaverMode = _Class("MCBatterySaverMode")
MCPasscodeManager = _Class("MCPasscodeManager")
MCMDMConfiguration = _Class("MCMDMConfiguration")
MCManagedMediaManagerReader = _Class("MCManagedMediaManagerReader")
MCMDMOptionsUtilities = _Class("MCMDMOptionsUtilities")
MCAirPlayDestination = _Class("MCAirPlayDestination")
MCManagedDefaultsManager = _Class("MCManagedDefaultsManager")
MCTimerContext = _Class("MCTimerContext")
MCProcessAssertion = _Class("MCProcessAssertion")
MCPowerAssertion = _Class("MCPowerAssertion")
MCMDMPowerAssertion = _Class("MCMDMPowerAssertion")
MCUserNotificationManager = _Class("MCUserNotificationManager")
MCUserNotificationQueueEntry = _Class("MCUserNotificationQueueEntry")
MCJobQueue = _Class("MCJobQueue")
MCHacks = _Class("MCHacks")
MCCloudConfiguration = _Class("MCCloudConfiguration")
MCManagedAppManagerReader = _Class("MCManagedAppManagerReader")
MCTunnelParser = _Class("MCTunnelParser")
MCAccountUtilities = _Class("MCAccountUtilities")
MCAppEnforcedRestrictionUtilities = _Class("MCAppEnforcedRestrictionUtilities")
MCPersonaHelper = _Class("MCPersonaHelper")
MCDeviceUploadCredentials = _Class("MCDeviceUploadCredentials")
MCDeviceCapabilities = _Class("MCDeviceCapabilities")
MCProfileTrustEvaluator = _Class("MCProfileTrustEvaluator")
MCProfileWarning = _Class("MCProfileWarning")
MCInstallerReader = _Class("MCInstallerReader")
MCHoldingTankManifest = _Class("MCHoldingTankManifest")
MCCommunicationServiceRulesUtilities = _Class("MCCommunicationServiceRulesUtilities")
MCCrypto = _Class("MCCrypto")
MCMDMClient = _Class("MCMDMClient")
MCSkipSetupKeysUtilities = _Class("MCSkipSetupKeysUtilities")
MCHTTPTransaction = _Class("MCHTTPTransaction")
MCAPNInfo = _Class("MCAPNInfo")
MCBookmark = _Class("MCBookmark")
MCAPNConfiguration = _Class("MCAPNConfiguration")
MCBookmarkManager = _Class("MCBookmarkManager")
MCNotifier = _Class("MCNotifier")
MCLazyInitializationUtilities = _Class("MCLazyInitializationUtilities")
MCDeviceUploadSubmissionResponse = _Class("MCDeviceUploadSubmissionResponse")
MCDeviceUploadOrganization = _Class("MCDeviceUploadOrganization")
MCManagedDomainsCache = _Class("MCManagedDomainsCache")
MCGizmoUtilities = _Class("MCGizmoUtilities")
MCProfile = _Class("MCProfile")
MCProfileServiceProfile = _Class("MCProfileServiceProfile")
MCConfigurationProfile = _Class("MCConfigurationProfile")
MCCertificateWrapperProfile = _Class("MCCertificateWrapperProfile")
MCDependencyReader = _Class("MCDependencyReader")
MCManifest = _Class("MCManifest")
MCPayloadUserPromptUtilities = _Class("MCPayloadUserPromptUtilities")
MCDeviceUploadDeviceDetails = _Class("MCDeviceUploadDeviceDetails")
MCDeviceUploadSubmitDeviceRequestPayload = _Class(
    "MCDeviceUploadSubmitDeviceRequestPayload"
)
MCSafariPasswordAutoFillDomainsCache = _Class("MCSafariPasswordAutoFillDomainsCache")
MCKeyValueSection = _Class("MCKeyValueSection")
MCKeyValue = _Class("MCKeyValue")
MCDeviceUploadUser = _Class("MCDeviceUploadUser")
MCFileAccessRepairTool = _Class("MCFileAccessRepairTool")
MCBook = _Class("MCBook")
MCAnalyticsEvent = _Class("MCAnalyticsEvent")
MCAnalyticsProfilePurgatoryExitEvent = _Class("MCAnalyticsProfilePurgatoryExitEvent")
MCAnalyticsDailyStatusEvent = _Class("MCAnalyticsDailyStatusEvent")
MCAnalyticsWebContentFilterModeChangedEvent = _Class(
    "MCAnalyticsWebContentFilterModeChangedEvent"
)
MCAnalyticsWebContentFilterListChangedEvent = _Class(
    "MCAnalyticsWebContentFilterListChangedEvent"
)
MCAnalyticsMDMCommandEvent = _Class("MCAnalyticsMDMCommandEvent")
MCAnalyticsMDMPushEvent = _Class("MCAnalyticsMDMPushEvent")
MCAnalyticsProfilePurgatoryEnterEvent = _Class("MCAnalyticsProfilePurgatoryEnterEvent")
MCSignpost = _Class("MCSignpost")
MCProfileInfo = _Class("MCProfileInfo")
MCUserMDMClient = _Class("MCUserMDMClient")
MCVersioningUtilities = _Class("MCVersioningUtilities")
MCRestrictionUtilities = _Class("MCRestrictionUtilities")
MCStateHandler = _Class("MCStateHandler")
MCProfileStateHandler = _Class("MCProfileStateHandler")
MCKeychain = _Class("MCKeychain")
MCDictionaryWriter = _Class("MCDictionaryWriter")
MCPayload = _Class("MCPayload")
MCLoggingPayload = _Class("MCLoggingPayload")
MCFontPayload = _Class("MCFontPayload")
MCWebContentFilterPayload = _Class("MCWebContentFilterPayload")
MCSingleSignOnPayload = _Class("MCSingleSignOnPayload")
MCEDUClassroomPayload = _Class("MCEDUClassroomPayload")
MCAppWhitelistPayloadBase = _Class("MCAppWhitelistPayloadBase")
MCSingleAppPayload = _Class("MCSingleAppPayload")
MCOSXServerAccountPayload = _Class("MCOSXServerAccountPayload")
MCAirPlayPayload = _Class("MCAirPlayPayload")
MCGlobalHTTPProxyPayload = _Class("MCGlobalHTTPProxyPayload")
MCChaperonePayload = _Class("MCChaperonePayload")
MCAirPlaySecurityPayload = _Class("MCAirPlaySecurityPayload")
MCEncryptedProfileServicePayload = _Class("MCEncryptedProfileServicePayload")
MCDNSProxyPayload = _Class("MCDNSProxyPayload")
MCSetupAssistantPayload = _Class("MCSetupAssistantPayload")
MCRestrictionsPayload = _Class("MCRestrictionsPayload")
MCNetworkUsageRulesPayload = _Class("MCNetworkUsageRulesPayload")
MCExtensibleSingleSignOnPayload = _Class("MCExtensibleSingleSignOnPayload")
MCNotificationSettingsPayload = _Class("MCNotificationSettingsPayload")
MCCardDAVAccountPayload = _Class("MCCardDAVAccountPayload")
MCLDAPAccountPayload = _Class("MCLDAPAccountPayload")
MCCalDAVAccountPayload = _Class("MCCalDAVAccountPayload")
MCSubCalAccountPayload = _Class("MCSubCalAccountPayload")
MCWiFiPayload = _Class("MCWiFiPayload")
MCTVRemotePayload = _Class("MCTVRemotePayload")
MCAPNPayload = _Class("MCAPNPayload")
MCMDMPayload = _Class("MCMDMPayload")
MCCellularPayload = _Class("MCCellularPayload")
MCGmailAccountPayload = _Class("MCGmailAccountPayload")
MCConferenceRoomDisplayPayload = _Class("MCConferenceRoomDisplayPayload")
MCUnknownPayload = _Class("MCUnknownPayload")
MCCertificatePayload = _Class("MCCertificatePayload")
MCWAPIIdentityCertificatePayload = _Class("MCWAPIIdentityCertificatePayload")
MCPlainCertificatePayload = _Class("MCPlainCertificatePayload")
MCSCEPPayload = _Class("MCSCEPPayload")
MCCertificateTransparencyPayload = _Class("MCCertificateTransparencyPayload")
MCWebClipPayload = _Class("MCWebClipPayload")
MCEmailAccountPayloadBase = _Class("MCEmailAccountPayloadBase")
MCEASAccountPayload = _Class("MCEASAccountPayload")
MCEmailAccountPayload = _Class("MCEmailAccountPayload")
MCPasswordPolicyPayload = _Class("MCPasswordPolicyPayload")
MCDNSSettingsPayload = _Class("MCDNSSettingsPayload")
MCVPNPayloadBase = _Class("MCVPNPayloadBase")
MCAppLayerVPNPayload = _Class("MCAppLayerVPNPayload")
MCVPNPayload = _Class("MCVPNPayload")
MCAlwaysOnVPNPayload = _Class("MCAlwaysOnVPNPayload")
MCDefaultsPayload = _Class("MCDefaultsPayload")
MCDomainsPayload = _Class("MCDomainsPayload")
MCSharedDeviceConfigurationPayload = _Class("MCSharedDeviceConfigurationPayload")
MCRemovalPasswordPayload = _Class("MCRemovalPasswordPayload")
MCAirPrintPayload = _Class("MCAirPrintPayload")
MCHomeScreenLayoutPayload = _Class("MCHomeScreenLayoutPayload")
MCTeslaServicer = _Class("MCTeslaServicer")
MCDeviceUploadRequestType = _Class("MCDeviceUploadRequestType")
MCSignpostManager = _Class("MCSignpostManager")
MCRestrictionManager = _Class("MCRestrictionManager")
MCEDUModeUtilities = _Class("MCEDUModeUtilities")
MCProfileConnection = _Class("MCProfileConnection")
MCWorkerThread = _Class("MCWorkerThread")
