"""
Classes from the 'Message' framework.
"""

try:
    from rubicon.objc import ObjCClass
except ValueError:

    def ObjCClass(name):
        return None


def _Class(name):
    try:
        return ObjCClass(name)
    except NameError:
        return None


MFWebAttachmentSource = _Class("MFWebAttachmentSource")
MFWebMessageDocument = _Class("MFWebMessageDocument")
_MFSearchMatcherContext = _Class("_MFSearchMatcherContext")
MFSqliteMessageIDStore = _Class("MFSqliteMessageIDStore")
MFSMTPResponse = _Class("MFSMTPResponse")
_MFSecCMSDecoder = _Class("_MFSecCMSDecoder")
MFProgressiveMimeParser = _Class("MFProgressiveMimeParser")
MFPlainTextDocument = _Class("MFPlainTextDocument")
MFPlainTextFragment = _Class("MFPlainTextFragment")
MFMessageURLConnectionDelegate = _Class("MFMessageURLConnectionDelegate")
MFMessageKeychainManager = _Class("MFMessageKeychainManager")
MFMimeEnrichedReader = _Class("MFMimeEnrichedReader")
MFWeakObjectCache = _Class("MFWeakObjectCache")
_MFWeakObjectCacheRef = _Class("_MFWeakObjectCacheRef")
MFUserDefaultMigrator = _Class("MFUserDefaultMigrator")
MFUnreadCountProbe = _Class("MFUnreadCountProbe")
MFThreadFuzzyMatcher = _Class("MFThreadFuzzyMatcher")
MFTaskAssertion = _Class("MFTaskAssertion")
MFSignatures = _Class("MFSignatures")
MFSecureMIMECompositionManager = _Class("MFSecureMIMECompositionManager")
MFRFC822AttachmentDataProvider = _Class("MFRFC822AttachmentDataProvider")
MFPowerController = _Class("MFPowerController")
MFOutgoingMessageContent = _Class("MFOutgoingMessageContent")
MFOutgoingRichtextMessageContent = _Class("MFOutgoingRichtextMessageContent")
MFOutgoingMultipartRelatedContent = _Class("MFOutgoingMultipartRelatedContent")
MFOutgoingLibraryMessageContent = _Class("MFOutgoingLibraryMessageContent")
_MFNetworkObserver = _Class("_MFNetworkObserver")
MFNetworkController = _Class("MFNetworkController")
MFMigrationPersistence = _Class("MFMigrationPersistence")
MFMessageTransformer = _Class("MFMessageTransformer")
_MFMailMessageDuplicateInfo = _Class("_MFMailMessageDuplicateInfo")
MFMessageSignerEMMessageSignerTransformer = _Class(
    "MFMessageSignerEMMessageSignerTransformer"
)
MFMessageReferenceContext = _Class("MFMessageReferenceContext")
_MFPersistedMessageForwardingIterator = _Class("_MFPersistedMessageForwardingIterator")
MFMessageLoadingContextToEMSecurityInformationTransformer = _Class(
    "MFMessageLoadingContextToEMSecurityInformationTransformer"
)
MFMessageLoadingContext = _Class("MFMessageLoadingContext")
MFMessageLoadingContextEvent = _Class("MFMessageLoadingContextEvent")
MFMessageInfoOrderedSet = _Class("MFMessageInfoOrderedSet")
MFMessageInfo = _Class("MFMessageInfo")
MFMessageDetails = _Class("MFMessageDetails")
MFMessageCriterionConverter = _Class("MFMessageCriterionConverter")
_MFDASearchCriterionConverterDelegate = _Class("_MFDASearchCriterionConverterDelegate")
_MFMessageContentRequestScheduler = _Class("_MFMessageContentRequestScheduler")
MFMessageContentRequest = _Class("MFMessageContentRequest")
_MFLoadingContextEventResult = _Class("_MFLoadingContextEventResult")
MFMessageCollectionInfo = _Class("MFMessageCollectionInfo")
MFMessageBodyMigrator = _Class("MFMessageBodyMigrator")
MFMailMessageStoreSearchResult = _Class("MFMailMessageStoreSearchResult")
MFMailMessageLibraryThreadFlagColorsUpgradeStep = _Class(
    "MFMailMessageLibraryThreadFlagColorsUpgradeStep"
)
MFMailMessageLibrarySetThreadSendersRecipientsConflictResolutionUpgradeStep = _Class(
    "MFMailMessageLibrarySetThreadSendersRecipientsConflictResolutionUpgradeStep"
)
MFMailMessageLibraryResetSequenceNumberMigrationStep = _Class(
    "MFMailMessageLibraryResetSequenceNumberMigrationStep"
)
MFMailMessageLibraryRecreateMessageIndicesUpgradeStep = _Class(
    "MFMailMessageLibraryRecreateMessageIndicesUpgradeStep"
)
MFMailMessageLibraryRebuildThreadsTableUpgradeStep = _Class(
    "MFMailMessageLibraryRebuildThreadsTableUpgradeStep"
)
MFMailMessageLibraryQueryTransformer = _Class("MFMailMessageLibraryQueryTransformer")
MFMailMessageLibraryModifyColumnDefinitionsMigrationStep = _Class(
    "MFMailMessageLibraryModifyColumnDefinitionsMigrationStep"
)
MFMailMessageLibraryMigrator = _Class("MFMailMessageLibraryMigrator")
MFMailMessageLibraryMailboxURLMigrationStep = _Class(
    "MFMailMessageLibraryMailboxURLMigrationStep"
)
_MFOfflineCacheOperation = _Class("_MFOfflineCacheOperation")
_MFDADeferredSelectMailboxOperation = _Class("_MFDADeferredSelectMailboxOperation")
_MFDADeferredModifyMailboxOperation = _Class("_MFDADeferredModifyMailboxOperation")
_MFDADeferredDeleteMailboxOperation = _Class("_MFDADeferredDeleteMailboxOperation")
_MFDADeferredNewMailboxOperation = _Class("_MFDADeferredNewMailboxOperation")
MFDADeferredStoreDraftOperation = _Class("MFDADeferredStoreDraftOperation")
MFDADeferredMessageMoveOperation = _Class("MFDADeferredMessageMoveOperation")
_MFDADeferredDeleteMessageOperation = _Class("_MFDADeferredDeleteMessageOperation")
_MFDADeferredSetFlagsOperation = _Class("_MFDADeferredSetFlagsOperation")
MFMailMessageLibraryLocalActionsTablesMigrationStep = _Class(
    "MFMailMessageLibraryLocalActionsTablesMigrationStep"
)
MFMailMessageLibraryGlobalDataUpgradeStep = _Class(
    "MFMailMessageLibraryGlobalDataUpgradeStep"
)
MFMailMessageLibraryFixPopUidsUniquenessConstraintUpgradeStep = _Class(
    "MFMailMessageLibraryFixPopUidsUniquenessConstraintUpgradeStep"
)
MFMailMessageLibraryAdoptSharedSchemaMigrationStep = _Class(
    "MFMailMessageLibraryAdoptSharedSchemaMigrationStep"
)
MFMailMessageLibraryAddSearchableIndexTablesUpgradeStep = _Class(
    "MFMailMessageLibraryAddSearchableIndexTablesUpgradeStep"
)
MFMailMessageLibraryAddJournaledConversationIDDateReceivedUpgradeStep = _Class(
    "MFMailMessageLibraryAddJournaledConversationIDDateReceivedUpgradeStep"
)
MFMailDropMailParser = _Class("MFMailDropMailParser")
MFOutgoingMessageDelivery = _Class("MFOutgoingMessageDelivery")
MFMailDropMailDelivery = _Class("MFMailDropMailDelivery")
MFMailboxUidTransformer = _Class("MFMailboxUidTransformer")
MFMailboxProvider = _Class("MFMailboxProvider")
MFLockStateMonitor = _Class("MFLockStateMonitor")
MFLocalActionReplayHandler = _Class("MFLocalActionReplayHandler")
MFListUnsubscribeMessageGenerator_iOS = _Class("MFListUnsubscribeMessageGenerator_iOS")
MFLibraryThreadReconciler = _Class("MFLibraryThreadReconciler")
MFLibraryReconciler = _Class("MFLibraryReconciler")
MFLibraryMessageReconciler = _Class("MFLibraryMessageReconciler")
MFFileCompressionQueueActivityManager = _Class("MFFileCompressionQueueActivityManager")
MFFileCompressionQueue = _Class("MFFileCompressionQueue")
MFFileArchiveEntry = _Class("MFFileArchiveEntry")
MFFileArchiveDirectory = _Class("MFFileArchiveDirectory")
MFFileArchive = _Class("MFFileArchive")
MFFile = _Class("MFFile")
MFFetchLimits = _Class("MFFetchLimits")
MFFakeAccountsProvider = _Class("MFFakeAccountsProvider")
MFDeliveryResult = _Class("MFDeliveryResult")
MFDecryptedAttachmentDataProvider = _Class("MFDecryptedAttachmentDataProvider")
MFDebugAccountState = _Class("MFDebugAccountState")
MFDbJournal = _Class("MFDbJournal")
MFDATransferActionReplayer = _Class("MFDATransferActionReplayer")
MFDAStoreDraftConsumer = _Class("MFDAStoreDraftConsumer")
_MFDAMessageStoreSearchResultBodyConsumer = _Class(
    "_MFDAMessageStoreSearchResultBodyConsumer"
)
_MFDALibraryConsumerFactory = _Class("_MFDALibraryConsumerFactory")
_MFDAMessageBodyFetchConsumer = _Class("_MFDAMessageBodyFetchConsumer")
_MFDAMessageHeaderFetchConsumer = _Class("_MFDAMessageHeaderFetchConsumer")
MFDAMessageContentConsumer = _Class("MFDAMessageContentConsumer")
MFDAFolderChangeResult = _Class("MFDAFolderChangeResult")
MFDAFolderChangeConsumer = _Class("MFDAFolderChangeConsumer")
MFContentErrorDocument = _Class("MFContentErrorDocument")
MFComposeAttachmentDataProvider = _Class("MFComposeAttachmentDataProvider")
MFCertificateTrustInformationKeychainManager = _Class(
    "MFCertificateTrustInformationKeychainManager"
)
MFCertificateTrustInfoEMCertificateTrustInformationTransformer = _Class(
    "MFCertificateTrustInfoEMCertificateTrustInformationTransformer"
)
MFCertificateTrustInfo = _Class("MFCertificateTrustInfo")
MFAttachmentSecurityScope = _Class("MFAttachmentSecurityScope")
MFAttachmentBundle = _Class("MFAttachmentBundle")
MFAttachmentUtilities = _Class("MFAttachmentUtilities")
MFAttachmentRaw = _Class("MFAttachmentRaw")
MFAttachmentPlaceholder = _Class("MFAttachmentPlaceholder")
MFAttachmentLibraryDataProvider = _Class("MFAttachmentLibraryDataProvider")
MFMailDropAttachmentPreviewDataProvider = _Class(
    "MFMailDropAttachmentPreviewDataProvider"
)
MFMailDropAttachmentDataProvider = _Class("MFMailDropAttachmentDataProvider")
MFAttachmentDataProvider = _Class("MFAttachmentDataProvider")
MFAttachmentCompositionContext = _Class("MFAttachmentCompositionContext")
MFAttachmentManager = _Class("MFAttachmentManager")
MFAttachmentComposeManager = _Class("MFAttachmentComposeManager")
MFAttachmentLibraryManager = _Class("MFAttachmentLibraryManager")
MFAttachmentCapabilities = _Class("MFAttachmentCapabilities")
_MFAttachmentActiveRequest = _Class("_MFAttachmentActiveRequest")
MFAttachment = _Class("MFAttachment")
MFAppStateMonitor = _Class("MFAppStateMonitor")
MFActivityCondition = _Class("MFActivityCondition")
_MFSatisfiedActivityCondition = _Class("_MFSatisfiedActivityCondition")
MFAccountStore = _Class("MFAccountStore")
MFAccountLoader = _Class("MFAccountLoader")
MFAccountFactory_iOS = _Class("MFAccountFactory_iOS")
MFMessageWriter = _Class("MFMessageWriter")
MFMessageSigner = _Class("MFMessageSigner")
MFBasicMessageDataSection = _Class("MFBasicMessageDataSection")
_MFMessageFlags = _Class("_MFMessageFlags")
MFMessageCriterion = _Class("MFMessageCriterion")
MFMessageTransferResult = _Class("MFMessageTransferResult")
_MFAddableMessage = _Class("_MFAddableMessage")
_MFObjectProperty = _Class("_MFObjectProperty")
_MFRecipientCollection = _Class("_MFRecipientCollection")
_MFEmailAddress = _Class("_MFEmailAddress")
_MFDataCollector = _Class("_MFDataCollector")
_MFBlockIterationHandler = _Class("_MFBlockIterationHandler")
_MFMessageCollector = _Class("_MFMessageCollector")
_MFMailMessageLibraryStatistics = _Class("_MFMailMessageLibraryStatistics")
MFMessageLibrary = _Class("MFMessageLibrary")
MFMailMessageLibrary = _Class("MFMailMessageLibrary")
MFInvocationQueue = _Class("MFInvocationQueue")
_MFFormatFlowedWriter = _Class("_MFFormatFlowedWriter")
_MFDAResolveRecipientsConsumer = _Class("_MFDAResolveRecipientsConsumer")
MFDAMessagePayloadFetchResponseImpl = _Class("MFDAMessagePayloadFetchResponseImpl")
MFRequestQueue = _Class("MFRequestQueue")
MFDARequestQueue = _Class("MFDARequestQueue")
MFMailboxUid = _Class("MFMailboxUid")
MFFakeMailboxUid = _Class("MFFakeMailboxUid")
_MFRootlessMailboxUid = _Class("_MFRootlessMailboxUid")
MFDAMailbox = _Class("MFDAMailbox")
MFMailDelivery = _Class("MFMailDelivery")
MFSMTPDelivery = _Class("MFSMTPDelivery")
MFDADelivery = _Class("MFDADelivery")
MFDAMailAccountConsumer = _Class("MFDAMailAccountConsumer")
MFDAMoveResponseConsumer = _Class("MFDAMoveResponseConsumer")
_MFDAMessageFetchAttachmentConsumer = _Class("_MFDAMessageFetchAttachmentConsumer")
MFDAMailAccountSyncConsumer = _Class("MFDAMailAccountSyncConsumer")
MFDADeliveryConsumer = _Class("MFDADeliveryConsumer")
_MFSQLGenerationContext = _Class("_MFSQLGenerationContext")
_MFLoginAuthenticator = _Class("_MFLoginAuthenticator")
_MFPlainAuthenticator = _Class("_MFPlainAuthenticator")
_MFNTLMAuthenticator = _Class("_MFNTLMAuthenticator")
_MFDigestMD5Authenticator = _Class("_MFDigestMD5Authenticator")
MFCRAM_MD5Authenticator = _Class("MFCRAM_MD5Authenticator")
MFConnectionSettings = _Class("MFConnectionSettings")
MFConnection = _Class("MFConnection")
MFSMTPConnection = _Class("MFSMTPConnection")
MFBufferedQueue = _Class("MFBufferedQueue")
_MFDAMSBasicConsumer = _Class("_MFDAMSBasicConsumer")
_MFDAMSSearchResponseConsumer = _Class("_MFDAMSSearchResponseConsumer")
_MFDAMSUpdateConsumer = _Class("_MFDAMSUpdateConsumer")
MFPlainAuthScheme = _Class("MFPlainAuthScheme")
MFNTLMAuthScheme = _Class("MFNTLMAuthScheme")
MFDigestMD5AuthScheme = _Class("MFDigestMD5AuthScheme")
MFCRAM_MD5AuthScheme = _Class("MFCRAM_MD5AuthScheme")
MFAuthScheme = _Class("MFAuthScheme")
_MFActivityMonitorMultiTarget = _Class("_MFActivityMonitorMultiTarget")
MFAccountValidator = _Class("MFAccountValidator")
_MFAccountInformation = _Class("_MFAccountInformation")
MFAccount = _Class("MFAccount")
MailAccount = _Class("MailAccount")
MFFakeMailAccount = _Class("MFFakeMailAccount")
LocalAccount = _Class("LocalAccount")
DAMailAccount = _Class("DAMailAccount")
DeliveryAccount = _Class("DeliveryAccount")
SMTPAccount = _Class("SMTPAccount")
DADeliveryAccount = _Class("DADeliveryAccount")
MFMailMimeTextAttachment = _Class("MFMailMimeTextAttachment")
MFMailMimePart = _Class("MFMailMimePart")
_MFSecCMSEncoder = _Class("_MFSecCMSEncoder")
MFMailMessageStore = _Class("MFMailMessageStore")
MFLibraryStore = _Class("MFLibraryStore")
MFDAMessageStore = _Class("MFDAMessageStore")
_MFSecDataMessageStore = _Class("_MFSecDataMessageStore")
MFMailDataMessageStore = _Class("MFMailDataMessageStore")
MFLocalizedMessageHeaders = _Class("MFLocalizedMessageHeaders")
_MFOutgoingMessageBody = _Class("_MFOutgoingMessageBody")
MFMailMessage = _Class("MFMailMessage")
MFFakeMailMessage = _Class("MFFakeMailMessage")
MFDAMessage = _Class("MFDAMessage")
MFOutgoingMessage = _Class("MFOutgoingMessage")
MFLibraryMessage = _Class("MFLibraryMessage")
MFFakeLibraryMessage = _Class("MFFakeLibraryMessage")
MFActivityMonitor = _Class("MFActivityMonitor")
MFDADraftMessage = _Class("MFDADraftMessage")
MFDAMessageStoreSaveDraftRequest = _Class("MFDAMessageStoreSaveDraftRequest")
_MFDAMessageStoreFetchUsingRemoteIDRequest = _Class(
    "_MFDAMessageStoreFetchUsingRemoteIDRequest"
)
_MFDAMessageStoreFetchRequest = _Class("_MFDAMessageStoreFetchRequest")
_MFDAMessageStoreFetchHeadersRequest = _Class("_MFDAMessageStoreFetchHeadersRequest")
_MFDAMessageStoreDeleteRequest = _Class("_MFDAMessageStoreDeleteRequest")
_MFDAMessageStoreGetUpdatesRequest = _Class("_MFDAMessageStoreGetUpdatesRequest")
_MFDAMessageStoreSetFlagsRequest = _Class("_MFDAMessageStoreSetFlagsRequest")
MFServerMessagePersistenceFactory_iOS = _Class("MFServerMessagePersistenceFactory_iOS")
MFSearchableIndexPersistence_iOS = _Class("MFSearchableIndexPersistence_iOS")
MFSearchableIndexManager_iOS = _Class("MFSearchableIndexManager_iOS")
MFSearchableIndexItem_iOS = _Class("MFSearchableIndexItem_iOS")
MFSearchableIndex_iOS = _Class("MFSearchableIndex_iOS")
MFProtectedDatabasePersistence_iOS = _Class("MFProtectedDatabasePersistence_iOS")
MFPersistenceDatabaseSchema_iOS = _Class("MFPersistenceDatabaseSchema_iOS")
MFPersistenceDatabaseConnection_iOS = _Class("MFPersistenceDatabaseConnection_iOS")
MFPersistenceDatabase_iOS = _Class("MFPersistenceDatabase_iOS")
MFPersistence_iOS = _Class("MFPersistence_iOS")
_MFMessagePersistenceQueryIterator = _Class("_MFMessagePersistenceQueryIterator")
_MFMessageQueryConversionIterator = _Class("_MFMessageQueryConversionIterator")
MFMessagePersistence_iOS = _Class("MFMessagePersistence_iOS")
MFMessageChangeManager_iOS = _Class("MFMessageChangeManager_iOS")
MFMailboxPersistence_iOS = _Class("MFMailboxPersistence_iOS")
MFLocalActionPersistence_iOS = _Class("MFLocalActionPersistence_iOS")
MFMonitoredInvocation = _Class("MFMonitoredInvocation")
_MFMailboxUidChildrenEnumerator = _Class("_MFMailboxUidChildrenEnumerator")
_MFMailboxUidEnumerator = _Class("_MFMailboxUidEnumerator")
MFError = _Class("MFError")
