'''
Classes from the 'MetricsKit' framework.
'''

try:
    from rubicon.objc import ObjCClass
except ValueError:
    def ObjCClass(name):
        return None


def _Class(name):
    try:
        return ObjCClass(name)
    except NameError:
        return None

    
MTJSContextEventFilter = _Class('MTJSContextEventFilter')
MTPromise = _Class('MTPromise')
MTPromiseCompletionBlocks = _Class('MTPromiseCompletionBlocks')
MTPeriodicQueue = _Class('MTPeriodicQueue')
MTIDInfo = _Class('MTIDInfo')
MTIDCloudKitLocalDB = _Class('MTIDCloudKitLocalDB')
MTNumberUtil = _Class('MTNumberUtil')
MTPromiseResult = _Class('MTPromiseResult')
MTTreatmentProfile = _Class('MTTreatmentProfile')
MTKnownFieldMethod = _Class('MTKnownFieldMethod')
MTMediaActivityTracker = _Class('MTMediaActivityTracker')
MTNonretainedCache = _Class('MTNonretainedCache')
MTWeakRef = _Class('MTWeakRef')
MTMediaTimeTracker = _Class('MTMediaTimeTracker')
MTIDFileStore = _Class('MTIDFileStore')
MTInterprocessChangeNotifier = _Class('MTInterprocessChangeNotifier')
MTEnvironmentUIKitDelegate = _Class('MTEnvironmentUIKitDelegate')
MTEnvironmentUIKitStoreDelegate = _Class('MTEnvironmentUIKitStoreDelegate')
MTConvenienceEnvironmentDelegate = _Class('MTConvenienceEnvironmentDelegate')
MTIDCloudKitPromiseManager = _Class('MTIDCloudKitPromiseManager')
MTPAFPlaylistItem = _Class('MTPAFPlaylistItem')
MTPromiseWithTimeout = _Class('MTPromiseWithTimeout')
MTIDObserver = _Class('MTIDObserver')
MTHLSItem = _Class('MTHLSItem')
MTHLSRollItem = _Class('MTHLSRollItem')
MTPAFTracker = _Class('MTPAFTracker')
MTPAFPlaylistKitBinding = _Class('MTPAFPlaylistKitBinding')
MTIDConfig = _Class('MTIDConfig')
MTEventFieldsUtil = _Class('MTEventFieldsUtil')
MTTreatment = _Class('MTTreatment')
MTPAFItemActivity = _Class('MTPAFItemActivity')
MTCallerSuppliedFields = _Class('MTCallerSuppliedFields')
MTFrameworkEnvironment = _Class('MTFrameworkEnvironment')
MTIDCache = _Class('MTIDCache')
MTConfigAMSMetricsDelegate = _Class('MTConfigAMSMetricsDelegate')
MTMediaActivity = _Class('MTMediaActivity')
MTHLSVideoPlaylist = _Class('MTHLSVideoPlaylist')
MTPAFPlaylist = _Class('MTPAFPlaylist')
MTStandardIDService = _Class('MTStandardIDService')
MTPAFActivity = _Class('MTPAFActivity')
MTReflectUtil = _Class('MTReflectUtil')
MTMetricsKitTemplate = _Class('MTMetricsKitTemplate')
MTMetricsKit = _Class('MTMetricsKit')
MTPAFKit = _Class('MTPAFKit')
MTAPAFKit = _Class('MTAPAFKit')
MTVPAFKit = _Class('MTVPAFKit')
MTTreatmentAction = _Class('MTTreatmentAction')
MTHashAction = _Class('MTHashAction')
MTNumberDeresAction = _Class('MTNumberDeresAction')
MTURLDeresAction = _Class('MTURLDeresAction')
MTIDCompositeSecretStore = _Class('MTIDCompositeSecretStore')
MTUIKitStoreAMSBagDelegatePackage = _Class('MTUIKitStoreAMSBagDelegatePackage')
MTIDScheme = _Class('MTIDScheme')
MTIDCloudKitStore = _Class('MTIDCloudKitStore')
MTEventRecorderAMSMetricsDelegate = _Class('MTEventRecorderAMSMetricsDelegate')
MTObject = _Class('MTObject')
MTSystem = _Class('MTSystem')
MTFinalValidationFilter = _Class('MTFinalValidationFilter')
MTUtils = _Class('MTUtils')
MTMetricsUtils = _Class('MTMetricsUtils')
MTMetricsData = _Class('MTMetricsData')
MTConstraintTreatmentFilter = _Class('MTConstraintTreatmentFilter')
MTEventRecorder = _Class('MTEventRecorder')
MTEventHandlers = _Class('MTEventHandlers')
MTPAFEventHandlers = _Class('MTPAFEventHandlers')
MTMetricsEventHandlers = _Class('MTMetricsEventHandlers')
MTEventHandlerRegistration = _Class('MTEventHandlerRegistration')
MTConfig = _Class('MTConfig')
MTEventDataProvider = _Class('MTEventDataProvider')
MTEventHandler = _Class('MTEventHandler')
MTFlexibleEventHandler = _Class('MTFlexibleEventHandler')
MTMediaActivityEventHandler = _Class('MTMediaActivityEventHandler')
MTStandardEventHandler = _Class('MTStandardEventHandler')
MTDialogEventHandler = _Class('MTDialogEventHandler')
MTMediaEventHandler = _Class('MTMediaEventHandler')
MTImpressionableEventHandler = _Class('MTImpressionableEventHandler')
MTClickEventHandler = _Class('MTClickEventHandler')
MTImpressionsEventHandler = _Class('MTImpressionsEventHandler')
MTExitEventHandler = _Class('MTExitEventHandler')
MTSearchEventHandler = _Class('MTSearchEventHandler')
MTAccountEventHandler = _Class('MTAccountEventHandler')
MTEnterEventHandler = _Class('MTEnterEventHandler')
MTPageEventHandler = _Class('MTPageEventHandler')
MTBaseEventDataProvider = _Class('MTBaseEventDataProvider')
MTPAFBaseEventDataProvider = _Class('MTPAFBaseEventDataProvider')
MTMetricsBaseEventDataProvider = _Class('MTMetricsBaseEventDataProvider')
MTEnvironment = _Class('MTEnvironment')
MTTreatmentContext = _Class('MTTreatmentContext')
MTIDSecret = _Class('MTIDSecret')
MTMetricsDataPredicate = _Class('MTMetricsDataPredicate')
