'''
Classes from the 'SiriInstrumentation' framework.
'''

try:
    from rubicon.objc import ObjCClass
except ValueError:
    def ObjCClass(name):
        return None


def _Class(name):
    try:
        return ObjCClass(name)
    except NameError:
        return None

    
SISchemaVoiceTriggerMetrics = _Class('SISchemaVoiceTriggerMetrics')
SISchemaViewContainer = _Class('SISchemaViewContainer')
SISchemaUserViewRegionInteraction = _Class('SISchemaUserViewRegionInteraction')
SISchemaUserSpeechDuration = _Class('SISchemaUserSpeechDuration')
SISchemaUserDataContainer = _Class('SISchemaUserDataContainer')
SISchemaUUFRShown = _Class('SISchemaUUFRShown')
SISchemaUUFRSaid = _Class('SISchemaUUFRSaid')
SISchemaUUFRPresented = _Class('SISchemaUUFRPresented')
SISchemaUUFRFatalError = _Class('SISchemaUUFRFatalError')
SISchemaUUFRCompletion = _Class('SISchemaUUFRCompletion')
SISchemaUIStateTransition = _Class('SISchemaUIStateTransition')
SISchemaUIStatePresenting = _Class('SISchemaUIStatePresenting')
SISchemaUIStateDismissed = _Class('SISchemaUIStateDismissed')
SISchemaTurnInteraction = _Class('SISchemaTurnInteraction')
SISchemaTextToSpeechEnd = _Class('SISchemaTextToSpeechEnd')
SISchemaTextToSpeechBegin = _Class('SISchemaTextToSpeechBegin')
LTSchemaTask = _Class('LTSchemaTask')
LTSchemaTTSSpeechTranslationEvent = _Class('LTSchemaTTSSpeechTranslationEvent')
LTSchemaSpeechTranslationEvent = _Class('LTSchemaSpeechTranslationEvent')
SISchemaSpeechTranscription = _Class('SISchemaSpeechTranscription')
SISchemaSpeechResultSelected = _Class('SISchemaSpeechResultSelected')
SISchemaSiriUISettings = _Class('SISchemaSiriUISettings')
SISchemaSiriResponseContext = _Class('SISchemaSiriResponseContext')
SISchemaSiriCue = _Class('SISchemaSiriCue')
SIServiceServerUploadInfo = _Class('SIServiceServerUploadInfo')
SISchemaServerGeneratedDismissal = _Class('SISchemaServerGeneratedDismissal')
SISchemaServerEventMetadata = _Class('SISchemaServerEventMetadata')
SISchemaServerEvent = _Class('SISchemaServerEvent')
LTSchemaSafariFeedbackEvent = _Class('LTSchemaSafariFeedbackEvent')
SISchemaRedactableString = _Class('SISchemaRedactableString')
SISchemaRawSpeechProfileData = _Class('SISchemaRawSpeechProfileData')
SISchemaPunchOut = _Class('SISchemaPunchOut')
SISchemaPersonalization = _Class('SISchemaPersonalization')
PETSchemaPETUpload = _Class('PETSchemaPETUpload')
PETSchemaPETRawMessage = _Class('PETSchemaPETRawMessage')
PETSchemaPETMetadata = _Class('PETSchemaPETMetadata')
PETSchemaPETDistribution = _Class('PETSchemaPETDistribution')
PETSchemaPETAggregationKey = _Class('PETSchemaPETAggregationKey')
PETSchemaPETAggregatedMessage = _Class('PETSchemaPETAggregatedMessage')
PETSchemaPET1Key = _Class('PETSchemaPET1Key')
SISchemaMultiUserState = _Class('SISchemaMultiUserState')
LTSchemaMTSpeechTranslationEvent = _Class('LTSchemaMTSpeechTranslationEvent')
LTSchemaMTClientEvent = _Class('LTSchemaMTClientEvent')
LCServiceLoggingParameters = _Class('LCServiceLoggingParameters')
LCServiceLoggingConfiguration = _Class('LCServiceLoggingConfiguration')
SISchemaLocation = _Class('SISchemaLocation')
SISchemaLocaleIdentifier = _Class('SISchemaLocaleIdentifier')
LTSchemaLocaleConfidence = _Class('LTSchemaLocaleConfidence')
SISchemaLanguageProfile = _Class('SISchemaLanguageProfile')
LTSchemaLIDSpeechTranslationEvent = _Class('LTSchemaLIDSpeechTranslationEvent')
SISchemaInvocation = _Class('SISchemaInvocation')
SIServiceInstrumentationBatchResponse = _Class('SIServiceInstrumentationBatchResponse')
SIServiceInstrumentationBatch = _Class('SIServiceInstrumentationBatch')
SISchemaHomeKitAccessoryResponse = _Class('SISchemaHomeKitAccessoryResponse')
SISchemaHardwareInterfaceIdentifier = _Class('SISchemaHardwareInterfaceIdentifier')
LTSchemaError = _Class('LTSchemaError')
SISchemaEnrolledUserState = _Class('SISchemaEnrolledUserState')
SISchemaEnabledStatus = _Class('SISchemaEnabledStatus')
LTSchemaDisambiguationSpeechTranslationEvent = _Class('LTSchemaDisambiguationSpeechTranslationEvent')
SISchemaDictationTranscriptionMetadata = _Class('SISchemaDictationTranscriptionMetadata')
SISchemaDictationEndPointStop = _Class('SISchemaDictationEndPointStop')
SISchemaDictationEndPointCancel = _Class('SISchemaDictationEndPointCancel')
SISchemaDictationContext = _Class('SISchemaDictationContext')
SISchemaDictationAlternativesViewed = _Class('SISchemaDictationAlternativesViewed')
SISchemaDictationAlternativesPresent = _Class('SISchemaDictationAlternativesPresent')
SISchemaDictationAlternativeSelected = _Class('SISchemaDictationAlternativeSelected')
SISchemaDialogOutput = _Class('SISchemaDialogOutput')
SIServiceDeviceUploadInfo = _Class('SIServiceDeviceUploadInfo')
SISchemaDeviceFixedContext = _Class('SISchemaDeviceFixedContext')
SISchemaDeviceDynamicContext = _Class('SISchemaDeviceDynamicContext')
SISchemaDailyDeviceStatus = _Class('SISchemaDailyDeviceStatus')
SISchemaConversationTrace = _Class('SISchemaConversationTrace')
LCServiceConfigurationResponse = _Class('LCServiceConfigurationResponse')
LCServiceConfigurationRequest = _Class('LCServiceConfigurationRequest')
SISchemaClientTransportEventMetadata = _Class('SISchemaClientTransportEventMetadata')
SISchemaClientFlow = _Class('SISchemaClientFlow')
SISchemaClientEventMetadata = _Class('SISchemaClientEventMetadata')
SISchemaClientEvent = _Class('SISchemaClientEvent')
LCServiceCategoryConfiguration = _Class('LCServiceCategoryConfiguration')
SISchemaCasinoRelationship = _Class('SISchemaCasinoRelationship')
SISchemaCarPlayInvocationContext = _Class('SISchemaCarPlayInvocationContext')
SISchemaCarPlayHeadUnitContext = _Class('SISchemaCarPlayHeadUnitContext')
LCServiceBlacklistedFields = _Class('LCServiceBlacklistedFields')
LCServiceBlackListedField = _Class('LCServiceBlackListedField')
LTSchemaBatchTranslationEvent = _Class('LTSchemaBatchTranslationEvent')
SIServiceBatchInfo = _Class('SIServiceBatchInfo')
SISchemaAudioStopRecording = _Class('SISchemaAudioStopRecording')
SISchemaAudioFirstBufferRecorded = _Class('SISchemaAudioFirstBufferRecorded')
LCServiceApplicationConfiguration = _Class('LCServiceApplicationConfiguration')
SISchemaAnyEvent = _Class('SISchemaAnyEvent')
SISchemaAggregatedMetrics = _Class('SISchemaAggregatedMetrics')
SISchemaActiveStatus = _Class('SISchemaActiveStatus')
SISchemaActiveAudioDevice = _Class('SISchemaActiveAudioDevice')
SISchemaAcousticProfile = _Class('SISchemaAcousticProfile')
LTSchemaASRSpeechTranslationEvent = _Class('LTSchemaASRSpeechTranslationEvent')
