"""
Classes from the 'UIFoundation' framework.
"""

try:
    from rubicon.objc import ObjCClass
except ValueError:

    def ObjCClass(name):
        return None


def _Class(name):
    try:
        return ObjCClass(name)
    except NameError:
        return None


NSTextSelection = _Class("NSTextSelection")
_NSTextAttachmentLayoutContext = _Class("_NSTextAttachmentLayoutContext")
NSRTFWriter = _Class("NSRTFWriter")
NSHTMLWriter = _Class("NSHTMLWriter")
NSSubstituteWebResource = _Class("NSSubstituteWebResource")
NSTextCorrectionMarkerRendering = _Class("NSTextCorrectionMarkerRendering")
NSRTFReader = _Class("NSRTFReader")
NSRTFReaderTableState = _Class("NSRTFReaderTableState")
NSTextAttachmentViewProvider = _Class("NSTextAttachmentViewProvider")
_NSTextViewportLayoutObserver = _Class("_NSTextViewportLayoutObserver")
NSTextViewportLayoutController = _Class("NSTextViewportLayoutController")
UIPointFIFO = _Class("UIPointFIFO")
UIQuadCurvePointFIFO = _Class("UIQuadCurvePointFIFO")
UIBoxcarFilterPointFIFO = _Class("UIBoxcarFilterPointFIFO")
_UIPointVector = _Class("_UIPointVector")
NSTextBlock = _Class("NSTextBlock")
NSTextTable = _Class("NSTextTable")
NSTextTableBlock = _Class("NSTextTableBlock")
NSTextBlockLayoutHelper = _Class("NSTextBlockLayoutHelper")
_NSTextRunStorage = _Class("_NSTextRunStorage")
NSTextList = _Class("NSTextList")
NSStringDrawingTextStorageSettings = _Class("NSStringDrawingTextStorageSettings")
NSTextContentManager = _Class("NSTextContentManager")
NSTextContentStorage = _Class("NSTextContentStorage")
NSTextLineFragment = _Class("NSTextLineFragment")
NSCountableTextLocation = _Class("NSCountableTextLocation")
NSTextRange = _Class("NSTextRange")
NSCountableTextRange = _Class("NSCountableTextRange")
NSLayoutManagerTextBlockRowArrayCache = _Class("NSLayoutManagerTextBlockRowArrayCache")
NSLayoutManagerTextBlockHelper = _Class("NSLayoutManagerTextBlockHelper")
NSTextElement = _Class("NSTextElement")
NSTextParagraph = _Class("NSTextParagraph")
NSGlyphInfo = _Class("NSGlyphInfo")
NSCTGlyphInfo = _Class("NSCTGlyphInfo")
NSCIDGlyphInfo = _Class("NSCIDGlyphInfo")
NSIdentityGlyphInfo = _Class("NSIdentityGlyphInfo")
NSGlyphNameGlyphInfo = _Class("NSGlyphNameGlyphInfo")
_NSAttributeRun = _Class("_NSAttributeRun")
_NSAttributes = _Class("_NSAttributes")
_NSCGTextGraphicsContext = _Class("_NSCGTextGraphicsContext")
UINibCoderValue = _Class("UINibCoderValue")
NSTextLayoutManager = _Class("NSTextLayoutManager")
NSTextSelectionNavigation = _Class("NSTextSelectionNavigation")
__NSTextSelectionLineFragmentInfo = _Class("__NSTextSelectionLineFragmentInfo")
NSLineFragmentRenderingContext = _Class("NSLineFragmentRenderingContext")
NSTextLayoutFragment = _Class("NSTextLayoutFragment")
NSHTMLWebDelegate = _Class("NSHTMLWebDelegate")
NSHTMLReader = _Class("NSHTMLReader")
NSTextAlternatives = _Class("NSTextAlternatives")
__NSTextAppearanceEffectContext = _Class("__NSTextAppearanceEffectContext")
_NSUIKitTextGraphicsContext = _Class("_NSUIKitTextGraphicsContext")
_NSStandardTextGraphicsContextProvider = _Class(
    "_NSStandardTextGraphicsContextProvider"
)
NSTextGraphicsContextProvider = _Class("NSTextGraphicsContextProvider")
NSTextAttachment = _Class("NSTextAttachment")
NSTextTab = _Class("NSTextTab")
NSDataAsset = _Class("NSDataAsset")
NSInsertionPointHelper = _Class("NSInsertionPointHelper")
_NSCoreTypesetterLayoutCache = _Class("_NSCoreTypesetterLayoutCache")
NSATSGlyphStorage = _Class("NSATSGlyphStorage")
NSATSLineFragment = _Class("NSATSLineFragment")
NSGlyphGenerator = _Class("NSGlyphGenerator")
_NSATSTypesetterGuts = _Class("_NSATSTypesetterGuts")
NSTextContainer = _Class("NSTextContainer")
NSParagraphArbitrator = _Class("NSParagraphArbitrator")
NSExtraLMData = _Class("NSExtraLMData")
NSRunStorage = _Class("NSRunStorage")
NSIdRunStorage = _Class("NSIdRunStorage")
NSStorage = _Class("NSStorage")
_NSTextStorageSideData = _Class("_NSTextStorageSideData")
UINibStringIDTable = _Class("UINibStringIDTable")
NSLayoutManager = _Class("NSLayoutManager")
NSTypesetter = _Class("NSTypesetter")
NSATSTypesetter = _Class("NSATSTypesetter")
NSSingleLineTypesetter = _Class("NSSingleLineTypesetter")
NSCoreTypesetter = _Class("NSCoreTypesetter")
NSStringDrawingContext = _Class("NSStringDrawingContext")
NSShadow = _Class("NSShadow")
NSParagraphStyleExtraData = _Class("NSParagraphStyleExtraData")
__NSFontExtraData = _Class("__NSFontExtraData")
UIFontDescriptor = _Class("UIFontDescriptor")
UICTFontDescriptor = _Class("UICTFontDescriptor")
_UIFontCacheKey = _Class("_UIFontCacheKey")
_UIFontDescriptorCacheKey = _Class("_UIFontDescriptorCacheKey")
_UIFontTextStyleCacheKey = _Class("_UIFontTextStyleCacheKey")
_UIFontNameCacheKey = _Class("_UIFontNameCacheKey")
_UIFontSystemCacheKey = _Class("_UIFontSystemCacheKey")
UIFont = _Class("UIFont")
NSFont = _Class("NSFont")
UICTFont = _Class("UICTFont")
_UICache = _Class("_UICache")
NSParagraphStyle = _Class("NSParagraphStyle")
NSMutableParagraphStyle = _Class("NSMutableParagraphStyle")
UINibEncoder = _Class("UINibEncoder")
UINibDecoder = _Class("UINibDecoder")
NSAttributeDictionaryEnumerator = _Class("NSAttributeDictionaryEnumerator")
_NSCachedAttributedString = _Class("_NSCachedAttributedString")
NSConcreteNotifyingMutableAttributedString = _Class(
    "NSConcreteNotifyingMutableAttributedString"
)
NSTextStorage = _Class("NSTextStorage")
__NSImmutableTextStorage = _Class("__NSImmutableTextStorage")
NSConcreteTextStorage = _Class("NSConcreteTextStorage")
NSStringDrawingTextStorage = _Class("NSStringDrawingTextStorage")
__NSATSStringSegment = _Class("__NSATSStringSegment")
NSAttributeDictionary = _Class("NSAttributeDictionary")
NSTempAttributeDictionary = _Class("NSTempAttributeDictionary")
