"""
Classes from the 'CoreFoundation' framework.
"""

try:
    from rubicon.objc import ObjCClass
except ValueError:

    def ObjCClass(name):
        return None


def _Class(name):
    try:
        return ObjCClass(name)
    except NameError:
        return None


__NSMessageBuilder = _Class("__NSMessageBuilder")
_NSZombie_ = _Class("_NSZombie_")
__NSAtom = _Class("__NSAtom")
__NSGenericDeallocHandler = _Class("__NSGenericDeallocHandler")
_CFPrefsPendingKVONotification = _Class("_CFPrefsPendingKVONotification")
NSFileSecurity = _Class("NSFileSecurity")
__NSPlaceholderFileSecurity = _Class("__NSPlaceholderFileSecurity")
__NSFileSecurity = _Class("__NSFileSecurity")
NSException = _Class("NSException")
_NSSharedKeySetS = _Class("_NSSharedKeySetS")
_NSJapaneseBigramKeySet = _Class("_NSJapaneseBigramKeySet")
__NSWindows1252TrigramKeySet = _Class("__NSWindows1252TrigramKeySet")
__NSISOLatin2TrigramKeySet = _Class("__NSISOLatin2TrigramKeySet")
_NSKoreanBigramKeySet_SKS = _Class("_NSKoreanBigramKeySet_SKS")
__NSISO88596TrigramKeySet = _Class("__NSISO88596TrigramKeySet")
__NSISOLatin6TrigramKeySet = _Class("__NSISOLatin6TrigramKeySet")
__NSISOLatin3TrigramKeySet = _Class("__NSISOLatin3TrigramKeySet")
__NSISOLatin1TrigramKeySet = _Class("__NSISOLatin1TrigramKeySet")
__NSISOLatin4TrigramKeySet = _Class("__NSISOLatin4TrigramKeySet")
__NSWindows1250TrigramKeySet = _Class("__NSWindows1250TrigramKeySet")
__NSWindows1254TrigramKeySet = _Class("__NSWindows1254TrigramKeySet")
__NSISO88598TrigramKeySet = _Class("__NSISO88598TrigramKeySet")
__NSISO885911TrigramKeySet = _Class("__NSISO885911TrigramKeySet")
__NSISO88597TrigramKeySet = _Class("__NSISO88597TrigramKeySet")
__NSWindows1251TrigramKeySet = _Class("__NSWindows1251TrigramKeySet")
_NSKoreanBigramKeySet = _Class("_NSKoreanBigramKeySet")
_NSChineseBigramKeySet = _Class("_NSChineseBigramKeySet")
__NSWindows1255TrigramKeySet = _Class("__NSWindows1255TrigramKeySet")
__NSWindows1253TrigramKeySet = _Class("__NSWindows1253TrigramKeySet")
_NSMostCommonJapaneseCharsKeySet = _Class("_NSMostCommonJapaneseCharsKeySet")
__NSISO88595TrigramKeySet = _Class("__NSISO88595TrigramKeySet")
__NSISOLatin9TrigramKeySet = _Class("__NSISOLatin9TrigramKeySet")
_NSMostCommonChineseCharsKeySet = _Class("_NSMostCommonChineseCharsKeySet")
__NSISOLatin5TrigramKeySet = _Class("__NSISOLatin5TrigramKeySet")
_NSMostCommonKoreanCharsKeySet = _Class("_NSMostCommonKoreanCharsKeySet")
__NSWindows1258TrigramKeySet = _Class("__NSWindows1258TrigramKeySet")
__NSWindows1256TrigramKeySet = _Class("__NSWindows1256TrigramKeySet")
__NSWindows1257TrigramKeySet = _Class("__NSWindows1257TrigramKeySet")
__NSWindows874TrigramKeySet = _Class("__NSWindows874TrigramKeySet")
__NSISOLatin8TrigramKeySet = _Class("__NSISOLatin8TrigramKeySet")
_NSChineseBigramKeySet_SKS_SKS = _Class("_NSChineseBigramKeySet_SKS_SKS")
__NSISOLatin10TrigramKeySet = _Class("__NSISOLatin10TrigramKeySet")
__NSISOLatin7TrigramKeySet = _Class("__NSISOLatin7TrigramKeySet")
_NSChineseBigramKeySet_SKS = _Class("_NSChineseBigramKeySet_SKS")
_NSRefcountedPthreadMutex = _Class("_NSRefcountedPthreadMutex")
CFPDDataBuffer = _Class("CFPDDataBuffer")
CFPDCFDataBuffer = _Class("CFPDCFDataBuffer")
CFPDPurgeableBuffer = _Class("CFPDPurgeableBuffer")
CFPDSource = _Class("CFPDSource")
CFPDContainerSource = _Class("CFPDContainerSource")
CFPDCloudSource = _Class("CFPDCloudSource")
_CFStreamDelegate = _Class("_CFStreamDelegate")
__NSSKGraphE = _Class("__NSSKGraphE")
__NSBlockVariable = _Class("__NSBlockVariable")
_CFPrefsSynchronizer = _Class("_CFPrefsSynchronizer")
CFPDSourceLookUpKey = _Class("CFPDSourceLookUpKey")
_CFPrefsClientContext = _Class("_CFPrefsClientContext")
CFPrefsDaemon = _Class("CFPrefsDaemon")
__CFPrefsWeakObservers = _Class("__CFPrefsWeakObservers")
NSDateComponents = _Class("NSDateComponents")
NSInvocation = _Class("NSInvocation")
NSBlockInvocation = _Class("NSBlockInvocation")
__NSSKGraph = _Class("__NSSKGraph")
NSSharedKeySet = _Class("NSSharedKeySet")
NSCache = _Class("NSCache")
_NSMoribundCache = _Class("_NSMoribundCache")
NSTaggedPointerStringCStringContainer = _Class("NSTaggedPointerStringCStringContainer")
NSMethodSignature = _Class("NSMethodSignature")
NSRunLoop = _Class("NSRunLoop")
NSUserDefaults = _Class("NSUserDefaults")
CFPrefsSource = _Class("CFPrefsSource")
CFPrefsConfigurationFileSource = _Class("CFPrefsConfigurationFileSource")
CFPrefsPlistSource = _Class("CFPrefsPlistSource")
CFPrefsCloudSource = _Class("CFPrefsCloudSource")
CFPrefsManagedSource = _Class("CFPrefsManagedSource")
CFPrefsSearchListSource = _Class("CFPrefsSearchListSource")
CFPrefsSuiteSearchListSource = _Class("CFPrefsSuiteSearchListSource")
_CFXPreferences = _Class("_CFXPreferences")
_CFXPreferencesHandle = _Class("_CFXPreferencesHandle")
NSEnumerator = _Class("NSEnumerator")
__NSSingleObjectEnumerator = _Class("__NSSingleObjectEnumerator")
__NSConstantArrayEnumerator = _Class("__NSConstantArrayEnumerator")
__NSConstantDictionaryEnumerator = _Class("__NSConstantDictionaryEnumerator")
__NSArrayReverseEnumerator = _Class("__NSArrayReverseEnumerator")
__NSFastEnumerationEnumerator = _Class("__NSFastEnumerationEnumerator")
__NSDictionaryObjectEnumerator = _Class("__NSDictionaryObjectEnumerator")
__NSOrderedSetReverseEnumerator = _Class("__NSOrderedSetReverseEnumerator")
__NSEnumerator0 = _Class("__NSEnumerator0")
__CFNotification = _Class("__CFNotification")
__NSCFAttributedString = _Class("__NSCFAttributedString")
__NSCFCharacterSet = _Class("__NSCFCharacterSet")
__NSCFError = _Class("__NSCFError")
NSTaggedPointerString = _Class("NSTaggedPointerString")
__NSCFString = _Class("__NSCFString")
__NSCFConstantString = _Class("__NSCFConstantString")
NSBlock = _Class("NSBlock")
__NSStackBlock = _Class("__NSStackBlock")
__NSMallocBlock = _Class("__NSMallocBlock")
__NSAutoBlock = _Class("__NSAutoBlock")
__NSFinalizingBlock = _Class("__NSFinalizingBlock")
__NSGlobalBlock = _Class("__NSGlobalBlock")
NSStream = _Class("NSStream")
NSOutputStream = _Class("NSOutputStream")
__NSCFOutputStream = _Class("__NSCFOutputStream")
NSInputStream = _Class("NSInputStream")
__NSCFInputStream = _Class("__NSCFInputStream")
NSCalendar = _Class("NSCalendar")
_NSAutoCalendar = _Class("_NSAutoCalendar")
_NSCopyOnWriteCalendarWrapper = _Class("_NSCopyOnWriteCalendarWrapper")
__NSCFCalendar = _Class("__NSCFCalendar")
NSLocale = _Class("NSLocale")
_NSPlaceholderLocale = _Class("_NSPlaceholderLocale")
__NSCFLocale = _Class("__NSCFLocale")
NSTimer = _Class("NSTimer")
__NSCFTimer = _Class("__NSCFTimer")
NSURL = _Class("NSURL")
NSNull = _Class("NSNull")
__NSCFType = _Class("__NSCFType")
NSData = _Class("NSData")
NSConstantData = _Class("NSConstantData")
NSMutableData = _Class("NSMutableData")
__NSCFData = _Class("__NSCFData")
NSCFData = _Class("NSCFData")
__NSCFNumber = _Class("__NSCFNumber")
__NSCFBoolean = _Class("__NSCFBoolean")
NSOrderedSet = _Class("NSOrderedSet")
__NSOrderedSetReversed = _Class("__NSOrderedSetReversed")
__NSFrozenOrderedSetM = _Class("__NSFrozenOrderedSetM")
__NSOrderedSetI = _Class("__NSOrderedSetI")
NSMutableOrderedSet = _Class("NSMutableOrderedSet")
__NSOrderedSetM = _Class("__NSOrderedSetM")
__NSPlaceholderOrderedSet = _Class("__NSPlaceholderOrderedSet")
NSTimeZone = _Class("NSTimeZone")
__NSTimeZone = _Class("__NSTimeZone")
__NSLocalTimeZone = _Class("__NSLocalTimeZone")
__NSLocalTimeZoneI = _Class("__NSLocalTimeZoneI")
__NSPlaceholderTimeZone = _Class("__NSPlaceholderTimeZone")
NSDate = _Class("NSDate")
__NSDate = _Class("__NSDate")
__NSTaggedDate = _Class("__NSTaggedDate")
NSConstantDate = _Class("NSConstantDate")
__NSPlaceholderDate = _Class("__NSPlaceholderDate")
NSDictionary = _Class("NSDictionary")
__NSSingleEntryDictionaryI = _Class("__NSSingleEntryDictionaryI")
__NSDictionaryI = _Class("__NSDictionaryI")
__NSFrozenDictionaryM = _Class("__NSFrozenDictionaryM")
NSMutableDictionary = _Class("NSMutableDictionary")
NSSharedKeyDictionary = _Class("NSSharedKeyDictionary")
__NSDictionaryM = _Class("__NSDictionaryM")
__NSCFDictionary = _Class("__NSCFDictionary")
NSCFDictionary = _Class("NSCFDictionary")
__NSPlaceholderDictionary = _Class("__NSPlaceholderDictionary")
NSConstantDictionary = _Class("NSConstantDictionary")
__NSDictionary0 = _Class("__NSDictionary0")
NSSet = _Class("NSSet")
__NSOrderedSetSetProxy = _Class("__NSOrderedSetSetProxy")
__NSFrozenSetM = _Class("__NSFrozenSetM")
__NSSingleObjectSetI = _Class("__NSSingleObjectSetI")
__NSSetI = _Class("__NSSetI")
NSMutableSet = _Class("NSMutableSet")
__NSSetM = _Class("__NSSetM")
__NSCFSet = _Class("__NSCFSet")
__NSPlaceholderSet = _Class("__NSPlaceholderSet")
NSArray = _Class("NSArray")
__NSArrayReversed = _Class("__NSArrayReversed")
__NSOrderedSetArrayProxy = _Class("__NSOrderedSetArrayProxy")
__NSFrozenArrayM = _Class("__NSFrozenArrayM")
__NSArrayI_Transfer = _Class("__NSArrayI_Transfer")
__NSArrayI = _Class("__NSArrayI")
__NSSingleObjectArrayI = _Class("__NSSingleObjectArrayI")
NSConstantArray = _Class("NSConstantArray")
NSMutableArray = _Class("NSMutableArray")
__NSArrayM = _Class("__NSArrayM")
__NSCFArray = _Class("__NSCFArray")
NSCFArray = _Class("NSCFArray")
__NSPlaceholderArray = _Class("__NSPlaceholderArray")
__NSArray0 = _Class("__NSArray0")
