"""
Classes from the 'CoreMotion' framework.
"""

try:
    from rubicon.objc import ObjCClass
except ValueError:

    def ObjCClass(name):
        return None


def _Class(name):
    try:
        return ObjCClass(name)
    except NameError:
        return None


CMWorkoutManager = _Class("CMWorkoutManager")
CMWorkoutManagerInternal = _Class("CMWorkoutManagerInternal")
CMKappa = _Class("CMKappa")
CMKappaInternal = _Class("CMKappaInternal")
CLNotifierClientAdapter = _Class("CLNotifierClientAdapter")
CMOnBodyStatusManager = _Class("CMOnBodyStatusManager")
CMFitnessMachineData = _Class("CMFitnessMachineData")
CLPropertyValue = _Class("CLPropertyValue")
CMSwimData = _Class("CMSwimData")
CMMetMinute = _Class("CMMetMinute")
CMStrideCalibrationEntry = _Class("CMStrideCalibrationEntry")
CMStrideCalibrationEntryInternal = _Class("CMStrideCalibrationEntryInternal")
CMWorkoutMetsData = _Class("CMWorkoutMetsData")
CMMotionAlarm = _Class("CMMotionAlarm")
CMSwimTracker = _Class("CMSwimTracker")
CMSwimTrackerInternal = _Class("CMSwimTrackerInternal")
CMElevation = _Class("CMElevation")
CMAltimeter = _Class("CMAltimeter")
CMAltimeterInternal = _Class("CMAltimeterInternal")
CMFitnessShared = _Class("CMFitnessShared")
CMDeviceMotionLite = _Class("CMDeviceMotionLite")
CMStepCounter = _Class("CMStepCounter")
CMStepCounterProxy = _Class("CMStepCounterProxy")
CMActivityAlarm = _Class("CMActivityAlarm")
CMVehicleConnection = _Class("CMVehicleConnection")
CMVehicleConnectionData = _Class("CMVehicleConnectionData")
CMActivityAlarmProxy = _Class("CMActivityAlarmProxy")
CMPoseInternal = _Class("CMPoseInternal")
CMMotionUtils = _Class("CMMotionUtils")
CLHealthAssessmentRecordTypeForDuration = _Class(
    "CLHealthAssessmentRecordTypeForDuration"
)
CMTremorResult = _Class("CMTremorResult")
CMDyskineticSymptomResult = _Class("CMDyskineticSymptomResult")
CMPedometerBin = _Class("CMPedometerBin")
CMHeadphoneMotionManager = _Class("CMHeadphoneMotionManager")
CMHeadphoneMotionManagerInternal = _Class("CMHeadphoneMotionManagerInternal")
CMSkiData = _Class("CMSkiData")
CMWorkoutMets = _Class("CMWorkoutMets")
CMWorkoutMetsInternal = _Class("CMWorkoutMetsInternal")
CMCatherineFeeder = _Class("CMCatherineFeeder")
CMCatherineFeederInternal = _Class("CMCatherineFeederInternal")
CMSkiTracker = _Class("CMSkiTracker")
CMSkiTrackerInternal = _Class("CMSkiTrackerInternal")
CMFall = _Class("CMFall")
CMSleepData = _Class("CMSleepData")
CMPocketStateManager = _Class("CMPocketStateManager")
CMPocketStateQueueBlockPair = _Class("CMPocketStateQueueBlockPair")
CMDeviceOrientationManager = _Class("CMDeviceOrientationManager")
CMDeviceOrientationManagerInternal = _Class("CMDeviceOrientationManagerInternal")
CMPedometerEvent = _Class("CMPedometerEvent")
CMPedometerData = _Class("CMPedometerData")
CMPickupManager = _Class("CMPickupManager")
CMAnomalyMessenger = _Class("CMAnomalyMessenger")
CLSensorRecorderSensorSampleRate = _Class("CLSensorRecorderSensorSampleRate")
CLSensorRecorderSensorAvailable = _Class("CLSensorRecorderSensorAvailable")
CLSensorRecorderWriteSensorDataToFileForDateRange = _Class(
    "CLSensorRecorderWriteSensorDataToFileForDateRange"
)
CLSensorRecorderRecordSensorTypeFor = _Class("CLSensorRecorderRecordSensorTypeFor")
CLSensorRecorderSensorDataRequestById = _Class("CLSensorRecorderSensorDataRequestById")
CLSensorRecorderSensorMetaRequestByDateRange = _Class(
    "CLSensorRecorderSensorMetaRequestByDateRange"
)
CLSensorRecorderSensorMetaRequestById = _Class("CLSensorRecorderSensorMetaRequestById")
CLSensorRecorderSensorMeta = _Class("CLSensorRecorderSensorMeta")
CLLocationInternalClient_CoreMotion = _Class("CLLocationInternalClient_CoreMotion")
CMFitnessMachine = _Class("CMFitnessMachine")
CMFitnessMachineInternal = _Class("CMFitnessMachineInternal")
CMStrideCalibrationData = _Class("CMStrideCalibrationData")
CMOdometerData = _Class("CMOdometerData")
CMAnomalyEvent = _Class("CMAnomalyEvent")
CMPedometer = _Class("CMPedometer")
CMPedometerProxy = _Class("CMPedometerProxy")
CMActivityManager = _Class("CMActivityManager")
CMActivityManagerInternal = _Class("CMActivityManagerInternal")
CMGestureManager = _Class("CMGestureManager")
CMGestureManagerInternal = _Class("CMGestureManagerInternal")
CMElevationData = _Class("CMElevationData")
CLDeviceMotionProperties = _Class("CLDeviceMotionProperties")
CMHealthTracker = _Class("CMHealthTracker")
CMHealthTrackerInternal = _Class("CMHealthTrackerInternal")
CMAudioAccessoryManager = _Class("CMAudioAccessoryManager")
CMAudioAccessoryManagerInternal = _Class("CMAudioAccessoryManagerInternal")
CMAnomalyManager = _Class("CMAnomalyManager")
CMMagnetometerDataInternal = _Class("CMMagnetometerDataInternal")
CMOdometerSuitabilityManager = _Class("CMOdometerSuitabilityManager")
CMOdometerSuitabilityManagerProxy = _Class("CMOdometerSuitabilityManagerProxy")
CMNatalimeter = _Class("CMNatalimeter")
CMNatalimeterInternal = _Class("CMNatalimeterInternal")
CMMotionAlarmManager = _Class("CMMotionAlarmManager")
CMMotionAlarmManagerInternal = _Class("CMMotionAlarmManagerInternal")
CMErrorUtils = _Class("CMErrorUtils")
CMExerciseMinute = _Class("CMExerciseMinute")
CMExerciseMinuteInternal = _Class("CMExerciseMinuteInternal")
CMSedentaryTimerData = _Class("CMSedentaryTimerData")
CMCallHandednessManager = _Class("CMCallHandednessManager")
CMVO2MaxInputs = _Class("CMVO2MaxInputs")
CMSleepTracker = _Class("CMSleepTracker")
CMSpringTrackerInternal = _Class("CMSpringTrackerInternal")
CMMediaSession = _Class("CMMediaSession")
CMMotionManager = _Class("CMMotionManager")
CMMotionManagerInternal = _Class("CMMotionManagerInternal")
CMGyroDataInternal = _Class("CMGyroDataInternal")
CMRotationRateDataInternal = _Class("CMRotationRateDataInternal")
CMExerciseMinuteData = _Class("CMExerciseMinuteData")
CMOdometer = _Class("CMOdometer")
CMOdometerProxy = _Class("CMOdometerProxy")
CMOdometerSuitability = _Class("CMOdometerSuitability")
CMWakeGestureManager = _Class("CMWakeGestureManager")
CMLogItemInternal = _Class("CMLogItemInternal")
CMSensorRecorder = _Class("CMSensorRecorder")
CMSensorRecorderInternal = _Class("CMSensorRecorderInternal")
CMSensorDataList = _Class("CMSensorDataList")
CMAmbientPressureDataInternal = _Class("CMAmbientPressureDataInternal")
RMConnectionClient = _Class("RMConnectionClient")
RMConnectionClientCachedMessage = _Class("RMConnectionClientCachedMessage")
CMAttitude = _Class("CMAttitude")
CMAttitudeInternal = _Class("CMAttitudeInternal")
CMDeviceMotionInternal = _Class("CMDeviceMotionInternal")
CMWorkout = _Class("CMWorkout")
CMGenericWorkout = _Class("CMGenericWorkout")
CMFitnessMachineWorkout = _Class("CMFitnessMachineWorkout")
CMSwimWorkout = _Class("CMSwimWorkout")
CMFallStats = _Class("CMFallStats")
CMFallStatsItemsIterator = _Class("CMFallStatsItemsIterator")
RMConnectionEndpoint = _Class("RMConnectionEndpoint")
CMVehicleState = _Class("CMVehicleState")
CMVehicleStateData = _Class("CMVehicleStateData")
CMSignificantElevationSample = _Class("CMSignificantElevationSample")
CMAltitudeDataInternal = _Class("CMAltitudeDataInternal")
CMStrideCalibrationHistory = _Class("CMStrideCalibrationHistory")
CMAccelerometerDataInternal = _Class("CMAccelerometerDataInternal")
CMLogItem = _Class("CMLogItem")
CMOnBodyStatus = _Class("CMOnBodyStatus")
CMPose = _Class("CMPose")
CMHeartRateData = _Class("CMHeartRateData")
CMKappaData = _Class("CMKappaData")
CMDeviceOrientation = _Class("CMDeviceOrientation")
CMMotionActivity = _Class("CMMotionActivity")
CMActivity = _Class("CMActivity")
CMMagnetometerData = _Class("CMMagnetometerData")
CMCalorieUserInfo = _Class("CMCalorieUserInfo")
CMMotionTimeRange = _Class("CMMotionTimeRange")
CMCatherineData = _Class("CMCatherineData")
CMRotationRateData = _Class("CMRotationRateData")
CMRecordedRotationRateData = _Class("CMRecordedRotationRateData")
CMGyroData = _Class("CMGyroData")
CMRecordedGyroData = _Class("CMRecordedGyroData")
CMAmbientPressureData = _Class("CMAmbientPressureData")
CMRecordedPressureData = _Class("CMRecordedPressureData")
CMDeviceMotion = _Class("CMDeviceMotion")
CMAltitudeData = _Class("CMAltitudeData")
CMAccelerometerData = _Class("CMAccelerometerData")
CMRecordedAccelerometerData = _Class("CMRecordedAccelerometerData")
CMNatalieData = _Class("CMNatalieData")
CMMotionActivityManager = _Class("CMMotionActivityManager")
CMSedentaryTimer = _Class("CMSedentaryTimer")
CMSedentaryTimer_Internal = _Class("CMSedentaryTimer_Internal")
CLNotifierServiceAdapter = _Class("CLNotifierServiceAdapter")
CLGyroCalibrationDatabaseAdapter = _Class("CLGyroCalibrationDatabaseAdapter")
CLGeomagneticModelProviderAdapter = _Class("CLGeomagneticModelProviderAdapter")
CLCompassDatabaseAdapter = _Class("CLCompassDatabaseAdapter")
CMStrideCalibrationEntryArray = _Class("CMStrideCalibrationEntryArray")
CMGyroDataArray = _Class("CMGyroDataArray")
CMAmbientPressureDataArray = _Class("CMAmbientPressureDataArray")
CMAccelerometerDataArray = _Class("CMAccelerometerDataArray")
