"""
Classes from the 'MessageUI' framework.
"""

try:
    from rubicon.objc import ObjCClass
except ValueError:

    def ObjCClass(name):
        return None


def _Class(name):
    try:
        return ObjCClass(name)
    except NameError:
        return None


MFStringAccumulator = _Class("MFStringAccumulator")
MFSpringAnimationDelegate = _Class("MFSpringAnimationDelegate")
MFSoundController = _Class("MFSoundController")
_MFSoundBehaviorOverridesMonitor = _Class("_MFSoundBehaviorOverridesMonitor")
MFSimpleAnimationCoordinator = _Class("MFSimpleAnimationCoordinator")
MFSendMailIntentDonation = _Class("MFSendMailIntentDonation")
MFScannedDocumentConverter = _Class("MFScannedDocumentConverter")
_MFTableCellAttributesCache = _Class("_MFTableCellAttributesCache")
MFAddressConcatenator = _Class("MFAddressConcatenator")
_MFCRRecentContactABContext = _Class("_MFCRRecentContactABContext")
MFPreferencesURL = _Class("MFPreferencesURL")
MFPopupButtonItem = _Class("MFPopupButtonItem")
MFPlaceholderMessageRewriter = _Class("MFPlaceholderMessageRewriter")
MFPhotoPickerProgressItem = _Class("MFPhotoPickerProgressItem")
MFPhotoPickerProgressManager = _Class("MFPhotoPickerProgressManager")
MFMixedMessageFragment = _Class("MFMixedMessageFragment")
_MFMessageURLProtocolRegistry = _Class("_MFMessageURLProtocolRegistry")
MFMessageBodyStringAccumulator = _Class("MFMessageBodyStringAccumulator")
_MFMessageBodyConsumableNewline = _Class("_MFMessageBodyConsumableNewline")
MFMessageBodyElement = _Class("MFMessageBodyElement")
_MFMessageBodyHTMLElement = _Class("_MFMessageBodyHTMLElement")
_MFParsedHTMLNode = _Class("_MFParsedHTMLNode")
_MFParsedHTMLText = _Class("_MFParsedHTMLText")
_MFParsedHTMLTag = _Class("_MFParsedHTMLTag")
MFMessageBodyParserObject = _Class("MFMessageBodyParserObject")
MFMessageBodySubparser = _Class("MFMessageBodySubparser")
MFMessageBodyOriginalTextSubparser = _Class("MFMessageBodyOriginalTextSubparser")
MFMessageBodyParser = _Class("MFMessageBodyParser")
MFMessageBodyHTMLParser = _Class("MFMessageBodyHTMLParser")
MFMediaExporter = _Class("MFMediaExporter")
MFMailSignatureController = _Class("MFMailSignatureController")
MFMailPopoverManager = _Class("MFMailPopoverManager")
_MFMailCompositionContext = _Class("_MFMailCompositionContext")
_MFNSShadow = _Class("_MFNSShadow")
_MFValueTransformer = _Class("_MFValueTransformer")
_MFNSShadowTransformer = _Class("_MFNSShadowTransformer")
_MFFontToFontDescriptorTransformer = _Class("_MFFontToFontDescriptorTransformer")
_MFMailComposeAttachmentWrapper = _Class("_MFMailComposeAttachmentWrapper")
_MFMailComposeAttachmentLoader = _Class("_MFMailComposeAttachmentLoader")
_MFQLItemDataProvider = _Class("_MFQLItemDataProvider")
MFMailComposeContactsSearchController = _Class("MFMailComposeContactsSearchController")
MFMailAccountProxyGenerator = _Class("MFMailAccountProxyGenerator")
_MFMailAccountProxySource = _Class("_MFMailAccountProxySource")
MFMailAccountProxy = _Class("MFMailAccountProxy")
MFLANHandoffAgent = _Class("MFLANHandoffAgent")
MFLANHandoffContext = _Class("MFLANHandoffContext")
MFHardwareJPEGScaler = _Class("MFHardwareJPEGScaler")
MFFontMetricCache = _Class("MFFontMetricCache")
MFFileAttachment = _Class("MFFileAttachment")
MFDropTarget = _Class("MFDropTarget")
MFDragSource = _Class("MFDragSource")
MFDataDetectors = _Class("MFDataDetectors")
MFContactsSearchResultsModel = _Class("MFContactsSearchResultsModel")
MFContactsSearchManager = _Class("MFContactsSearchManager")
MFContactsSearchTaskContext = _Class("MFContactsSearchTaskContext")
MFComposeTypeFactory = _Class("MFComposeTypeFactory")
MFComposeTextStyle = _Class("MFComposeTextStyle")
MFComposeRecipientOriginContext = _Class("MFComposeRecipientOriginContext")
MFComposeRecipients = _Class("MFComposeRecipients")
MFComposeDisplayMetrics = _Class("MFComposeDisplayMetrics")
MFComposeRecipient = _Class("MFComposeRecipient")
_MFPlaceholderComposeRecipient = _Class("_MFPlaceholderComposeRecipient")
MFRecentComposeRecipient = _Class("MFRecentComposeRecipient")
MFComposeRecipientGroup = _Class("MFComposeRecipientGroup")
MFRecentComposeRecipientGroup = _Class("MFRecentComposeRecipientGroup")
MFCalendarComposeRecipient = _Class("MFCalendarComposeRecipient")
_MFAutocompleteResultsTableViewModel = _Class("_MFAutocompleteResultsTableViewModel")
_MFTableViewModelDiff = _Class("_MFTableViewModelDiff")
MFAttachmentPasteboardRepresentation = _Class("MFAttachmentPasteboardRepresentation")
MFAttachmentDragPreviewInfo = _Class("MFAttachmentDragPreviewInfo")
MFWebKitMainThread = _Class("MFWebKitMainThread")
MFAlertOverlayController = _Class("MFAlertOverlayController")
MFReformattedAddress = _Class("MFReformattedAddress")
MFAddressPickerReformatter = _Class("MFAddressPickerReformatter")
_MFCountableMatchesContext = _Class("_MFCountableMatchesContext")
MFAddressBookManager = _Class("MFAddressBookManager")
_MFMailComposeContentVariation = _Class("_MFMailComposeContentVariation")
MFPlaceholderMailDeliveryUI = _Class("MFPlaceholderMailDeliveryUI")
MFMailDropMailDeliveryUI = _Class("MFMailDropMailDeliveryUI")
MFComposeAttachmentInfo = _Class("MFComposeAttachmentInfo")
MFCenteredTextAttachment = _Class("MFCenteredTextAttachment")
_MFAtomTextAttachment = _Class("_MFAtomTextAttachment")
_MFAtomAttachment = _Class("_MFAtomAttachment")
_MFAtomTextSelectionRect = _Class("_MFAtomTextSelectionRect")
_MFAtomViewTextSelectionRect = _Class("_MFAtomViewTextSelectionRect")
MFPersonTransformer = _Class("MFPersonTransformer")
MFMailIntentTransformer = _Class("MFMailIntentTransformer")
MFBarButtonItem = _Class("MFBarButtonItem")
MFMessageURLProtocol = _Class("MFMessageURLProtocol")
MFAtomIcon = _Class("MFAtomIcon")
MFSpringAnimation = _Class("MFSpringAnimation")
_MFSearchProcessResultsOperation = _Class("_MFSearchProcessResultsOperation")
_MFSearchAddResultsOperation = _Class("_MFSearchAddResultsOperation")
MFContactsSearchOperation = _Class("MFContactsSearchOperation")
MFContactsAutocompleteSearchOperation = _Class("MFContactsAutocompleteSearchOperation")
MFComposeActivityHandoffOperation = _Class("MFComposeActivityHandoffOperation")
_MFSecureMIMEPersonHeaderLabel = _Class("_MFSecureMIMEPersonHeaderLabel")
MFSecureMIMEPersonHeaderView = _Class("MFSecureMIMEPersonHeaderView")
MFRoundProgressView = _Class("MFRoundProgressView")
MFProgressView = _Class("MFProgressView")
MFModernLabelledAtomList = _Class("MFModernLabelledAtomList")
MFModernAtomBackgroundView = _Class("MFModernAtomBackgroundView")
MFModernAtomIconView = _Class("MFModernAtomIconView")
MFMessageContentProgressLayer = _Class("MFMessageContentProgressLayer")
MFMessageContentLoadingView = _Class("MFMessageContentLoadingView")
MFComposeHeaderView = _Class("MFComposeHeaderView")
MFComposeRecipientView = _Class("MFComposeRecipientView")
MFComposeRecipientTextView = _Class("MFComposeRecipientTextView")
MFComposeDropPreviewView = _Class("MFComposeDropPreviewView")
MFAttachmentImageGenerator = _Class("MFAttachmentImageGenerator")
_MFAtomLayoutView = _Class("_MFAtomLayoutView")
MFMailComposeHeaderView = _Class("MFMailComposeHeaderView")
MFComposeWebContentVariationView = _Class("MFComposeWebContentVariationView")
MFComposeSubjectView = _Class("MFComposeSubjectView")
MFComposeMultiView = _Class("MFComposeMultiView")
MFComposeImageSizeView = _Class("MFComposeImageSizeView")
MFComposeFromView = _Class("MFComposeFromView")
MFMailComposeRecipientTextView = _Class("MFMailComposeRecipientTextView")
MFMailComposeToField = _Class("MFMailComposeToField")
MFMailComposeNavigationBarTitleView = _Class("MFMailComposeNavigationBarTitleView")
MFComposeActionCardTitleView = _Class("MFComposeActionCardTitleView")
MFMailComposeView = _Class("MFMailComposeView")
MFRoundedCornersStackView = _Class("MFRoundedCornersStackView")
MFModernAtomView = _Class("MFModernAtomView")
MFModernComposeRecipientAtom = _Class("MFModernComposeRecipientAtom")
MFCorecipientsIndicatorAtom = _Class("MFCorecipientsIndicatorAtom")
_MFMailComposePlaceholderView = _Class("_MFMailComposePlaceholderView")
MFComposeScrollView = _Class("MFComposeScrollView")
MFComposeSubjectTextView = _Class("MFComposeSubjectTextView")
_MFAtomTextView = _Class("_MFAtomTextView")
_MFAtomFieldEditor = _Class("_MFAtomFieldEditor")
MFRecipientTableViewCell = _Class("MFRecipientTableViewCell")
MFPhotoPickerSectionHeaderView = _Class("MFPhotoPickerSectionHeaderView")
MFPhotoPickerCell = _Class("MFPhotoPickerCell")
MFHeaderLabelView = _Class("MFHeaderLabelView")
MFCaptionLabel = _Class("MFCaptionLabel")
_MFAtomTextViewBaselineLayoutStrut = _Class("_MFAtomTextViewBaselineLayoutStrut")
MFSearchShadowView = _Class("MFSearchShadowView")
MFPopupButton = _Class("MFPopupButton")
MFModernAddressAtom = _Class("MFModernAddressAtom")
MFAtomTextView = _Class("MFAtomTextView")
_MFMailRecipientTextField = _Class("_MFMailRecipientTextField")
_MFModernAddressAtomEffectButton = _Class("_MFModernAddressAtomEffectButton")
MFDimmableButton = _Class("MFDimmableButton")
MFConfirmationButton = _Class("MFConfirmationButton")
MFComposeTextColorButton = _Class("MFComposeTextColorButton")
MFComposeSMIMELockButton = _Class("MFComposeSMIMELockButton")
MFComposeSendAccessoryButton = _Class("MFComposeSendAccessoryButton")
MFComposeStyleSelectorButton = _Class("MFComposeStyleSelectorButton")
MFComposeFontSelectorButton = _Class("MFComposeFontSelectorButton")
MFComposeWebView = _Class("MFComposeWebView")
MFMailComposePlaceholderViewController = _Class(
    "MFMailComposePlaceholderViewController"
)
MFMailComposeInternalViewController = _Class("MFMailComposeInternalViewController")
MFMailComposeController = _Class("MFMailComposeController")
MFComposeStyleSelectorViewController = _Class("MFComposeStyleSelectorViewController")
MFComposeColorPickerController = _Class("MFComposeColorPickerController")
MFMailComposeRemoteViewController = _Class("MFMailComposeRemoteViewController")
MFContaineeInputViewController = _Class("MFContaineeInputViewController")
MFGroupDetailViewController = _Class("MFGroupDetailViewController")
MFAutocompleteResultsTableViewController = _Class(
    "MFAutocompleteResultsTableViewController"
)
MFPhotoPickerController = _Class("MFPhotoPickerController")
MFMessageComposeViewController = _Class("MFMessageComposeViewController")
MFMailComposeViewController = _Class("MFMailComposeViewController")
