"""
Classes from the 'MLCompute' framework.
"""

try:
    from rubicon.objc import ObjCClass
except ValueError:

    def ObjCClass(name):
        return None


def _Class(name):
    try:
        return ObjCClass(name)
    except NameError:
        return None


MLCDeviceGPUHeapAllocator = _Class("MLCDeviceGPUHeapAllocator")
_MLCANEReductionParameters = _Class("_MLCANEReductionParameters")
MLCLog = _Class("MLCLog")
MLCTensor = _Class("MLCTensor")
MLCStrings = _Class("MLCStrings")
MLCConvolutionDescriptor = _Class("MLCConvolutionDescriptor")
MLCDataHelper = _Class("MLCDataHelper")
_MLCGPUConvolutionTransposePadding = _Class("_MLCGPUConvolutionTransposePadding")
MLCMatMulDescriptor = _Class("MLCMatMulDescriptor")
MLCEmbeddingDescriptor = _Class("MLCEmbeddingDescriptor")
_MLCANEWeightFileOps = _Class("_MLCANEWeightFileOps")
_MLCANEUpsampleParameters = _Class("_MLCANEUpsampleParameters")
MLCYOLOLossDescriptor = _Class("MLCYOLOLossDescriptor")
MLCOptimizerDescriptor = _Class("MLCOptimizerDescriptor")
MLCDeviceCPU = _Class("MLCDeviceCPU")
MLCTensorData = _Class("MLCTensorData")
MLCCustomLayerTensor = _Class("MLCCustomLayerTensor")
MLCErrors = _Class("MLCErrors")
MLCMultiheadAttentionDescriptor = _Class("MLCMultiheadAttentionDescriptor")
MLCOptimizer = _Class("MLCOptimizer")
MLCAdamOptimizer = _Class("MLCAdamOptimizer")
MLCRMSPropOptimizer = _Class("MLCRMSPropOptimizer")
MLCSGDOptimizer = _Class("MLCSGDOptimizer")
MLCTensorOptimizerDeviceData = _Class("MLCTensorOptimizerDeviceData")
MLCLossDescriptor = _Class("MLCLossDescriptor")
MLCControlTreeNode = _Class("MLCControlTreeNode")
MLCLSTMDescriptor = _Class("MLCLSTMDescriptor")
_MLCGaussianRandomGenerator = _Class("_MLCGaussianRandomGenerator")
MLCGraph = _Class("MLCGraph")
MLCInferenceGraph = _Class("MLCInferenceGraph")
MLCTrainingGraph = _Class("MLCTrainingGraph")
MLCDeviceANE = _Class("MLCDeviceANE")
_MLCANEArithmeticParameters = _Class("_MLCANEArithmeticParameters")
MLCTensorDescriptor = _Class("MLCTensorDescriptor")
_MLCANEMatMulParameters = _Class("_MLCANEMatMulParameters")
_MLCANEConvolutionParameters = _Class("_MLCANEConvolutionParameters")
_MLCANEPoolingParameters = _Class("_MLCANEPoolingParameters")
MLCPoolingDescriptor = _Class("MLCPoolingDescriptor")
MLCDevice = _Class("MLCDevice")
MLCDeviceGPU = _Class("MLCDeviceGPU")
MLCPlatformInfo = _Class("MLCPlatformInfo")
_MLCANEIOSurfaceObject = _Class("_MLCANEIOSurfaceObject")
MLCDeviceOptimizer = _Class("MLCDeviceOptimizer")
_MLCANENormalizationParameters = _Class("_MLCANENormalizationParameters")
_MLCANENeuronParameters = _Class("_MLCANENeuronParameters")
MLCTensorParameter = _Class("MLCTensorParameter")
_MLCANEModelObject = _Class("_MLCANEModelObject")
_MLCANEConcatParameters = _Class("_MLCANEConcatParameters")
_MLCGPUInstanceNormDataSource = _Class("_MLCGPUInstanceNormDataSource")
_MLCGPUBatchNormDataSource = _Class("_MLCGPUBatchNormDataSource")
MLCLayer = _Class("MLCLayer")
MLCCompareLayer = _Class("MLCCompareLayer")
MLCInstanceNormalizationLayer = _Class("MLCInstanceNormalizationLayer")
MLCLSTMLayer = _Class("MLCLSTMLayer")
MLCSplitLayer = _Class("MLCSplitLayer")
MLCArithmeticLayer = _Class("MLCArithmeticLayer")
MLCMatMulLayer = _Class("MLCMatMulLayer")
MLCConcatenationLayer = _Class("MLCConcatenationLayer")
MLCMultiheadAttentionLayer = _Class("MLCMultiheadAttentionLayer")
MLCActivationLayer = _Class("MLCActivationLayer")
MLCEmbeddingLayer = _Class("MLCEmbeddingLayer")
MLCSliceLayer = _Class("MLCSliceLayer")
MLCDropoutLayer = _Class("MLCDropoutLayer")
MLCPhiLayer = _Class("MLCPhiLayer")
MLCLayerNormalizationLayer = _Class("MLCLayerNormalizationLayer")
MLCReshapeLayer = _Class("MLCReshapeLayer")
MLCReductionLayer = _Class("MLCReductionLayer")
MLCSoftmaxLayer = _Class("MLCSoftmaxLayer")
MLCConvolutionLayer = _Class("MLCConvolutionLayer")
MLCGramMatrixLayer = _Class("MLCGramMatrixLayer")
MLCConditionalLayer = _Class("MLCConditionalLayer")
MLCUpsampleLayer = _Class("MLCUpsampleLayer")
MLCTransposeLayer = _Class("MLCTransposeLayer")
MLCFullyConnectedLayer = _Class("MLCFullyConnectedLayer")
MLCLossLayer = _Class("MLCLossLayer")
MLCYOLOLossLayer = _Class("MLCYOLOLossLayer")
MLCGroupNormalizationLayer = _Class("MLCGroupNormalizationLayer")
MLCPaddingLayer = _Class("MLCPaddingLayer")
MLCPoolingLayer = _Class("MLCPoolingLayer")
MLCBatchNormalizationLayer = _Class("MLCBatchNormalizationLayer")
_MLCCPULayer = _Class("_MLCCPULayer")
_MLCCPUReshape = _Class("_MLCCPUReshape")
_MLCCPUSlice = _Class("_MLCCPUSlice")
_MLCCPUArithmetic = _Class("_MLCCPUArithmetic")
_MLCCPUPooling = _Class("_MLCCPUPooling")
_MLCCPUConvolution = _Class("_MLCCPUConvolution")
_MLCCPUCompare = _Class("_MLCCPUCompare")
_MLCCPULSTM = _Class("_MLCCPULSTM")
_MLCCPUEmbedding = _Class("_MLCCPUEmbedding")
_MLCCPUGramMatrix = _Class("_MLCCPUGramMatrix")
_MLCCPUFullyConnected = _Class("_MLCCPUFullyConnected")
_MLCCPUReduction = _Class("_MLCCPUReduction")
_MLCCPUMHAttention = _Class("_MLCCPUMHAttention")
_MLCCPUNeuron = _Class("_MLCCPUNeuron")
_MLCCPUDropout = _Class("_MLCCPUDropout")
_MLCCPUMatMul = _Class("_MLCCPUMatMul")
_MLCCPUSplit = _Class("_MLCCPUSplit")
_MLCCPUSoftmax = _Class("_MLCCPUSoftmax")
MLCActivationDescriptor = _Class("MLCActivationDescriptor")
_MLCGPUWeightsConvolution = _Class("_MLCGPUWeightsConvolution")
_MLCGPULayer = _Class("_MLCGPULayer")
_MLCGPUSplit = _Class("_MLCGPUSplit")
_MLCGPUGroupNormalization = _Class("_MLCGPUGroupNormalization")
_MLCGPUArithmetic = _Class("_MLCGPUArithmetic")
_MLCGPUMHAttention = _Class("_MLCGPUMHAttention")
_MLCGPUSlice = _Class("_MLCGPUSlice")
_MLCGPUSoftmax = _Class("_MLCGPUSoftmax")
_MLCGPUTranspose = _Class("_MLCGPUTranspose")
_MLCGPUReduction = _Class("_MLCGPUReduction")
_MLCGPULSTM = _Class("_MLCGPULSTM")
_MLCGPUUpsample = _Class("_MLCGPUUpsample")
_MLCGPUPooling = _Class("_MLCGPUPooling")
_MLCGPUGramMatrix = _Class("_MLCGPUGramMatrix")
_MLCGPUBatchNormalization = _Class("_MLCGPUBatchNormalization")
_MLCGPUFullyConnected = _Class("_MLCGPUFullyConnected")
_MLCGPUCompare = _Class("_MLCGPUCompare")
_MLCGPUReshape = _Class("_MLCGPUReshape")
_MLCGPULayerNormalization = _Class("_MLCGPULayerNormalization")
_MLCGPUDropout = _Class("_MLCGPUDropout")
_MLCGPUNeuron = _Class("_MLCGPUNeuron")
_MLCGPUMatMul = _Class("_MLCGPUMatMul")
_MLCGPUInstanceNormalization = _Class("_MLCGPUInstanceNormalization")
_MLCGPUPadding = _Class("_MLCGPUPadding")
_MLCGPUConvolution = _Class("_MLCGPUConvolution")
MLCDeviceOps = _Class("MLCDeviceOps")
MLCGPUDeviceOps = _Class("MLCGPUDeviceOps")
MLCMHAGPUDeviceOps = _Class("MLCMHAGPUDeviceOps")
MLCLayerNormGPUDeviceOps = _Class("MLCLayerNormGPUDeviceOps")
MLCMultiGPUDeviceOps = _Class("MLCMultiGPUDeviceOps")
MLCRNNGPUDeviceOps = _Class("MLCRNNGPUDeviceOps")
MLCANEDeviceOps = _Class("MLCANEDeviceOps")
MLCCPUDeviceOps = _Class("MLCCPUDeviceOps")
MLCSliceCPUDeviceOps = _Class("MLCSliceCPUDeviceOps")
MLCRNNCPUDeviceOps = _Class("MLCRNNCPUDeviceOps")
MLCMHACPUDeviceOps = _Class("MLCMHACPUDeviceOps")
_MLCGPUGroupNormDataSource = _Class("_MLCGPUGroupNormDataSource")
MLCGPUHelper = _Class("MLCGPUHelper")
