# This file is generated by objective.metadata
#
# Last update: Tue Jun 26 22:14:34 2018

import objc, sys

if sys.maxsize > 2 ** 32:
    def sel32or64(a, b): return b
else:
    def sel32or64(a, b): return a
if sys.byteorder == 'little':
    def littleOrBig(a, b): return a
else:
    def littleOrBig(a, b): return b

misc = {
}
constants = '''$NLLanguageAmharic$NLLanguageArabic$NLLanguageArmenian$NLLanguageBengali$NLLanguageBulgarian$NLLanguageBurmese$NLLanguageCatalan$NLLanguageCherokee$NLLanguageCroatian$NLLanguageCzech$NLLanguageDanish$NLLanguageDutch$NLLanguageEnglish$NLLanguageFinnish$NLLanguageFrench$NLLanguageGeorgian$NLLanguageGerman$NLLanguageGreek$NLLanguageGujarati$NLLanguageHebrew$NLLanguageHindi$NLLanguageHungarian$NLLanguageIcelandic$NLLanguageIndonesian$NLLanguageItalian$NLLanguageJapanese$NLLanguageKannada$NLLanguageKhmer$NLLanguageKorean$NLLanguageLao$NLLanguageMalay$NLLanguageMalayalam$NLLanguageMarathi$NLLanguageMongolian$NLLanguageNorwegian$NLLanguageOriya$NLLanguagePersian$NLLanguagePolish$NLLanguagePortuguese$NLLanguagePunjabi$NLLanguageRomanian$NLLanguageRussian$NLLanguageSimplifiedChinese$NLLanguageSinhalese$NLLanguageSlovak$NLLanguageSpanish$NLLanguageSwedish$NLLanguageTamil$NLLanguageTelugu$NLLanguageThai$NLLanguageTibetan$NLLanguageTraditionalChinese$NLLanguageTurkish$NLLanguageUkrainian$NLLanguageUndetermined$NLLanguageUrdu$NLLanguageVietnamese$NLTagAdjective$NLTagAdverb$NLTagClassifier$NLTagCloseParenthesis$NLTagCloseQuote$NLTagConjunction$NLTagDash$NLTagDeterminer$NLTagIdiom$NLTagInterjection$NLTagNoun$NLTagNumber$NLTagOpenParenthesis$NLTagOpenQuote$NLTagOrganizationName$NLTagOther$NLTagOtherPunctuation$NLTagOtherWhitespace$NLTagOtherWord$NLTagParagraphBreak$NLTagParticle$NLTagPersonalName$NLTagPlaceName$NLTagPreposition$NLTagPronoun$NLTagPunctuation$NLTagSchemeLanguage$NLTagSchemeLemma$NLTagSchemeLexicalClass$NLTagSchemeNameType$NLTagSchemeNameTypeOrLexicalClass$NLTagSchemeScript$NLTagSchemeTokenType$NLTagSentenceTerminator$NLTagVerb$NLTagWhitespace$NLTagWord$NLTagWordJoiner$'''
enums = '''$NLModelTypeClassifier@0$NLModelTypeSequence@1$NLTaggerJoinContractions@32$NLTaggerJoinNames@16$NLTaggerOmitOther@8$NLTaggerOmitPunctuation@2$NLTaggerOmitWhitespace@4$NLTaggerOmitWords@1$NLTokenUnitDocument@3$NLTokenUnitParagraph@2$NLTokenUnitSentence@1$NLTokenUnitWord@0$NLTokenizerAttributeEmoji@4$NLTokenizerAttributeNumeric@1$NLTokenizerAttributeSymbolic@2$'''
misc.update({})
r = objc.registerMetaDataForSelector
objc._updatingMetadata(True)
try:
    r(b'NLModel', b'modelWithContentsOfURL:error:', {'arguments': {3: {'type_modifier': b'o'}}})
    r(b'NLModel', b'modelWithMLModel:error:', {'arguments': {3: {'type_modifier': b'o'}}})
    r(b'NLTagger', b'enumerateTagsInRange:unit:scheme:options:usingBlock:', {'arguments': {6: {'callable': {'retval': {'type': b'v'}, 'arguments': {0: {'type': b'^v'}, 1: {'type': b'Q'}, 2: {'type': b'{_NSRange=QQ}'}, 3: {'type': b'o^Z'}}}}}})
    r(b'NLTokenizer', b'enumerateTokensInRange:usingBlock:', {'arguments': {3: {'callable': {'retval': {'type': b'v'}, 'arguments': {0: {'type': b'^v'}, 1: {'type': b'{_NSRange=QQ}'}, 2: {'type': b'Q'}, 3: {'type': b'o^Z'}}}}}})
finally:
    objc._updatingMetadata(False)
expressions = {}

# END OF FILE
